### ISSUE TITLE
Provide a public API to register threads not created by Python for debugging

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#1009]
This can be done by simply wrapping `pydevd.settrace(suspend=False)`

**Comment by int19h** [comment]
Looking at it, we never actually had it as a *public* API in ptvsd. It was an internal function that just happened to do the right thing, and so we suggested it as a workaround for people who ran into issued, but it was not a stable API. You could see that it was internal, because you had to import it from `ptvsd.debugger` submodule, rather than the top-level package.

Since we're making it a public API here, we might as well revisit the naming and the placement, so that it looks the same as other functions, and the name is more expressive. I suggest `ptvsd.debug_this_thread()`.
