### ISSUE TITLE
CLI args have changed in PTVSD

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1129]
@DonJayamanne commented on [Mon Jan 28 2019](https://github.com/Microsoft/vscode-python/issues/4187)

Debugger tests are failing as the CLI has changed:

OLD CLI:
`['-m', 'ptvsd', '--host', 'localhost', '--wait', '--port', `${port}`, '--file', fileToDebug.fileToCommandArgument()]`

New CLI
`['-m', 'ptvsd', '--host', 'localhost', '--wait', '--port', `${port}`, fileToDebug.fileToCommandArgument()]`

We seem to have dropped `--file` from the CLI.

**Comment by karthiknadig** [comment]
I had not used `--file` when i wrote the usage for `ptvsd` in `readme.md` (in september https://github.com/Microsoft/ptvsd/commit/f8c3d847f8dda7b4d6759775dace27354dc0cdb5). I think it is safe to remove this usage.

**Comment by int19h** [comment]
`--file` was only supported by accident, because we passed a bunch of arguments to `pydevd` command line as is. It was never documented as supported anywhere, and it's not working anymore because we no longer launch pydevd via its command line, nor is compatibility with its command line our explicit goal.

Our switches to identify the target are the same as old ptvsd (3.x) and Python itself. So for file, it should be simply `ptvsd ... foo.py`.

It should also be noted that not all ptvsd switches are public in a sense that they're intended to be used by end users. The only ones that are considered public are those that show up when you do `-?`. Stuff like e.g. `--client` only makes sense for IDEs (but third party IDEs are a thing, so it's still public - just different category). And then there's stuff like `--subprocess-of`, which is strictly internal. Any tests in pydevd should only be testing the first two categories, rather than the latter.

With the new parser, the entirety of supported switches is in one place in the code, and can be used for reference:
https://github.com/Microsoft/ptvsd/blob/master/src/ptvsd/__main__.py#L119

**Comment by DonJayamanne** [comment]
If modified our scripts to remove the dropped arg `--file`
