### ISSUE TITLE
Debugger breaks into _ydev_execfile.py if there are syntax errors in pythonfile

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#113]
* Debug using VS Code experimental debugger
* Un select `Raised Exceptions`
* Select `Uncaught Exceptions`
* Debug python program with syntax errors
```python
if True
```

Debugger will break into `_pydev_execfile.py`

**Comment by huguesv** [comment]
What should it do? Not break perhaps?

**Comment by DonJayamanne** [comment]
> What should it do? Not break perhaps?

Yes, more precisely I'd expect it to just fall over with the runtime exception (error and stack trace printed in output window).

**Comment by int19h** [comment]
I'm confused. We had a bug previously where the problem was that it *didn't* break (but instead just let Python print the error stack and then terminate): #55.

I think breaking with an exception notification is preferable, because it's much clearer to the user what the problem is, even if running in external terminal. We can strip our and pydevd internal frames from that stack, though (not just here, but in general) - but technically that would be a part of the Just My Code feature.

**Comment by DonJayamanne** [comment]
When I reported issue #55, I wasn't using the terminal, I was using the standard VS Code debugger console (as that's the default output window in our extension). The problem then was that it was falling over without sending a message indicating the fact that the program ended.

**Couple of problems in #55:**
* When using `debug console` (non-terminal) user cannot see any output from program.
This has been resolved with #156, #157
* The program terminated, but debug adapter didn't know about this.
This too has been resolved, since then (the program now sends the exit, terminate and disconnect messages)

> I think breaking with an exception notification is preferable, because it's much clearer to the user what 

Agreed. Yes, this is an exception.
So, I guess, the real solution is to break on the actual syntax exception & not in pydev.
So the #26 should ideally resolve this issue.

Will close this issue in favor of #26
