### ISSUE TITLE
Break on uncaught exceptions not working when exception is raised from a background thread

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#114]
Python 3.6 32-bit + VSC
```py
import threading

def thread_func(n):
    raise Exception('argh')

th = threading.Thread(target = lambda: thread_func(1))
th.setDaemon(True)
th.start()

th = threading.Thread(target = lambda: thread_func(2))
th.setDaemon(True)
th.start()

#raise Exception('argh')
x = input("?")
print(x)
```
Set checkbox on "Uncaught exceptions", clear one on "Raised exceptions", and run. Note that exception is printed out to stdout, but there's nothing in VSC. Now uncomment the `raise` before `input` and run again - that one gets reported.

**Comment by huguesv** [comment]
Is there a repro for this?

**Comment by int19h** [comment]
I've updated the item with code.

Also, this behavior is identical in PyDev as well, so it's a pydevd limitation, and we'll need to fix it in there.

**Comment by fabioz** [comment]
I started to take a look at this issue... Initially I thought it'd be possible to just use the hooks for thread creation, but this isn't really possible (it wouldn't work if the debugger is attached to a running program and threads don't really raise their exceptions) so, changing the approach to use the tracing facilities as is the case for handled exceptions.

The idea is that only a few frames have to be traced for the exception info to trace unhandled exceptions (others can remain untraced). 

Namely:

- `threading.py` needs to trace functions: `_bootstrap_inner` , `__bootstrap_inner`.
- a frame where `frame.f_back` has the pydevd.py file with the `run` function.
- a frame where `frame.f_back` is None.

**Comment by fabioz** [comment]
I've finished implementing this feature on pydevd (on https://github.com/fabioz/PyDev.Debugger/commit/77819b14274814d865bac2f4debd09726bc3942e), but there are many conflicts to bring this to ptvsd because https://github.com/Microsoft/ptvsd/pull/426 is not integrated yet, so, instead of providing a pull request (which would make integrating https://github.com/Microsoft/ptvsd/pull/426 pretty difficult), I'll wait for that pull request to be integrated and then provide a pull request for this feature.
