### ISSUE TITLE
Investigate issues related to ports being in use with Flask/Django

### ISSUE THREAD

**Issue by qubitron** [Microsoft/ptvsd#1209]
See if there's anything we can do to avoid the issue

**Comment by qubitron** [comment]
- Cases where port is in use but the app listens on that port anyways
- Cases where stop debugging doesn't stop the current process

**Comment by karthiknadig** [comment]
On windows the underlying server used by django/flask does not set `SO_EXCLUSIVEADDRUSE` on the socket (might be intentional). They set `SO_REUSEADDR`, which on windows means that two processes can bind to the same address and port, (on linux binding is allowed only when there is no active listening socket). This issue can be addressed for the most part, if stop debugging killed the launched process. We already have a work item investigating proper shutdown of debugged processes.

However, this does not prevent the case where the server was already started externally.
