### ISSUE TITLE
subprocess arguments incorrectly escaped inside the debugger

### ISSUE THREAD

**Issue by huguesv** [Microsoft/ptvsd#1227]
@Meinersbur commented on [Sun Mar 10 2019](https://github.com/Microsoft/PTVS/issues/5155)

Consider the following program:
```
import sys
import subprocess

python = sys.executable
subprocess.check_call([python, '-c', 'print("A B")'])
subprocess.check_call([python, '-c', 'print("XY")'])
print("Done")
```

When executed with python from the command line this prints:
```
>python3 module1.py
A B
XY
Done

>python3 --version
Python 3.7.2
```

When executed from inside the Visual Studio 2017 debugger (same python 3.7.2, Python installed product 15.9.18254.1 according to Help -> About...), and Visual Studio 2019 preview, I get:
```
A B
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'XY' is not defined
```

The issue seems that the command line argument is only escaped when there is a space in it, but not deemed necessary with quotes. I checked the subprocess module, it correctly calls CreateProcess with escaped arguments in both cases. That is, the python debugger seems to hook the CreateProcess call, parses the command line, but re-escapes it insufficiently.

**Comment by int19h** [comment]
There are several other issues with the quoting code - it also doesn't handle terminal `\` well, for example, and it doesn't properly escape literal backslashes that precede quotes.

**Comment by int19h** [comment]
@fabioz, there's an interesting issue here - the updated quoting code (see commit referenced above) works fine, except for the case of an empty argument. The reason is that the different piece of code that splits the command line into arguments before doing the patching and quoting special-cases it in a way that's not consistent with any other argument:

https://github.com/Microsoft/ptvsd/blob/3c83d6be7e6c0584cd9f1555beef10ed59299ab9/src/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py#L275-L279

So, when it is parsing something like `foo "" "bar" "\"\""`, what you get is `['foo', '""', 'bar', '""]`. In other words, empty arguments don't get their quotes stripped, but everything else does. Note that this is lossy, too, because there's no way to distinguish between `""` and `"\"\""` after such parsing.

This doesn't look right, but the comment implies that it was added to deal with some other issue. Can you clarify why it's necessary? Perhaps we can come up with a better workaround for that.

**Comment by fabioz** [comment]
@int19h This code is actually a port of https://github.com/eclipse/eclipse.platform.debug/blob/master/org.eclipse.debug.core/core/org/eclipse/debug/core/DebugPlugin.java from java to Python... from the comment it seems that's a workaround only needed for `java.lang.ProcessImpl`, so, I think that on Python that workaround may not be needed (so, feel free to change that -- as a note, tests for this live in `tests_python.test_pydev_monkey.TestCase.test_str_to_args_windows` -- if you change it, it'd be nice to add the reference to the original code in the docstring too).
