### ISSUE TITLE
Can't initiate remote debugging from an IPython process

### ISSUE THREAD

**Issue by alendit** [Microsoft/ptvsd#1232]
## Environment data

- PTVSD version: 4.2.4
- OS and version: arch (latest)
- Python version: 3.7.2 (GCC 7.3.0)
- VS Code
- IPython: 7.2.0

## Actual behavior

When trying to connect to a remote jupyter process, the following happens:

```
import ptvsd
ptvsd.enable_attach(address=('127.0.0.1', 3000), redirect_output=True)
ptvsd.wait_for_attach()  # blocks
# attach to this address from a parallelly running vscode instance
# this works fine, call stack window displays the currently running threads
# the ipython execution continues
print("Test")
# stdout is displayed in the debugging console correctly
def test():
    v = 10
    breakpoint()  # alternatively ptvsd.break_into_debugger()
    return v
test()
# the function returns 10 without breaking
# ipython returns to interactive mode
```

## Expected  behavior

Last step should pause on the breakpoint.

Doing the same steps in a separate script produces the expected behaviour.

I guess it has something to do with jupyter threading / interactivity implementation, but I couldn't find what's going wrong from a cursory looks through `pydebd` code. Other debuggers, e.g. `ipdb`, `pudb`, work fine in the same setting.

**Comment by int19h** [comment]
The problem is that we consider any code that has filename like `<...>` to be filtered out as not-user-code for stepping purposes - and `breakpoint()` is considered a kind of step - unless it's `<string>`:

https://github.com/Microsoft/ptvsd/blob/1173a2b913e5bb0ec628038c0b71429cfd0c88d2/src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_filtering.py#L225

In case of IPython cells, they have names like `<ipython-input-2-1f2f30391028>`, so they get excluded in their entirety. 

As a workaround, this check can be disabled by setting `'debugStdLib': true` in your attach configuration in launch.json, and then the break works normally. Note that you won't see the source code of the cell in debugger when it breaks for the same reason (it needs a filename to do that). But you can still see the locals and the stack, and do blind stepping.

Still, this shouldn't be treated as non-user-code in the first place. @fabioz, @karthiknadig, what do you guys think? We can add another special case there for `<ipython...>` , similar to how `<string>` is handled, but perhaps it's better to treat `<...>` as user code by default, and only exclude known things like `<frozen...>`?

**Comment by fabioz** [comment]
I think it should be ok to  do that...  with some additional work, it
should be even possible to show the source (haven't checked, but if the
code is available somewhere it could be shown or in the worse case we could
use uncompile6 to provide the actual source for the function... note that
it's gpl, so we can't include it... but maybe we could ask users to install
separately? -- it also needs investigation to see if it can recover the
code preserving the line numbers -- ideally the cell contents would be
stored somewhere for us to access though... maybe they'd accept a patch if
they don't provide such access).

**Comment by int19h** [comment]
IPython kernel patches the `linecache` module and stores source code for all the cells there (which is also why `traceback` can show them in traces). So if we also use `linecache` to handle the `source` DAP request, instead of reading the file directly, we should get IPython cell source fetching for free.

**Comment by int19h** [comment]
This exact scenario should be working now with the most recent ptvsd. There are other issues that surface while trying to debug cells - e.g. stepping doesn't work on top level.
