### ISSUE TITLE
pydevd support for settrace without blocking

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1248]

**Comment by fabioz** [comment]
Note: it's not enough to simply not block (i.e.: skip the `ready_to_run` flag). 

Due to https://github.com/Microsoft/ptvsd/issues/1355 what needs to be done is that the whole tracing may need to be skipped until a `configurationDone` is given through the `DAP` (which would signal that the `on_setdebuggerproperty_request` and any other pre-conditions are already set and internal -- immutable -- caches can be constructed).

Some details here:

- the debugger needs to have an additional state where it's not functional but already has the tracing function set (because the tracing needs to be set at `pydevd.settrace` as it may not have another chance because `sys.settrace` **must** be called when running the thread to be traced).

- there may be different workflows internally if we're dealing with frame eval mode or not.


Another option could be not having any immutable cache in the debugger (so, `on_setdebuggerproperty_request` could be set at any time and any change would still enable the debugger to work, in which case the `ready_to_run` could be simply skipped) -- this needs some investigation to

**Comment by fabioz** [comment]
Note: starting to take a look at this item.

**Comment by fabioz** [comment]
Actually, I investigated the caches needed by `on_setdebuggerproperty_request` and added comments there (should be fixable by clearing the needed caches).

So, as far as things go, I think that if we ascertain that the configuration:

- `on_setdebuggerproperty_request`
- `on_launch` /`on_attach` (for path mapping and exclude filters)

is sent before breakpoints, things should work out by just making `pydevd.settrace` auto-set `ready_to_run = True` instead of waiting for it to be `True` (which is what already happens now in practice but with a thread instead of directly through the api).

There may be some performance impact if some frame which was in frame eval mode goes to tracing mode, and this would be already an issue when changing breakpoints -- https://github.com/Microsoft/ptvsd/issues/990 is already tracking this.
