### ISSUE TITLE
SystemExit is detected on Python 2 but not on Python 3

### ISSUE THREAD

**Issue by fabioz** [Microsoft/ptvsd#1279]
It seems that wrapper.py has some code to deal with this to auto-resume, but I didn't dig further... what's happening now is that on Python 2 the debugger breaks on `SystemExit(0)` but on Python 3 it doesn't (it should probably be consistent on both cases).

Note that on `SystemExit(1)` it always stops in any case.

**Comment by int19h** [comment]
There's a separate setting just for SystemExit(0) in ptvsd. We must not be implementing that one correctly on Python 2.

https://github.com/Microsoft/ptvsd/issues/841#issuecomment-436059489

**Comment by int19h** [comment]
This is a regression due to https://github.com/Microsoft/ptvsd/commit/957b01002dcd33f0f45232caf03b463d43b46a72#diff-b29f720860019d961dde440c375682f4R1127. In our `SystemExit` handling code, we expect exception names to be reported fully qualified - which means that it's `exceptions.SystemExit` on Python 2, and unqualified `SystemExit` on Python 3. With the change, the name that's reported from pydevd is `__class__.__name__`, which is always unqualified, so our check fails.

**Comment by int19h** [comment]
Not entirely sure it's a regression actually, the code might have been wrong all along - the test that was supposed to catch this has a defect.
