### ISSUE TITLE
import probablepeople makes VScode debugger startup extremely slow

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1288]
@fabiosangregorio commented on [Fri Mar 29 2019](https://github.com/Microsoft/vscode-python/issues/5015)

## Environment data

- VS Code version: 1.32.3
- Extension version (available under the Extensions sidebar): 2019.3.6215
- OS and version: Windows 10 64-bit
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.2 64-bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: probablepeople v0.5.4

## Expected behaviour
**main.py**
```python
import probablepeople
print('hello world')
```
The script above should take less than a second to complete with "Start debug" command.
`python main.py` command should take less than a second to complete.

## Actual behaviour
main.py takes about 20 seconds to complete with "Start debug" command.
`python main.py` command takes less than a second to complete. This is correct.

I tried several other imports from heavy modules to check if the problem occurred with other imports, but every import aside from `import probablepeople` runs in less than a second in debug mode.

## Steps to reproduce:
1. Create main.py with contents listed above
2. Start debug.
3. Wait 20 seconds.
4. The execution completes.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Starting Jedi Python language engine.
##########Linting Output - pylint##########

--------------------------------------------------------------------

Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)




```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

N/A

**Comment by karthiknadig** [comment]
I can repro this. Definitely there is perf issue here.

**Comment by fabiosangregorio** [comment]
Let me know if more information is needed.

**Comment by fabioz** [comment]
I investigated this and unfortunately there's not much to be done in the debugger side (although it could be fixed in the `probablepeople` side and possibly on Python itself).

So, what I found out is that the slowdown happens when `probablepeople` does: `from .ratios import ratios` -- the file imported (`probablepeople/ratios.py`) appears to have just a giant dictionary literal with more than `154k` lines.

Now, trying to run this with the simplest possible tracing function (a function which returns `None` to stop tracing that method), the slowdown is already there (it takes `14.22s` on my machine with the code below and when running the `import probablepeople` with the debugger, it takes `14.61s`, so, the debugger is actually doing the right thing by signalling that it doesn't want to trace that function, but it seems that Python itself has a major slowdown by just having the trace function set).

Code showing slowdown without debugger:

```
import time
initial_time = time.time()

def trace_func(frame, event, arg):
    return None

import sys
sys.settrace(trace_func)

print('start')
import probablepeople
print('finish')
print('%.2fs' % (time.time() - initial_time,))
```

The fix on `probablepeople` would be loading that data from a file instead of creating a giant dictionary -- on Python itself I'm not sure why it becomes so slower if the debugger has already signaled that the given context should not be traced (by returning `None` in the trace function), so, it could probably be treated as a bug (I haven't investigated further).

Closing this as there's not much to be done on the debugger side.

**Comment by fabioz** [comment]
@fabiosangregorio As a note, as a workaround you could launch externally and use the remote debugger (https://code.visualstudio.com/docs/python/debugging#_remote-debugging) and connect programatically (as you'd do with `pdb`) to avoid that initial slowdown.

**Comment by fabiosangregorio** [comment]
Thank you very much for investigating this issue. I might submit a PR to probablepeople if I can see major performance improvements in loading the data from a file.
