### ISSUE TITLE
Allow setBreakpoints before launch

### ISSUE THREAD

**Issue by gatesn** [Microsoft/ptvsd#1295]
## Environment data

- PTVSD version: 4.2.6
- OS and version: OSX Mojave
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8
- Using VS Code or Visual Studio: Custom

## Actual behavior

setBreakpoints throws claiming `launch` or `attach` must be issued first: https://github.com/Microsoft/ptvsd/blob/35be1abb32f992ad99072468f9f00fcc2ced08b6/src/ptvsd/wrapper.py#L1790

## Expected  behavior

The DAP homepage demonstrates setting breakpoints during the configuration phase. This would allow a client to setup breakpoints before the debugee starts executing. Otherwise there's a race condition right? Or am I missing something?

**Comment by int19h** [comment]
The configuration phase ends with `configurationDone`, and the actual launch/attach doesn't happen until then. So long as breakpoints are set before that event, there's no race.

That said, the spec says about the `initialized` event:

> This event indicates that the debug adapter is ready to accept configuration requests (e.g. SetBreakpointsRequest, SetExceptionBreakpointsRequest)". A debug adapter is expected to send this event when it is ready to accept configuration requests (but not before the ‘initialize’ request has finished).
>
> The sequence of events/requests is as follows:
> - adapters sends ‘initialized’ event (after the ‘initialize’ request has returned)
> - frontend sends zero or more ‘setBreakpoints’ requests
> - frontend sends one ‘setFunctionBreakpoints’ request
> - frontend sends a ‘setExceptionBreakpoints’ request if one or more ‘exceptionBreakpointFilters’ have 
 been defined (or if ‘supportsConfigurationDoneRequest’ is not defined or false)
> - frontend sends other future configuration requests
> - frontend sends one ‘configurationDone’ request to indicate the end of the configuration.

So it seems that we're not strictly conforming to the spec here, since we are not accepting the breakpoint requests immediately after `initialized`.

At the same time, the spec doesn't say where in the above sequence the launch/attach request should be - indeed, it doesn't even say that this happens before `configurationDone`, although that is the case in practice.

**Comment by gatesn** [comment]
So are you suggesting I should call `launch` before `configurationDone` to avoid the race? I was basing the sequence off the diagram here: https://microsoft.github.io/debug-adapter-protocol/img/init-launch.png

But you're right, I can't find anything in the spec saying `configurationDone` has to happen before `launch`.

**Comment by int19h** [comment]
In practice, all clients that we've tested (including VS and VS Code) do `launch` or `attach` before they do `configurationDone`. Given that `configurationDone` has a bunch of debug options in it that debugger needs to be aware of before it starts running code, I think that's by design, even though the spec doesn't reflect it currently.

**Comment by int19h** [comment]
Side note: if you're authoring a custom client, you might want to look at our tests - the actual test code in `test/func`, and `test/helpers/session.py` that those use. These capture the "de facto spec" that we're implementing currently. 

Also, setting `PTVSD_LOG_DIR` environment variable will give you the full DAP logs from the perspective of the debugger. You can use this to see how a typical debug session in VS or VSC looks like. E.g. in VSC, in launch.json, add this at the end of your configuration:
```json5
            "env": {
                "PTVSD_LOG_DIR": "/tmp",
            },
```
And if you want to do the same for your local copy of ptvsd, rather than the one VSC ships with, then:
```json5
            "customDebugger": true,  // ignore error squiggle here
            "env": {
                "PYTHONPATH": "~/src/ptvsd/src",
                "PTVSD_LOG_DIR": "/tmp",
            },
```
assuming that ~/src/ptvsd is the cloned repo.

**Comment by gatesn** [comment]
That's very helpful, thank you!
