### ISSUE TITLE
Remote Debugging does not show information in VARIABLES Panel on Linux.

### ISSUE THREAD

**Issue by quoctruong** [Microsoft/ptvsd#1325]
## Environment data

- PTVSD version: 4.2.7
- OS and version: Linux x64 4.17.0-3rodete2-amd64
- Python version (& distribution if applicable, e.g. Anaconda): Python 2.7.16rc1
- Using VS Code or Visual Studio:
VSCode
Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32

## Actual behavior

When a breakpoint is hit, only information on `CALL STACK` Panel is displayed, `VARIABLES` and `WATCH` Panels remain empty:
![image](https://user-images.githubusercontent.com/4371645/55761861-9ad56480-5a15-11e9-80bc-76f8cbb30ae2.png)

Please also see the `ptvsd` log here:
[ptvsd-1.log](https://github.com/Microsoft/ptvsd/files/3056515/ptvsd-1.log)

## Expected  behavior
Variables information should show up on the `VARIABLES` Panel

## Steps to reproduce:
Remote Debug any Python program on Linux.

**Comment by karthiknadig** [comment]
Strange, in the logs i don't see a variables request from VSC.

**Comment by quoctruong** [comment]
Also here is the configuration I'm using:
```
    {
      "name": "Attach (Remote Debug)",
      "type": "python",
      "request": "attach",
      "port": 3000,
      "host": "localhost",
      "pathMappings": [
        {
          "localRoot": "${workspaceFolder}/src",          
          "remoteRoot": "/app"
        }
      ]
    }
```

**Comment by int19h** [comment]
I think that's because stack trace came back with no frames:
```
D00105.395: IDE --> {
                "command": "stackTrace",
                "arguments": {
                    "threadId": 2,
                    "startFrame": 0,
                    "levels": 20
                },
                "type": "request",
                "seq": 12
            }

D00105.395: (while handling {'command': 'stackTrace', 'type': 'request', 'seq': 12})
            PYD <-- {
                "command": "stackTrace",
                "arguments": {
                    "threadId": "pid_1_id_139822985189416",
                    "startFrame": 0,
                    "levels": 20
                },
                "type": "request",
                "seq": 1000000015
            }

D00105.396: (requested while handling {'command': 'stackTrace', 'type': 'request', 'seq': 12})
            PYD --> {
                "type": "response",
                "request_seq": 1000000015,
                "success": true,
                "command": "stackTrace",
                "body": {
                    "stackFrames": [],
                    "totalFrames": 0
                },
                "seq": 60,
                "pydevd_cmd_id": 502
            }

D00105.396: (while handling {'command': 'stackTrace', 'type': 'request', 'seq': 12})
            IDE <-- {
                "type": "response",
                "seq": 25,
                "request_seq": 12,
                "success": true,
                "command": "stackTrace",
                "message": "",
                "body": {
                    "stackFrames": [],
                    "totalFrames": 0
                }
            }
```

@quoctruong, can you please clarify where app.py is located inside that Docker container? Is it inside a package, by chance?

**Comment by quoctruong** [comment]
It's just inside `/app` folder. I was able to debug this on MacOS with the `VARIABLES` Panel populated.

**Comment by int19h** [comment]
I have a theory. In this case, path mappings are:
```json5
                    "pathMappings": [
                        {
                            "localRoot": "/usr/local/google/home/quoct/cloudcode-projects/python-hello-world-1/src",
                            "remoteRoot": "/app"
                        }
                    ],
```

So when /app/app.py is mapped to VSC, it becomes /usr/local/google/home/quoct/cloudcode-projects/python-hello-world-1/src/app.py. 

Looking at the code for `_iter_visible_frames_info` and `make_get_thread_stack_message`, it looks like the former translates the filename to client according to path mappings, and only after that the latter applies filtering. So the path considered by the filter is going to be under /usr/local. Now consider the default library roots in `_get_default_library_roots`:
```py
        roots = [sys.prefix]
        if hasattr(sys, 'base_prefix'):
            roots.append(sys.base_prefix)
        if hasattr(sys, 'real_prefix'):
            roots.append(sys.real_prefix)
```
On Linux, `sys.prefix` is going to be either /usr or /usr/local, depending on the Python build. Either way, it seems that this would make app.py treated as library code. 

@quoctruong, can you check if moving your project to some location not under /usr fixes the problem for you?

**Comment by quoctruong** [comment]
@int19h You are correct. If I moved my project into the `tmp` folder, it actually fixes the problem.

Is this an intended behavior or a bug in `ptvsd`? I feel like a lot of the projects are going to be stored in some folder in `/usr` or `/usr/local`.

**Comment by int19h** [comment]
It's definitely a bug. A regression, even:

https://github.com/Microsoft/ptvsd/blob/66bd05a7ce48c461809631f8b31262eee04e2a87/src/ptvsd/wrapper.py#L110-L120

**Comment by fabioz** [comment]
I actually tried to remove ```sys.prefix, sys.base_prefix and sys.real_prefix```, but in this case the `ci` started failing lots of things: https://travis-ci.org/fabioz/ptvsd/jobs/520402771 (properly, because it's using the system python which has many things in `/usr/lib` and `/usr/local` and should not be traced unless we ask to debug system libraries).

So, I'm on a bit of a stalemate because a place like `/usr/local` apparently is meant to be used as a place for an admin to install programs for the user without affecting the whole system (i.e.: python packages would be on `/usr/local/lib/python2.7/site-packages`) and is not a place for development purposes (i.e.: that'd be in a /home/$user) directory -- see: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html.

@int19h any thoughts?

-- as a note, I still have to fix the issue that we should apply the filtering on the original source and not the translated source (which should fix this issue as the code being run lies in `/app` and not `/usr` in the remote machin).

**Comment by int19h** [comment]
The old code in wrapper.py (linked from the comment above) specifically retrieved site-package paths via the `site` module, which should take care of stdlib proper.

The main problem with /usr is that /usr/home is not an uncommon alias for /home (usually the latter being symlinked to the former) for historical reasons. On FreeBSD, it's still the default, although it shouldn't matter there, because `sys.prefix` for Python installed from packages would be /usr/local.

**Comment by fabioz** [comment]
On my Linux install, it seems that `sys.base_prefix`, `sys.real_prefix`, `site.getusersitepackages` and `site.getsitepackages` don't really exist (i.e.: trying to use them raises `AttributeError`).

The current code checks all those and checks for `site-packages` in the `sys.path`:

https://github.com/Microsoft/ptvsd/blob/master/src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_filtering.py#L149

From all of those, when using the system python -- and not a virtual env -- `sys.prefix` is the only one that resolves, so, I think leaving `sys.prefix` is the right thing here.

**Comment by int19h** [comment]
`sys.base_prefix` and `sys.real_prefix` are missing on 2.x, that's expected.

But `site` specifically documents `getsitepackages` and friends on both 2.7+ and 3.2+, and the doc doesn't say anything about the possibility of them being missing, so I'm not sure why it would behave like that? The only other thing that I can find along these lines is this: https://github.com/pypa/virtualenv/issues/737 - but it's about virtual envs specifically. Could it be an older Python version on your system?

For me, they seem to behave as expected:
```
int19h@ANGBAND ~> python -c "import site; print(site.getsitepackages())"
['/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
int19h@ANGBAND ~> python3 -c "import site; print(site.getsitepackages())"
['/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.7/dist-packages']
```

Either way, it seems that for those Python versions that do supply this information, at least, it provides more precise locations than `prefix` does. So I think that the code in `_get_default_library_roots` should try `getsitepackages` + `getusersitepackages` first, and if that does exist and returns a non-empty list, then just use it and skip `prefix` etc; otherwise, use those as a fallback. So it would be an either-or, not a union as it is today. It seems that this should always be the same or better than the current state of affairs - if what `getsitepackages` returns is under `sys.prefix`, then the latter is redundant; and if it's not, then `sys.prefix` is wrong in the first place.

**Comment by fabioz** [comment]
It's really odd (it seems reality and docs don't match).

I printed those in the ci:

i.e.: https://travis-ci.org/fabioz/ptvsd/jobs/520726103 

using the code: 
https://github.com/fabioz/ptvsd/commit/43cc5900392bb55f6e9884b5e7c87bee4f08673f#diff-aa6900c2c853f5d08b5240c3538ba446R20

and I get on Python 2.7:

```
sys.prefix: /home/travis/build/fabioz/ptvsd/.tox/py27
sys.real_prefix: /opt/python/2.7.15
Folder with "site-packages" in sys.path: /home/travis/build/fabioz/ptvsd/.tox/py27/lib/python2.7/site-packages
```

and on Python 3.7:

```
sys.prefix: /home/travis/build/fabioz/ptvsd/.tox/py37
sys.base_prefix: /home/travis/build/fabioz/ptvsd/.tox/py37
sys.real_prefix: /opt/python/3.7.1
Folder with "site-packages" in sys.path: /home/travis/build/fabioz/ptvsd/.tox/py37/lib/python3.7/site-packages
```

So, `getsitepackages()` and `getusersitepackages()` are not available there too.

Anyways, I agree with your suggestion, so, I'll change the code so that it checks for the info on `site` and then falls back to the info on `sys` if it's not available (besides fixing the issue where we filter based on the translated file and not the original file).

**Comment by fabioz** [comment]
@int19h can you also print `sys.prefix`, `sys.base_prefix` and `sys.real_prefix` on your machine (I'm curious to see if there are things missing from `site.getsitepackages()` and `site.getusersitepackages()`).

-- as a note, we should probably also add that information to the logging to help us diagnose issues like that (will add this to the pull request).

**Comment by fabioz** [comment]
I've done the change but it's still not ok on the `pydevd` ci (which creates a virtualenv instead of using the one from the system).

What I have in this case is the following:

```
sys.prefix: /home/travis/miniconda2/envs/build_env
sys.base_prefix: /home/travis/miniconda2/envs/build_env
site.getusersitepackages(): /home/travis/.local/lib/python3.7/site-packages
site.getsitepackages(): ['/home/travis/miniconda2/envs/build_env/lib/python3.7/site-packages']
Folder with "site-packages" in sys.path: /home/travis/miniconda2/envs/build_env/lib/python3.7/site-packages
```

And I'm hitting breakpoints in files such as:

`/home/travis/miniconda2/envs/build_env/lib/python3.7/tokenize.py`

-- so, although `sys.prefix` is probably more generic than it should, I see no other way to get `/home/travis/miniconda2/envs/build_env/lib/python3.7/` right now (so, for now I'll keep the existing approach of always including `sys.prefix`).

**Comment by int19h** [comment]
I believe Tox uses virtualenv internally, so on CI these would be expected.

Anyway, It looks like excluding `sys.prefix` breaks things in more scenarios than excluding it. And as you have said, if this filtering is done after path mapping, then this particular scenario would "just work"; and there's `debugStdLib` as an imperfect workaround.

I'm still curious as to the proper way to determine the location of Python stdlib, at least in new Python versions. @brettcannon, is there anything we are missing here?

**Comment by brettcannon** [comment]
https://docs.python.org/3/library/sysconfig.html#installation-paths, otherwise wherever `os.__file__` points to.
