### ISSUE TITLE
cannot step over, step out of, or continue from breakpoint on line with list comprehension

### ISSUE THREAD

**Issue by m27315** [microsoft/ptvsd#1375]
## Environment data

- PTVSD version: `ptvsd==4.2.8`
- OS and version: `Gentoo`
- Python version: `Python 2.7.5`
- Using `VS Code`
```
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.27-gentoo-r1
```

Incidentally, I am debugging a "remote" app running inside a Docker container on my developer machine.  I don't think this is relevant, because I am able to connect, set breakpoints and step.  My only issue is the one represented here.

## Actual behavior

After setting a breakpoint on a line containing a list comprehension, I am unable to "Continue", "Step Over", or "Step Out" without stepping through every iteration of the list comprehension.

## Expected  behavior

I would expect "Step Over" and "Continue" to both immediately move to the next line without having to step through every iteration of the comprehension.

## Steps to reproduce:
1. Set breakpoint on line with list comprehension.
2. Stop on breakpoint.
3. Observer that you must step through every iteration of loop, regardless of using "Continue", "Step Over" or "Step Out".

## Suggestion

Should one of these implement pdb's `until` command?

Ref:  https://stackoverflow.com/questions/6308569/how-do-you-skip-over-a-list-comprehension-in-pythons-debugger-pdb

**Comment by int19h** [comment]
Note that this also happens for something like:
```py
for x in range(0, 100): pass
```

There are two different issues here, though.

The first one is the one that is described in that StackOverflow question, and it's about the meaning of step regardless of breakpoints (the question didn't involve any). Currently, it effectively treats step as "until next loop iteration", and it should arguably rather be "until next line". 

The other issue is actually unrelated. Because you arrive at that line via a breakpoint, and do not deactivate it after, it is going to be hit every time Python evaluates *anything* on that line. This is not changed by step, continue etc - the behavior of any step is, "run until the step ends *or* a breakpoint is hit". This is by design, since it enables e.g. reporting of breakpoints in stepped-over functions. Same thing for Continue, which is basically "step to program end". I believe `pdb` has the same semantics for `until`. So, either way, you have to remove that breakpoint after hitting that line if you don't want to stop on it any further.

The workaround for the first issue is to set a breakpoint after the list comprehension / loop, and do Continue. If you don't have another breakpoint on the line with the loop, then it will effectively do a step over the loop.

But we need to look at the default behavior - in other contexts, we specifically implement Step Over as "step over line", not "step over statement". For example, given this:
```py
print('a'); print('b')
```
if you step before the first print, it will step over both. So there's inconsistency here between loops and everything else. We need to either consistently do statement-based stepping, or consistently do line-based stepping, to the extent permitted by Python debugging APIs and efficiency constraints.

**Comment by m27315** [comment]
Understood.  I appreciate the distinction you have made. ... Yes, I agree with your point about consistency.

From an end-user perspective, I can imagine cases where I would want both.

If I had to choose one, I would prefer "step over statements", even though it is counter-intuitive to me and opposed to my typical workflow, simply because I have a workaround this way but not the other.  

As a workaround, I disabled the breakpoint, executed "Step Over", and then re-enabled it, since I would eventually use it again.

However, if "Step Over" is changed to always be "Step Over Line", then I lose the granularity without recourse, except maybe to step in and then back out, which is also cumbersome and annoying.

I guess asking to support both - an explicit "Step Over Line" and "Step Over Statement" (or "Step Over Expression") - is out of the question?

Thanks for your kind consideration.  :smile:

**Comment by fabioz** [comment]
As a note, right now we mostly use the line events that CPython itself provides (so, for instance, in the case where there are 2 prints in the same line, CPython only gives one line event and in the line comprehension, CPython provides multiple line events).

Related to the issue with 2 prints on the same line, `Ned Batchelder` does provides some tricks  (rewriting line numbers in the frame object in:  https://nedbatchelder.com/blog/200804/wicked_hack_python_bytecode_tracing.html... we already do bytecode rewriting for some speedups to simulate programmatic breakpoints, so, it could be an option). 

On CPython 3.7, it seems to be possible to trace opcodes (i.e.: there's a new `opcode` which can be enabled in the tracing function passed in `sys.settrace` -- see: https://docs.python.org/3/library/sys.html). It was added in: https://bugs.python.org/issue31344 (although a comment by `Nick Coghlan` says that when that's turned on Python `is no longer guaranteed to work correctly`, which I find a bit troubling) -- and supporting that in the debugger may be a lot of work.

Regarding the line comprehension, I think that it should be something solved in the UI first and not only in the debugger through configurations (I think that within the same debugging session you may want both)... maybe the ideal would be having a functionality such as `run to line ignoring existing breakpoints` which would effectively remove all breakpoints, add a single breakpoint at a line (maybe the cursor or next line) and do a continue and when it's hit undo it all (so, maybe 2 new actions, one for run to cursor line and another for run to next line). It could all be done in the UI or there could be custom messages (custom messages would let us test that within the debugger).

**Comment by int19h** [comment]
It doesn't look like we can resolve this within the constraints imposed by Python itself.
