### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#1381]
[ptvsd-15112.log](https://github.com/Microsoft/ptvsd/files/3105235/ptvsd-15112.log)

**Comment by int19h** [comment]
This one is not a bug - note that the message in the log has `I` in the timestamp, i.e. it's informational. This is because we catch this exception, and wrap it in `EOFError` (which is also seen in the log), as part of the shutdown:

https://github.com/Microsoft/ptvsd/blob/master/src/ptvsd/ipcjson.py#L268-L280

https://github.com/Microsoft/ptvsd/blob/master/src/ptvsd/wrapper.py#L708-L715

**Comment by karthiknadig** [comment]
User reported this issue. I have asked them if this affect their run in any way. I will close it if it did not affect their run.

**Comment by karthiknadig** [comment]
User responded saying this does not affect their run. Will re-open if this blocks or causes actual issues during any run.
