### ISSUE TITLE
Django static files never finish loading

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1393]
@holyoaks commented on [Tue Apr 30 2019](https://github.com/Microsoft/vscode-python/issues/5521)

## Environment data

- VS Code version: 1.33.1
- Extension version (available under the Extensions sidebar): 2019.4.11987
- OS and version: Mac OS 10.14.5 Beta (18F118d)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.3
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv 
- Relevant/affected Python packages and their versions: django 2.2

## Expected behaviour

When debugging a django application, if there is more than one static file being loaded in the page, all static files will load without any issue.

## Actual behaviour

When debugging a django application, if there is more than one static file being loaded in the page, at least one of the files will stall and never load. The browser shows "pending" and finally cancels the load after several minutes. Impossible to use VS Code with Python for development and debugging with this behavior.

## Steps to reproduce:
1. Create new django app, with one view, one url
2. Create a template for the view to render
3. In that template, load two css files, with two images being loaded into the template in style defined in css file.
4. Debug the django app, and the page will never completely load.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
<output is empty. Nothing returns>
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
<Don't see Enable source map support for extension debugging> Screenshot attached

```

<img width="1004" alt="Screen Shot 2019-04-30 at 9 14 02 AM" src="https://user-images.githubusercontent.com/5797525/56968205-588cd800-6b28-11e9-85d5-8be14b4307d2.png">

---

@DonJayamanne commented on [Tue Apr 30 2019](https://github.com/Microsoft/vscode-python/issues/5521#issuecomment-488052691)

* Please could you provide a sample repo we can use to replicate this at our end?
* What version of django are you using?
* Please could you provide the contents of the `Debug Configuration` (from `launch.json`) that you are using. 

> In that template, load two css files, with two images being loaded into the template in style defined in css file.

* Does removing the css files & the image result in the page being loaded?

---

@holyoaks commented on [Tue Apr 30 2019](https://github.com/Microsoft/vscode-python/issues/5521#issuecomment-488132108)

A sample repo has been uploaded to [https://github.com/holyoaks/djangotest](url)
Django 2.2
the debug configuration is shown below

`
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "args": [
                "runserver",
                "--noreload",
                "--nothreading"
            ],
            "django": true
        }
    ]
`

If I have only ONE css or other static file, it seems to work. If I add additional, one or more works, but at least one does not.

I will also mention that I've tried my private repository, as well as the test repository I referenced above on a Windows 10 machine, and I do NOT get this behavior. I'm afraid it is something Mac specific, but can't say for certain. Thank you!

---

@DonJayamanne commented on [Tue Apr 30 2019](https://github.com/Microsoft/vscode-python/issues/5521#issuecomment-488153192)

Please can you try running this without debugging and confirm the problem persists.

---

@holyoaks commented on [Tue Apr 30 2019](https://github.com/Microsoft/vscode-python/issues/5521#issuecomment-488154926)

The problem does NOT exist if I:
1. activate the virtualenv in the Terminal; and,
2. run python manage.py runserver 

Only when debugging in VS Code. I have verified with both my simple repository and my private repository.

---

@ypapouin commented on [Wed May 01 2019](https://github.com/Microsoft/vscode-python/issues/5521#issuecomment-488247594)

Same problem here (only when debugging django using vscode), I'm trying to investigate on the origin but I'm unable to find it.
The project was previously working perfectly with its current existing virtualenv. 

I disabled extension auto-update and vscode auto-update and after having downgraded vscode to 1.32.3 and Python extension to 2019.2.5558, the problem still occurs.

Take a look on following timestamps, 12 minutes to load the main page .

```
(django-logicapp)  C:\Users\Yann\Documents\Python\django-logicapp>cd c:\Users\Yann\Documents\Python\django-logicapp && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && c:\Users\Yann\Documents\Python\django-logicapp/.venv/Scripts/python.exe c:\Users\Yann\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 53647 C:\Users\Yann\Documents\Python\django-logicapp/manage.py runserver --noreload --nothreading "
Performing system checks...

System check identified no issues (0 silenced).
May 01, 2019 - 10:28:32
Django version 2.1.4, using settings 'logicapp.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
INFO 2019-05-01 10:28:37,838 session 13220 20656 request index
INFO 2019-05-01 10:28:37,839 context 13220 20656 update_context_student
INFO 2019-05-01 10:28:37,840 context 13220 20656 AnonymousUser don't have student attribute
INFO 2019-05-01 10:28:37,840 context 13220 20656 {'version': 0, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000240ADEF2EB8>>, 'student': None}
INFO 2019-05-01 10:28:37,841 context 13220 20656 update_context_highschool
INFO 2019-05-01 10:28:37,842 context 13220 20656 AnonymousUser don't have highschool attribute
INFO 2019-05-01 10:28:37,843 context 13220 20656 {'version': 0, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000240ADEF2EB8>>, 'student': None, 'highschool': None}
INFO 2019-05-01 10:28:37,845 context 13220 20656 update_context_teacher
INFO 2019-05-01 10:28:37,846 context 13220 20656 {'version': 0, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000240ADEF2EB8>>, 'student': None, 'highschool': None, 'teacher': None}
INFO 2019-05-01 10:28:37,847 session 13220 20656 {'version': 0, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000240ADEF2EB8>>, 'student': None, 'highschool': None, 'teacher': None, 'title': 'Titre'}
INFO 2019-05-01 10:28:37,863 basehttp 13220 20656 "GET / HTTP/1.1" 200 6586
INFO 2019-05-01 10:28:37,917 basehttp 13220 20656 "GET /static/css/bootstrap/bootstrap.css HTTP/1.1" 304 0
INFO 2019-05-01 10:28:37,920 basehttp 13220 20656 "GET /static/js/jquery-3.3.1.js HTTP/1.1" 304 0
INFO 2019-05-01 10:28:37,923 basehttp 13220 20656 "GET /static/js/jquery.formset.js HTTP/1.1" 304 0
INFO 2019-05-01 10:28:37,926 basehttp 13220 20656 "GET /static/js/bootstrap.bundle.js HTTP/1.1" 304 0
INFO 2019-05-01 10:28:37,930 basehttp 13220 20656 "GET /static/js/notification.js HTTP/1.1" 304 0
INFO 2019-05-01 10:28:37,933 basehttp 13220 20656 "GET /static/js/base.js HTTP/1.1" 304 0
INFO 2019-05-01 10:30:33,147 basehttp 13220 20656 "GET /static/css/bootstrap/toggle/component-custom-switch.css HTTP/1.1" 304 0
INFO 2019-05-01 10:32:28,165 basehttp 13220 20656 "GET /static/css/fonts/font-awesome.css HTTP/1.1" 304 0
INFO 2019-05-01 10:34:23,648 basehttp 13220 20656 "GET /static/css/bootstrap/bootstrap-override.css HTTP/1.1" 200 9156
INFO 2019-05-01 10:36:18,777 basehttp 13220 20656 "GET /static/js/format.js HTTP/1.1" 304 0
INFO 2019-05-01 10:38:13,819 basehttp 13220 20656 "GET /static/js/js.cookie-2.2.0.min.js HTTP/1.1" 200 1714
INFO 2019-05-01 10:38:13,892 basehttp 13220 20656 "GET /media/images/btn1.png HTTP/1.1" 200 29558
INFO 2019-05-01 10:40:09,458 basehttp 13220 20656 "GET /media/images/btn2.png HTTP/1.1" 200 27016
```

---

@ypapouin commented on [Wed May 01 2019](https://github.com/Microsoft/vscode-python/issues/5521#issuecomment-488319268)

I tried VSCode-win32-x64-1.31.1 and VSCode-win32-x64-1.32.3 in portable mode with only the Python extension installed, it was still the same issue.

After some testing, the problem also exists in a standalone launch when I add `--nothreading`, and it also disappear from VSCode if I remove this argument from the `launch.json`.

So, if it's not VSCode neither the Python Extension, does a Windows 10 Update could be the culprit ?

---

@holyoaks commented on [Wed May 01 2019](https://github.com/Microsoft/vscode-python/issues/5521#issuecomment-488343917)

I can confirm that removing --nothreading from my debug configuration resolves the issue as well, on Mac OS. This must be either a VSCode or Python Extension issue

**Comment by int19h** [comment]
This requires a recent Django version to repro, but reproduces equally on Windows and Mac. It is also browser-dependent: Edge will not repro, but Chrome, Safari and Firefox will.

It is not a debugger bug. As @ypapouin noted, it reproduces if you start the server directly from command line without VSCode involved at all, so long as `--nothreading` is specified. 

I believe this is a manifestation of this issue:

https://code.djangoproject.com/ticket/16099
https://bugs.chromium.org/p/chromium/issues/detail?id=195550

Basically, most browsers will speculatively establish multiple connections to the server, on the basis that most pages require loading multiple resources anyway. However, they will not issue a GET request on those speculative connections until they know what to retrieve. If the server is single-threaded, as is the case with `--nothreading`, the request handling code might get an incoming connection, and then block waiting for any data to actually arrive on it - and in the meantime, it can't serve any more connections. If it so happens that the speculative connection is the one that the server `accept()`ed first, this effectively blocks all other connections, that the browser might be trying to actively use. 

I'm not entirely sure why it depends on the Django version, but presumably something changed in Django which (likely inadvertently) affected the order in which requests are served. It does not reproduce in Django 2.1.0-2.1.3, but 2.1.4+ consistently has it. 

So the real problem is that we still `--nothreading` by default in launch config. Per #1256, it doesn't seem to be needed, so https://github.com/Microsoft/vscode-python/issues/5116 should be able to go ahead, and would fix this issue. #1256 also mentions #4988 as the potential reason to keep it, but looking at the bug, the workaround there was *not* `--nothreading`, it was coincidental to the real workaround (disabling templates).

**Comment by int19h** [comment]
Also of note: our [Django tutorial](https://code.visualstudio.com/docs/python/tutorial-django) mentions this same issue:

> Note: If you use Chrome as your debugging browser, remove --nothreading due to Chromium issue 13043.

However, this is the only place anywhere in the documentation that talks about it. It is not mentioned on the main documentation page for the debugger, even though it talks about Django, and uses `--nothreading`. In the tutorial, this was added per #2303. Judging by the date on that issue, it was also Django 2.1.4.

Also, I suspect that the Django change in 2.1.4 that made this happen consistently is the fix for https://code.djangoproject.com/ticket/29849.

**Comment by DonJayamanne** [comment]
Will remove that argument in the extension. Thanks

**Comment by holyoaks** [comment]
Thanks all of you. I love VS Code and am glad to see the continuous improvement in the codebase.
