### ISSUE TITLE
Wait on abnormal exit doesn't wait if you raise ValueError

### ISSUE THREAD

**Issue by huguesv** [microsoft/ptvsd#1399]
## Environment data

- PTVSD version: latest master from today
- OS and version: win10
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7
- Using VS Code or Visual Studio: Visual Studio

## Actual behavior

Console window disappears

## Expected  behavior

Console window stays up. If you do the same with legacy debugger, it stays up.

## Steps to reproduce:
1. In tools/options/python/debugging, set wait on normal to false, wait on abnormal to true
2. F5 to run this code
```
raise ValueError('asdf')
```
3. Debugger breaks into code, press F5

**Comment by int19h** [comment]
It looks like we only treat `SystemExit` with non-zero exit code specifically as abnormal exit. So it doesn't cover the case where another exception is propagated all the way to the entry point.

Short-term, I think we should treat any exception that bubbles out to the entry point as an error. Unfortunately, it doesn't cover all cases - e.g. in attach scenarios we don't control the entry point at all. There are also possibilities such as `os._exit` that are inherently impossible detect from within the same process. 

Long-term, this functionality should be taken out-of-proc. This would make it foolproof, and vastly simpler to implement, since it'd only have to look at the exit code of the process. #1278 is related.

**Comment by karthiknadig** [comment]
This is addressed in the `dbg_adapter_refactor` branch.
