### ISSUE TITLE
Debug mpirun Python processes

### ISSUE THREAD

**Issue by KevinLucidyne** [microsoft/ptvsd#1427]
Create */home/bob/foobar.py* in [Visual Studio Code](https://code.visualstudio.com/) with the [VS Code Docker Extension](https://code.visualstudio.com/docs/azure/docker)

    import ptvsd
    import time
    ptvsd.enable_attach(address = ('0.0.0.0', 5678))
    ptvsd.wait_for_attach()
    time.sleep(2)
    print("all righty then")

Set a breakpoint on the last line.

Debug|Add Configuration

In *launch.json* add to "configurations"
```json
{
   "name": "Python Attach (Remote Debug ptsvd default)",
   "type": "python",
   "request": "attach",
   "pathMappings": [
       {
          "localRoot": "/home/bob", 
          "remoteRoot": "/home/bob" 
       }
    ],
            "port": 5678, 
            "host": "0.0.0.0" 
        },
```

    $ python -m pip install --user --upgrade ptvsd
    $ python foobar.py 

Start the debugger with configuration "Python Attach (Remote Debug ptsvd default)". It stops at the breakpoint.

But if I run *mpirun*
```
$ mpirun --allow-run-as-root -np 2 -H localhost:2 -bind-to none -map-by slot -x PATH -mca pml ob1 -mca btl ^openib python ./foobar.py
```

I get the error ```socket.error: [Errno 98] Address already in use```

Is there a way to assign multiple ports for an arbitrary number of processes in *launch.json* and in *foobar.py*?

**Comment by karthiknadig** [comment]
@KevinLucidyne in `foobar.py` you could add code to check for open port and cycle through port values manually before calling `enable_attach`. There is no mechanism in the debugger to do this directly.

However, you will need multiple Attach configs to attach to each of the processes. There is no single config that currently allows you to attach you to multiple process. @DonJayamanne do you see a way to do multiple connections?

I suggest the following alternative, using `ProcessPoolExecutor`:
The `foobar.py` should look like this:
```py
# The two lines below are needed in linux. Currently ptvsd does not support fork.
import multiprocessing
multiprocessing.set_start_method('spawn', True)
from concurrent.futures import ProcessPoolExecutor
import os
import time

def run_this():
    time.sleep(2)
    print("all righty then [process: %d]" % (os.getpid(),))


def main():
    with ProcessPoolExecutor() as executor:
        for _ in range(3):
            executor.submit(run_this)

if __name__ == '__main__':
    main()
```
Launch this using ptvsd with multi proc enabled:
```
python3 -m ptvsd --host 0.0.0.0 --port 5678 --wait --multiprocess ./foobar.py
```
Use this configuration to attach, note the `subProcess` setting below.
```js
{
    "name": "Attach",
    "type": "python",
    "request": "attach",
    "port": 5678,
    "host": "localhost",
    "pathMappings": [
        {
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "."
        }
    ],
    "subProcess": true,
    "redirectOutput": true,
},
```

![image](https://user-images.githubusercontent.com/3840081/57893275-2bfae080-77f7-11e9-8509-e166a9fe614c.png)

**Comment by int19h** [comment]
I haven't tried it with `enable_attach`, but with command line it's legal to specify 0 as a port to pick the first available one (we use that for multiproc).

However, there are no facilities currently to find out which port that ends up being. Perhaps we should expose it? There's already logic to retrieve it after the server socket is created in `start_server` in daemon.py, to send multiproc child process notification. It could also set a global variable on package root.

**Comment by KevinLucidyne** [comment]
If there's no existing way to do this, then maybe change `enable_attach` so that it accepts a list of address tuples?

**Comment by int19h** [comment]
I think you can implement try-until-succeed by catching that error from `enable_attach` and retrying with a different address/port in a loop.

JSON side is trickier. I'm not sure it's even possible to have a single configuration in launch.json to start multiple independent debug sessions. For Python multiprocessing, the one session that is started has to specifically tell VSC to attach to child processes, and it can do so because it knows what those processes are - but in your case, there's no parent/child relationship, they're all independent and don't know about each other. 

For now, I would suggest using something like [Jsonnet](https://jsonnet.org/) to generate a multi-configuration launch.json from a single template.

**Comment by fabioz** [comment]
I think what's wanted from the user side is creating a launch configuration which actually acts as a server (so, it waits for incoming connections at a given port instead of the other way around as is now and `ptvsd` would take care of new connections arriving and would talk to VSCode for new processes -- as is already the case for multiprocessing).

This should be one scenario we take into account once we make the split where `ptvsd` actually works as a debug adapter launching a separate process (and is how I think multiprocessing should work in general anyways where subprocesses connect to the same initial port where `ptvsd` is listening).

**Comment by KevinLucidyne** [comment]
@karthikananth not really what I'm looking for.  As you might have suspected, my example is a proxy for a much more complicated situation that requires the use of OpenMPI  and mpirun.

**Comment by karthiknadig** [comment]
@KevinLucidyne thank you for the input. We will consider this as a feature while doing the multi-process work.

**Comment by KevinLucidyne** [comment]
@int19h If I'm understanding you correctly, the problem with your workaround for JSON is that mpirun isn't going to provide a way to specify which debugger configuration is getting called.

You all have added the ability to attach the debugger by process id on Linux, right? So I could fire up the processes in mpirun and attach to them as a prelaunch task?  Is that correct?

**Comment by int19h** [comment]
I'm afraid attach-by-PID is not stable enough on Linux right now.

Now that I think about it, since you control the code in those processes, how about making *them* generate the JSON you need to attach to them? i.e. after you successfully call `enable_attach()`, get the port number, and have the process open launch.json in some shared location, and append a config for itself. 

Side note: this would all be much easier if VSC supported user-defined reverse connections, when debuggee connects to an open port on the IDE. This is already what we do for launch (F5), but it's not documented, and I don't think there's any way to have VSC just sit and wait for a connection outside of that one case currently. @DonJayamanne, what do you think?

**Comment by gramster** [comment]
Closing as we are unlikely to do anything here.
