### ISSUE TITLE
Step doesn't stop on next statement

### ISSUE THREAD

**Issue by huguesv** [microsoft/ptvsd#1456]
## Environment data

- PTVSD version: 4.2.10b1
- OS and version: Win10
- Python version (& distribution if applicable, e.g. Anaconda): 2.7 or 3.6
- Using VS Code or Visual Studio: VS

Note: This is using the code from PR https://github.com/microsoft/PTVS/pull/5318/files

## Actual behavior

Runs till the end of program

## Expected  behavior

Stop on line 2

## Steps to reproduce:
1. Write a program like this with 2 statements, put breakpoint on first statement

![image](https://user-images.githubusercontent.com/1696845/58133501-d3ea2280-7bd8-11e9-99fe-af9147121fec.png)

2. Start with F5, wait to hit the breakpoint
3. Press F10 to step

**Comment by huguesv** [comment]
[adapterhost.log](https://github.com/microsoft/ptvsd/files/3204742/adapterhost.log)

**Comment by karthiknadig** [comment]
This requires stop on entry to be on to repro.

**Comment by int19h** [comment]
Looking at the log, it looks like the first stopped event is for the breakpoint. Then after that is stepped over, the next stopped event has reason=entry (not step!), and VS automatically sent a continue response to it. 

So the problem is that we double-report the stop on first line. In this scenario, it should always be reported as a breakpoint stop (so that VS doesn't auto-continue), but we shouldn't then report a stop-at-entry at all. This is a case similar to when you step to the next line, and it also has a breakpoint; we only report the stop once.
