### ISSUE TITLE
Remove travis

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1477]

**Comment by fabioz** [comment]
@karthiknadig -- I think that it'd be nice to leave Travis.

I use it much more than the one on Azure because it automatically runs tests on any new branch on my own private fork, which doesn't seem to be the case for Azure... given that I create new branches to run almost daily, it becomes pretty tedious to manually configure Azure each time to target new branches (although it's possible that I'm missing something in Azure... if that's the case, please point me to the right direction).

**Comment by int19h** [comment]
Done for debugpy
