### ISSUE TITLE
Breakpoints Failing as of 2019.5.17059

### ISSUE THREAD

**Issue by knabb** [microsoft/ptvsd#1480]
## Environment data

- PTVSD version: 2019.5.17059
- OS and version: Mac OS or Windows
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio: VS Code

## Actual behavior

VS Code debugger is no longer stopping at our breakpoints as of version 2019.5.17059. We are seeing a lot of the message: "pydev debugger: warning: trying to add breakpoint to file that does not exist: /path/function.py (will have no effect)". We appear to get this message for each .py file.

This is a new issue. Yesterday, before the update to the 2019.5.17059 version, breakpoints were working properly. We have noticed it on multiple machines, some windows, some mac.

If we install the previous version (2019.4.12954), break points work properly again.

## Expected  behavior

Debugger should stop at breakpoints.

## Steps to reproduce:
We are using launch json that looks like this:
```
{
            "name": "debug test",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/test/debug.py",
            "cwd": "${workspaceFolder}/test/",
            "console": "integratedTerminal"
}
```

Hit F5 and see that none of the breakpoints are hit.

**Comment by karthiknadig** [comment]
This is caused by the extension adding pathmapping by default to launch config. This is the commit that introduced the issue.
https://github.com/microsoft/vscode-python/commit/1fad96f2730121ed2f61a9ec3b27750f5e46a796

The extension attempts to map workspace folder to current working directory. This was added to support certain multi-process scenarios. Looks like we will need to revert that and find alternate solution for those scenarios.

Extension will address this issue via: https://github.com/microsoft/vscode-python/issues/5839, https://github.com/microsoft/vscode-python/issues/5833

Temporary solution:
Add this to your launch.json
```js
{
            "name": "debug test",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/test/debug.py",
            "cwd": "${workspaceFolder}/test/",
            "console": "integratedTerminal",
            "pathMappings": [],
}
```

**Comment by knabb** [comment]
Thank you for the quick update.
