### ISSUE TITLE
Message processing/forwarding loop

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1486]

**Comment by int19h** [comment]
This got a bit more convoluted in light of the fact that the current ordering of messages is partially defined by the TS Python adapter in VSC, and when running directly against VSC the order is actually different. The TS adapter has some fairly complicated logic in it that needs to be partially replicated, and partially fixed because it orders things wrong - e.g. right now ptvsd actually gets `launch` *before* `initialize`!

But on the bright side, I found where the actual order, and permissible permutations, are documented: https://github.com/microsoft/vscode/issues/4902#issuecomment-368583522. So we don't have to guess anymore, and it's also clear why we had some of the issues we did. The catch is that both valid sequences require the ability to receive and handle requests while another request is still pending. I'm trying to determine if we need futures again 🤔 or can somehow hack this one case without, since we don't need them anywhere else.

Note also that this item effectively incorporates `initialize` and `configurationDone`, and a skeleton for `attach` and `launch`, due to them all being necessary in the initialization sequence. So it covers like half of #1489.

**Comment by fabioz** [comment]
As a note, I think the reordering should happen in `pydevd` for the cases that don't work (we shouldn't need threads for that, the reader thread should be able to requeue messages that arrive out of the expected order).

Also, I'm fixing the case where breakpoints appear before having the launch mappings to reapply breakpoints in my next pull request -- which is already doing this for the ipython related source mapping, so, that particular use-case should no longer be a constraint.

**Comment by fabioz** [comment]
Actually, I backed out from reapplying breakpoints after receiving a launch -- we really must wait for the launch and apply it before setting breakpoints because otherwise breakpoint validation can be incorrect. 

-- I created https://github.com/microsoft/ptvsd/issues/1501 to handle the reordering on `pydevd` (please add the limitations you see to that issue).

**Comment by int19h** [comment]
If we follow the diagram in the linked comment, I think we can avoid the breakpoint issue by using the "late case", i.e.:

1. Wait for `launch` or `attach` request with the necessary info.
2. While handling it, issue `initialized` event, and block waiting for `configurationDone`
3. IDE sends breakpoints in response to the above.
4. IDE eventually sends `configurationDone`.
5. Unblock and finish handling `launch` / `attach`, and send the response.

This should give us well-defined ordering of everything, in which breakpoint validation happens only when we have all the necessary info.

This means that the adapter should be able to handle this sequence correctly as well (i.e. while it doesn't need to apply breakpoints itself, it must be able to pass all messages to `pydevd` in this same order, including the concurrent part). Additionally, this way, the adapter can establish the socket connection to  `pydevd` on the very first step already, and so all other steps will be passing messages to a live instance (instead of saving them to pass them on later, when it gets enough info to connect).

**Comment by fabioz** [comment]
Seems good to me ;)
