### ISSUE TITLE
Remote debugging for built-in Python

### ISSUE THREAD

**Issue by EugeneZelenko** [microsoft/ptvsd#1518]
It'll be great to have possibility to embed use ptvsd_launcher.py into Python code started inside application with built-in Python interpreter with uses internal application's data and APIs. Currently ptvsd_launcher.py and its support code rely on parameter passed in sys.args, so it should use alternative way to pass parameters and/or alternative entry point.

**Comment by karthiknadig** [comment]
@EugeneZelenko Can you elaborate a bit more? I don't fully understand the scenario.

FYI. If you have a application with python loaded there, we have a feature to attach to that application via process id. See https://github.com/microsoft/ptvsd#attaching-to-a-running-process-by-id . This is currently supported up to python 3.6 . Support for 3.7+ is coming soon.

**Comment by EugeneZelenko** [comment]
Yes, I know about attachment to remote process. My point is to have possibility to launch ptvsd_launcher.py  without launching new instance of Python interpreter.

**Comment by int19h** [comment]
@EugeneZelenko 

If I understand everything correctly, `ptvsd.enable_attach` and `ptvsd.attach` are meant for this exact scenario (among others). If you control the host app, you can have it run that. If you only control the guest code, you can explicitly specify that stuff there. 

By ptvsd_launcher.py, I assume you mean the one in PTVS? https://github.com/microsoft/PTVS/blob/master/Python/Product/PythonTools/ptvsd_launcher.py

That one is not a part of ptvsd API, but more of an internal helper - and it is there in part because VS also needs to work with ptvsd 3.x, which is completely different internally. The entrypoint in ptvsd that it uses, `ptvsd.debugger()`, is intended solely for that purpose - it's compatible between 3.x and 4.x. 

For code that wants to work with modern ptvsd in a similar manner, you should do `from ptvsd.__main__ import main`, and invoke that. Note though that while you get to pass "command line" arguments to it as a list, it will still muck around with global `sys.argv`. But there's no way around it, because that's what the user code will look at once it starts, so ptvsd has to remove itself and its own switches in order to correctly simulate what Python normally does when you do `python foo.py`, `python -m foo` etc. Because of that, I would generally not recommend actually using that argument. Just pass it in sys.argv, and it will not be there by the time user code is running (except for any switches that are passed to user code).

Take a look at the code here, I think it's easier than trying to explain it:
https://github.com/microsoft/ptvsd/blob/f3b0bb0cdc99531c6d44881cd81f2b554b68cdb1/src/ptvsd/__main__.py

Better yet, use `runpy.run_module()`. We have not committed to `main()` being a public API quite yet, and the argument will likely go away in future releases. But running ptvsd as module will always remain supported. The benefit is that it's the same API whether you use it from CLI or programmatically, so it's not some weird rarely used case that you depend on now, and we break later.

If your scenario isn't covered by either `attach`, `enable_attach`, or `main` / `run_module`, then can you please tell a little bit more about the specifics?

**Comment by EugeneZelenko** [comment]
If it's safe to modify sys.args, sure, it'll be easier to replicate ptvsd_launcher.py in my application.

**Comment by int19h** [comment]
Yep. Modifying `sys.argv` is allowed. So this:
```py
sys.argv += ["--host", "localhost", "--port", "5678", "foo.py", "bar"]
runpy.run_module("ptvsd")
```
should behave exactly as if you did:
```sh
python -m ptvsd --host localhost --port 5678 foo.py bar
```
and in either case, if foo.py then does `print(sys.argv)`, it will say `["foo.py", "bar"]`

If this works for you, can you please go ahead and close the issue?

**Comment by EugeneZelenko** [comment]
Thank you for clarification! Just one more question: Python code is started from C++, so how could I tell ptvsd about this entrance point?

**Comment by int19h** [comment]
Not really, sorry - at least not in this way. Ptvsd CLI is meant to mimic Python itself - specifically, `python foo.py`, `python -m foo`, or `python -c "print(...)"`. Each of those is a special case, and has to be handled separately to ensure that it does the same thing that Python normally does.

But you can take the code that's there in `__main__.py`, and adapt it for your case. I don't think there's anything there that really needs to be inside the `ptvsd` package. Take a look at this snippet:

https://github.com/microsoft/ptvsd/blob/f3b0bb0cdc99531c6d44881cd81f2b554b68cdb1/src/ptvsd/__main__.py#L341-L348

This is the bare minimum you need to get something going like that. However, this code depends on `setup_connection`, which is *not* public API. You can import it nevertheless and use it - just be aware that it can break later, and likely will (as we're doing a major refactoring). 

If you need a stable API, then `ptvsd.attach` and `ptvsd.enable_attach` are that. Just call either one in your host Python initialization before you start running more code.

**Comment by int19h** [comment]
I just realized that perhaps I misunderstood your question, and what you really want is for Visual Studio to use your binary instead of `python` to launch the process, when you do Start/F5?

**Comment by EugeneZelenko** [comment]
My idea is to launch ptvsd client from Python interpreter started inside my application (Boost::Python is used for that purpose), set breakpoint on Python function name which will be called after client launch and then connect Visual Studio Code debugger to that client.

I'd like to replicate something like macros debugger (Python/Ruby) in https://klayout.de, but with already available tools.

Application is not straightforward Python replacement. It launch Python interpreter on later stages.

I tried to executed code modelled from ptvsd_launcher.py built-in Python interpreter, but it hangs and log was not produced even when I passed --log-dir <dir>. Another problem that ptvsd seems to be able to launch file and module but not function from already imported module.

**Comment by int19h** [comment]
Rather than using `--log-dir`, try setting `PTVSD_LOG_DIR` environment variable. I don't think ptvsd_launcher even supports `--log-dir`, that's only in the main CLI.

**Comment by int19h** [comment]
We try to stick to what Python does with respect to our ptvsd CLI (all other switches are to configure ptvsd itself). So, basically, if it's described here, it is in scope for that - and conversely, this is also why we don't do class and function launch:

https://docs.python.org/3/using/cmdline.html

(We do not fully support some scenarios there yet, either - e.g. we don't support interactive mode. But mostly it's stuff that nobody has asked for so far. If there's a scenario for which you specifically need anything that is missing, please file a separate issue for it, so that it can be prioritized accordingly.)

For what you're trying to do, I think `enable_attach` is your best bet, and you should then handle the launching of embedded Python code yourself, however you see fit, probably via `runpy` etc. The code that is in our `__main__.py` for `run_file`, `run_module` etc can provide a starting point for that part - and you're welcome to reuse it, since the license is MIT. But I don't think it's going to be helpful to you as a library.

The tricky part in your scenario is having VSCode connect to the debugger. On your side, if you do `enable_attach`, you then have to do F5 with an "attach" debug configuration in Code. This [can be automated](https://code.visualstudio.com/api/references/vscode-api#debug) from *inside* Code via your own extension - look at `startDebugging` specificaly. But I don't know if there's any API they have to drive it programmatically from the outside. If not, then you'll need a Code extension that exposes some kind of IPC endpoint for your app specifically.

**Comment by EugeneZelenko** [comment]
Thank you for explanations! Solution will be not as  as trivial as I expected.

**Comment by int19h** [comment]
You're welcome!

Oh, and you'll need to use `ptvsd.wait_for_attach` to make sure that your Python code doesn't start running until the debugger attaches. By itself, `enable_attach` sets up the debug server, but doesn't block waiting for connection.
