### ISSUE TITLE
How can I step into methods defined in remote python file when execute remote debugging?

### ISSUE THREAD

**Issue by ldreamke** [microsoft/ptvsd#1563]
When I do remote debugging with ptvsd module, I can't find a way to step into methods defined in remote python file.  Is there a way to do it? 
Thanks!

**Comment by int19h** [comment]
Is your remote file under `site-packages`, by chance?

Try experimenting with this setting, and see if it fixes it for you:
https://code.visualstudio.com/docs/python/debugging#_justmycode

If it does, can you tell more about your scenario (i.e. where the code actually is, and why), so that we can improve this feature such that it "just works" without having to manually configure it?

**Comment by ldreamke** [comment]
> Is your remote file under `site-packages`, by chance?
> 
> Try experimenting with this setting, and see if it fixes it for you:
> https://code.visualstudio.com/docs/python/debugging#_justmycode
> 
> If it does, can you tell more about your scenario (i.e. where the code actually is, and why), so that we can improve this feature such that it "just works" without having to manually configure it?

Thank you very much!! The variable justmycode in file launch.json should be set to 'false'. Now it works.
