### ISSUE TITLE
logToFile should still be supported with the new debug adapter

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1642]

**Comment by int19h** [comment]
It would not be able to log it into the same directory, though.

However, I think it can log to TEMP, but also print the exact name of the file out to the debug console. That way the user can just Shift+click it there to open it.

Also, we can have an option to log directly to the debug console. So perhaps we should make it a different property, to accommodate future variations? (i.e. not just a bool flag)

**Comment by karthiknadig** [comment]
The extension can set PTVSD_LOG_DIR when it sees the flag in the resolver. If it is not already set.
/cc @DonJayamanne

**Comment by int19h** [comment]
If we want to get the adapter logs, then doing this via `DebugConfigurationProvider` is too late, because the adapter is already running by then.

There is a way to hook this. We need to register a `DebugAdapterDescriptorFactory` for our debugger - that thing is queried for the command line to launch the adapter. We will have to do it in any case, since adapter needs Python to run, and this is the only way to locate it dynamically without hardcoding the path to Python binary into package.json. But while we're at it, the factory could also an environment variable to enable the adapter log. Or better yet, a command line switch, to avoid polluting the environment. 

However, with this approach, it can no longer be driven by a setting in launch.json. It would instead have to be a global extension setting - `python.ptvsdLog` or something like that.

**Comment by karthiknadig** [comment]
https://github.com/microsoft/vscode-python/issues/6017#issuecomment-517100717
