### ISSUE TITLE
Adapter should support --log-dir switch

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1649]

**Comment by DonJayamanne** [comment]
Why not just accept the environment variable, that would be easier (for VSC). Else we need to encode paths for cli, etc...
I'm assuming this is easier for PTVSD too.

**Comment by karthiknadig** [comment]
Both the --log-dir switch and the environment variable will be supported. @int19h recommended the switch, since it does not add anything to the user's environment variables.

**Comment by int19h** [comment]
We don't need to encode the paths for CLI, since the API that VSCode provides has you specify the command line as an array, and it takes care of all the encoding.

And we already have to provide that array, since that's where the paths to Python and ptvsd package go to launch the adapter itself. Might as well just add another path there.

**Comment by karthiknadig** [comment]
Fixed via https://github.com/microsoft/ptvsd/issues/1448
