### ISSUE TITLE
Waiting for thread pydevd.CheckAliveThread.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1691]
## Environment data

- PTVSD version: 4.3.2
- OS and version: Ubuntu
- Python version (& distribution if applicable, e.g. Anaconda): 3.*
- Using VS Code or Visual Studio: VSCode
- Library: cherrypy

## Actual behavior
```
[13/Aug/2019:18:30:27] ENGINE Listening for SIGHUP.
[13/Aug/2019:18:30:27] ENGINE Listening for SIGTERM.
[13/Aug/2019:18:30:27] ENGINE Listening for SIGUSR1.
[13/Aug/2019:18:30:27] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[13/Aug/2019:18:30:27] ENGINE Started monitor thread 'Autoreloader'.
[13/Aug/2019:18:30:27] ENGINE Serving on http://127.0.0.1:8080
[13/Aug/2019:18:30:27] ENGINE Bus STARTED
127.0.0.1 - - [13/Aug/2019:18:30:43] "GET / HTTP/1.1" 200 12 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
127.0.0.1 - - [13/Aug/2019:18:30:43] "GET /favicon.ico HTTP/1.1" 200 1406 "http://127.0.0.1:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
[13/Aug/2019:18:30:52] ENGINE Restarting because /mnt/c/GIT/pyscratch2/cherrypysample.py changed.
[13/Aug/2019:18:30:52] ENGINE Stopped thread 'Autoreloader'.
[13/Aug/2019:18:30:52] ENGINE Bus STOPPING
[13/Aug/2019:18:30:53] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8080)) shut down
[13/Aug/2019:18:30:53] ENGINE Bus STOPPED
[13/Aug/2019:18:30:53] ENGINE Bus EXITING
[13/Aug/2019:18:30:53] ENGINE Bus EXITED
[13/Aug/2019:18:30:53] ENGINE Waiting for child threads to terminate...
[13/Aug/2019:18:30:53] ENGINE Waiting for thread pydevd.CheckAliveThread.
```

## Expected  behavior

Should not block on debugger.

## Steps to reproduce:
1. Use this file:
```py
import cherrypy

class HelloWorld(object):
    @cherrypy.expose
    def index(self):
        return "Hello World!"

cherrypy.quickstart(HelloWorld())
```
2. Start debugging.
3. Make changes to line with "Hello World" and save.

**Comment by fabioz** [comment]
This happens because in pydevd a non-daemon thread is created and that thread waits for all other threads to exit before exiting itself -- it does this to make sure that all the related pydevd threads exit cleanly and send the needed events to the IDE.

Now, it seems that CherryPy does something similar before reloading: it waits for all other threads to exit before doing the reload at: https://github.com/cherrypy/cherrypy/blob/5d2b02532a27c4a6ae7622b1be2380c9e143461e/cherrypy/process/wspbus.py#L353

So, as there are 2 places waiting for the reload, nothing happens... 

I'm still thinking about the best solution here.

A workaround inside CherryPy would be doing something as:

```
if hasattr(t, 'do_kill_pydev_thread'):
    t.do_kill_pydev_thread()
```

right before the t.join() in https://github.com/cherrypy/cherrypy/blob/5d2b02532a27c4a6ae7622b1be2380c9e143461e/cherrypy/process/wspbus.py#L366

**Comment by ygbr** [comment]
Hi @karthiknadig just as a side note on this, even if you stop the debugging or kill the debug process running the cherrypy server using standard OS signals (CTRL+C), it seems that it is leaving zombie Python processes running due to this issue.

**Comment by ygbr** [comment]
@fabioz do you want me to open an issue on CherryPy GH as well so we can track this together?

Maybe @jaraco or @webknjaz could help bring some light to this ;)

**Comment by webknjaz** [comment]
I can't reproduce this.

**Comment by fabioz** [comment]
I already have a fix for the waiting part (I'm finishing the test case) -- what I did is change the pydevd thread to stop itself if someone tries to join() it (which is what CherryPy is doing).

Now, this doesn't fix all the problems... there are some more things to consider:

1. `os.execv` creates a new process and replaces the existing process with a new process, so, this means that you need to turn on the option to automatically attach to new subprocesses... also, I'm not sure how VSCode deals with things when this happens, since the parent process will die and a new process will replace it (@karthiknadig @int19h we should check how this scenario works as we will not want to kill this process when the process that launched it goes away).

2. when `os.execv` is called, if the parameters are quoted (with `"`), the monkeypatching to attach the new process may not work properly in `ptvsd` (i.e.: there's a double quoting in https://github.com/microsoft/ptvsd/blob/master/src/ptvsd/multiproc.py#L325 if it's already quoted) -- @karthiknadig @int19h, do you think we should fix that in master or only work in the `dbg_adapter_refactor` branch, since that code will probably be deprecated?
