### ISSUE TITLE
Ignored breakpoint

### ISSUE THREAD

**Issue by gramster** [microsoft/ptvsd#1764]
https://github.com/microsoft/vscode-python/issues/5296#issuecomment-525500454

From user @danielboth:

I got a similar issue where a breakpoint is ignored by vscode. Some details on my setup first:

VS Code version: 1.37.1
Extension version: 2019.8.30787
OS and version: Windows 10 1903
Python version: 4.7.4
Type for virtual environment used: venv
Relevant/affected Python packages and their versions: N/A
launch.json: Default settings
Next, some steps to get vscode to ignore the breakpoint, from scratch:

choco install python. Now python is installed in default folder C:\Python37
setup new folder, create test.py, set breakpoint, run test.py, debugger kicks in as expected
Run python.exe -m venv C:\Repositories\PythonBreakpointTest, set breakpoint, run test.py debugger still works ok.
Now in the workspace, switch python.pythonPath to C:\Repositories\PythonBreakpointTest\Scripts\python.exe, run debugger, now it skips over the breakpoint ignoring it. Switching it back to the default python.exe makes all happy again.

**Comment by int19h** [comment]
@danielboth, can you please clarify - are you placing test.py _inside_ the venv folder?

**Comment by karthiknadig** [comment]
Closing this for now. Please reopen when more information is available.

**Comment by danielboth** [comment]
Sorry, delayed response due to holidays. To answer @int19h, yes I'm placing test.py (actual name in the log is subnet.py, sorry) inside the venv folder.

I also ran the test with logging enabled and included the logfile. I did not get any pydevd_debug_file though.
[ptvsd-7928.log](https://github.com/microsoft/ptvsd/files/3672874/ptvsd-7928.log)

Looking through this file, this seems interesting:

D00000.063: (requested while handling {'command': 'setBreakpoints', 'type': 'request', 'seq': 4})
            PYD --> {
                "type": "response",
                "request_seq": 1000000002,
                "success": true,
                "command": "setBreakpoints",
                "body": {
                    "breakpoints": [
                        {
                            "verified": false,
                            "message": "Breakpoint in file excluded by filters.\nNote: may be excluded because of \"justMyCode\" option (default == true).",
                            "source": {
                                "name": "test.py",
                                "path": "c:\\Repositories\\PythonBreakpointTest\\test.py"
                            },
                            "line": 22
                        }
                    ]
                },
                "seq": 8,
                "pydevd_cmd_id": 502
            }

**Comment by int19h** [comment]
@danielboth 
venv folders are not meant to be used to place code in - they are transient artifacts. They have to be activated to give access to the modules installed within, but the code using those libraries should remain outside. You're likely to run into many other issues with the arrangement that you have at the moment, because Python tooling in general is not designed to accommodate such use.

That said, the problem you're having with the debugger specifically is that it's treating the contents of the venv as part of the standard library / installed packages. And there is a [debugger option called "justMyCode"](https://code.visualstudio.com/docs/python/debugging#_justmycode) that prevents debugging of those parts - so that you can focus just on your code - which is enabled by default. You can explicitly set that to false in your launch.json, and then you should be able to hit breakpoints.

**Comment by danielboth** [comment]
Thanks @int19h, that makes it clear I was just using the venv folders in the wrong way. Thanks for explaining!

Moved the file outside the venv folder and then all works as expected, so no need to reopen this.
