### ISSUE TITLE
Need a way to launch python executable without subprocess patching

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1771]
~In `enable_attach` we plan on starting the adapter as a subprocess. To avoid pydevd from using patched apis to create the sub-process we want to patch for multiproc after spawning the adapter process. Looking at the code in pydevd it seems like it save the `patch_multiprocessing` setting value and reuses that later.~

**Comment by int19h** [comment]
Alternatively, we need a way to make subprocess detouring not apply to `ptvsd.adapter`. This is a more generic approach, since it can accommodate other debugger helper processes in the future, regardless of when they're spawned.

It seems like the easiest way to do so would be to apply the existing pydevd `dont_trace` patterns to subprocesses. Since we already add the entire ptvsd/ there, it would already cover the adapter, and any future helpers.

**Comment by fabioz** [comment]
How about creating an api for that?

Something as:

```
with pydevd.skip_subprocess_arg_patch():
    subprocess.call(...)
```

The implementation would be pretty straightforward (it would create a thread local variable to apply that option only to the current thread and would skip the arg patching in that context).

The downside I see on the `dont_trace` approach is that it's possible that you do want to execute some subprocess with tracing (say on some jupyter debugging extension or running tests) and it'd need to interpret the actual arguments passed to python to discover the filename (so, it's a bit more complex to implement).

**Comment by int19h** [comment]
This sounds nice, especially since it could also be used by non-debugging infrastructure that embeds the debugger (e.g. on Azure) for their own helper processes. And we could even expose it to end users, if there's demand for it.

**Comment by fabioz** [comment]
Ok, I'll go forward with that approach then.

**Comment by karthiknadig** [comment]
Fixed via https://github.com/microsoft/ptvsd/pull/1779
