### ISSUE TITLE
Runtime errors are not caught when debugging with PyQt5

### ISSUE THREAD

**Issue by LBdN** [microsoft/ptvsd#1816]
## Environment data

- VS Code version: 1.38.1
- Extension version (available under the Extensions sidebar): 2019.09.34911
- OS and version: Win 10
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.4
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Relevant/affected Python packages and their versions: PyQt5
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language Server. 

## Expected behaviour

Breakpoint on uncaught exceptions. 

## Actual behaviour

application crash. 

## Steps to reproduce:

My app use one QTimer that move forward a (complex) iterator. If any exception is raised in it, the whole app crashes. 

simple example : 

```
Traceback (most recent call last):
  File "C:\Users\lionel\Code\parametric\reactive2\rectitude\engine\timer.py", line 59, in __next__
    result = next(self.tasks, FINISHED)
  File "C:\Users\lionel\Code\parametric\reactive2\rectitude\engine\engine_listener.py", line 146, in __next__
    res = next(self.it, end_marker)
  File "C:\Users\lionel\Code\parametric\reactive2\rectitude\profiling.py", line 43, in __next__
    retval = self.prof.runcall(next, self.iter)
  File "C:\Users\lionel\AppData\Local\Programs\Python\Python37\lib\cProfile.py", line 121, in runcall
    return func(*args, **kw)
  File "C:\Users\lionel\Code\parametric\reactive2\rectitude\engine\engine_listener.py", line 172, in build_iterator
    yield from node.get_iter_async()
  File "C:\Users\lionel\Code\parametric\reactive2\reactive2\engine\core.py", line 136, in get_iter_async
    result = self.apply(iters)
  File "C:\Users\lionel\Code\parametric\reactive2\reactive2\engine\core.py", line 150, in apply
    result = self.func(*inputs)
  File "C:\Users\lionel\Code\parametric\reactive2\reactive2\twodee\reducers.py", line 109, in reverse
    1/0
ZeroDivisionError: division by zero
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
##########Linting Output - pylint##########
> ~\Code\parametric\venv-py3\Scripts\python.exe -m pylint --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Users\lionel\Code\parametric\reactive2\reactive2\validators\base.py
cwd: c:\Users\lionel\Code\parametric\reactive2
> ~\Code\parametric\venv-py3\Scripts\python.exe -m pylint --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Users\lionel\Code\parametric\reactive2\reactive2\validators\base.py
cwd: c:\Users\lionel\Code\parametric\reactive2
##########Linting Output - pylint##########

```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
[Extension Host] Info Python Extension: 2019-09-30 10:23:05: Cached data exists getEnvironmentVariables, c:\Users\lionel\Code\parametric\reactive2
c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\xterm\lib\xterm.js:1 [Violation] 'setTimeout' handler took 51ms
5[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
console.ts:137 [Extension Host] Info Python Extension: 2019-09-30 10:24:08: Cached data exists getEnvironmentVariables, extension-output-#5
console.ts:137 [Extension Host] Info Python Extension: 2019-09-30 10:24:40: Cached data exists getEnvironmentVariables, extension-output-#2
```

**Comment by LBdN** [comment]
Yep.
The _Raised Exceptions_ setting works but is not useful as many exceptions are raised and caught. 
The _Uncaught Exceptions_ setting seems to do nothing. 
Not sure I can supply a repro easily, I will evaluate that.

**Comment by karthiknadig** [comment]
@LBdN You mentioned breakpoint working. So, in the part of your code where you expect the exception to occur, does the breakpoint work there?

What I am trying to figure out is whether the exception is coming from a thread that was started native APIs. If it does originate from a native source, then you might need `ptvsd.debug_this_thread()` to enabled tracing in that thread.

**Comment by LBdN** [comment]
Yes; it does.
I don't know whether the python part in PyQT5 in another thread.  Might be. I'll try that tomorrow.

**Comment by LBdN** [comment]
mmm.. I tried what you proposed and it doesn't work. this is the test I have.

`def reverse(rects):
    _reversed = list(rects)[:]
    #==
    import ptvsd
    ptvsd.debug_this_thread()
    import rectitude.debug as dd
    dd.print_time_and_thread()
    1/0
    #==
    _reversed.reverse()
    return  {'rects' : _reversed }`

I also checked the threads and it seems everything is run from the same one.  

Also, I checked and the uncaught exception works before the pyqt loops starts. Maybe either the generator or the qtimer swallows the exception.

**Comment by fabioz** [comment]
I was able to reproduce this issue (see the code pasted below for a code-sample which reproduces the issue).

Now, some details on what's happening: PyQt5 itself kills the program when an exception from a `QTimer` signal/slot gets up to the main QApplication loop, not the debugger -- i.e.: the code pasted below stops on 5 calls with or without the debugger.

So, if you have an unhandled exception that gets to the main application loop from a QTimer, you should handle it yourself... usually I use a decorator for this -- you can see: https://github.com/fabioz/pyvmmonitor-qt/blob/master/pyvmmonitor_qt/qt_utils.py#L370 as a reference for such a decorator (or you could do something as: https://stackoverflow.com/a/38020962/110451).

In this case, you should put a breakpoint inside that decorator or that except hook to see what would be an unhandled exception.

Now, regarding showing it as if it was untraced, this is quite tricky... the problem here is that it doesn't appear to the debugger as if this frame is a top-level (the stack appears as `<module>`, `main()`, `OnTimeout.__call__()`), so, even though it behaves as an async call where the `OnTimeout.__call__()` would be a a top-level frame, this is not how it appears for Python, which expects the exception to be propagated to the top-level frame before being reported as an uncaught exception.

So, everything is working as it should aside from the fact that PyQt5 itself kills the program instead of propagating the exception. Given that this is how PyQt5 itself works, I don't think there's much to be done from the debugger (given this, I'm closing the issue -- feel free to comment more if you feel there's something I'm missing here).

Example reproducing the issue:

```
class OnTimeout(object):

    def __init__(self, app):
        self._app = app
        self._called = 0

    def __call__(self):
        self._called += 1
        print(self._called)
        if self._called == 5:
            raise AssertionError('some error')
        if self._called == 10:
            self._app.exit()


def main(app):
    timer = QtCore.QTimer()
    timer.setInterval(200)
    on_timeout = OnTimeout(app)

    timer.timeout.connect(on_timeout)
    timer.start()
    app.exec_()


if __name__ == '__main__':
    from PyQt5 import QtCore
    from PyQt5.QtWidgets import QApplication
    app = QApplication([])
    main(app)

```
