### ISSUE TITLE
ImportError: can't find '__main__' module

### ISSUE THREAD

**Issue by m0tz** [microsoft/ptvsd#1823]
python 2.7.
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-29-generic

```
Traceback (most recent call last):
  File "/home/user/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/user/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/user/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python2.7/runpy.py", line 268, in run_path
    mod_name, loader, code, fname = _get_main_module_details()
  File "/usr/lib/python2.7/runpy.py", line 137, in _get_main_module_details
    (main_name, sys.path[0]))
ImportError: can't find '__main__' module in '/home/user/myproject/'
```

**Comment by int19h** [comment]
Could you please share your launch.json as well?

**Comment by m0tz** [comment]
sure. launch.json

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}/",
            "args": [
                "python", "manage.py", "runserver_plus",
            ],
            "django": true
        }
    ]
}

**Comment by karthiknadig** [comment]
@m0tz Try this config:
```js
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "args": [
                "runserver",
                "--noreload"
            ],
            "django": true
        }
    ]
}
```

**Comment by m0tz** [comment]
@karthiknadig thanks, that works. 

why my launch.json does not work?

**Comment by karthiknadig** [comment]
@m0tz There were two issues:
1. ` "program":` should point to a python file. The Python extension picks up the executable based on the version of python selected via the interpreter selection UI. In your setting it was pointing to a directory (your workspace folder).
2. `"args": ` are a list of arguments that you pass to your python script or module. In your case the args were `[ "python", "manage.py", "runserver_plus"]`. This is equivalent to:
`/usr/bin/python python manage.py runserver_plus`. See `python` is there twice, this causes the debugger to try to load `python.__main__`.

How did you find the debug config that you used?

**Comment by int19h** [comment]
"program" can also point at a directory. But if it does, then that directory must contain a file named `__main__.py`, and then Python will execute that file. This is what was happening in this case, except there was no such file. 

In general, when you use "program", this is equivalent to saying `python <program> <args>`. So in this case, what was executing is:
```
python /home/user/myproject/ python manage.py runserver_plus
```
So that second `python` became a command line arugment to `/home/user/myproject/__main__py`. If it were present, you'd see it in `sys.argv`.

In a similar vein, if you use "module" instead of "program", then it's as if you ran `python -m <module> <args>`.

You can look up the details of Python behavior in either case here. The debugger should always behave the same in all respects - if it doesn't, it's a bug.
https://docs.python.org/3/using/cmdline.html

**Comment by karthiknadig** [comment]
@int19h is correct, I missed that `program` can be a dir.
