### ISSUE TITLE
Add option to pydevd so that disconnect doesn't run user code.

### ISSUE THREAD

**Issue by fabioz** [microsoft/ptvsd#1837]
Right now on a disconnect `pydevd` will always remove all breakpoints and start running user code, but this is not desirable on some situations (i.e.: if the user did a launch and then disconnects there's an implicit assumption that it's terminating the program -- the same would be true for subprocesses which are later attached to if the initial program was started through a launch).

**Comment by fabioz** [comment]
Maybe this could be handled through an additional setting in `setDebuggerProperty` (something as `onDisconnectResumeBreakpoints`).

@int19h what do you think?

**Comment by int19h** [comment]
This is currently handled by the adapter - if it receives "disconnect" from the IDE, and it was launch, it sends "terminate" to pydevd.

In multiproc scenarios, the IDE will send "disconnect" to the root, even if a child process is selected (so long as we properly tell it which process is a child of which). Thus, the adapter will need to extend this logic to multiple sessions.

OTOH, if the user disconnects from a single specific subprocess in a multiproc session that was started by launching, it shouldn't be terminated.

So I think that existing pydevd behavior is fine as is, since it gives the adapter the necessary degree of control to implement everything. However, for pydevd to be DAP-conformant by itself, it needs to implement terminate-on-disconnect if launch was used for that particular process (subprocesses are out of scope for DAP spec).

**Comment by fabioz** [comment]
I created this because the sequence diagrams said that it requested a disconnect to the debugge (in https://github.com/microsoft/ptvsd/pull/1828/files#diff-ecd749edec2bf96b3cfacdff3c90a770R95), if that's not the case I'll close this (the sequence diagram should probably be updated to say that it requests a terminate there instead of a disconnect).
