### ISSUE TITLE
Add telemetry event when debugger binaries are used

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1859]
Whenever we use cython binaries, we should generate a telemetry event.

**Comment by fabioz** [comment]
I can take a look into this...

My idea is having `pydevd` generate an output event when handling the `initialize` request with:
```
{
    "category": "telemetry",
    "output": "pydevd",
    "data": {"cython": true|false, "frame_eval": true|false},
}
```
on the `ptvsd` side, it should change the `output` to `ptvsd.adapter` and add the `packageVersion` when forwarding it to the ide.

@karthiknadig @int19h 
Does that seem ok?

**Comment by karthiknadig** [comment]
@fabioz, @int19h I am wondering if `pydevd` should generate this telemetry event at all. Could we use `pydevdSystemInfo` request to get this data?

**Comment by int19h** [comment]
If I remember correctly, neither .pyd is loaded lazily, so both should be present in `sys.modules` as soon as pydevd itself is imported. In which case the adapter can do a frameless "evaluate" request to find them there.

**Comment by fabioz** [comment]
For doing a frameless `evaluate`, we need to address https://github.com/microsoft/ptvsd/issues/1733 before... adding the info to `pydevdSystemInfo` should be straightforward, so, I created https://github.com/microsoft/ptvsd/issues/1880 to do that on the pydev side -- this issue can be used to add the telemetry on the ptvsd side then.

**Comment by int19h** [comment]
#1733 is only required to query the children of the resulting value, isn't it? The immediate response to "evaluate" should contain "result", and if it's a plain value (e.g. True/False), that would be parseable as is. For something like `"_pydevd_bundle.pydevd_cython" in __import__("sys").modules`, that would be enough.

**Comment by fabioz** [comment]
Sort of... it currently only evaluates as an `exec` and not as an `eval` (because return values aren't currently supported), so, the return is always `''`.

We could probably do a partial support and try to do an `eval` first to return the `str` result but without a `variablesReference` (that'd be simpler/faster to do than the full support for a `variablesReference` as specified in https://github.com/microsoft/ptvsd/issues/1733 and may be enough for all the cases we'd use it, but it still needs some work).

But still, `"_pydevd_bundle.pydevd_cython" in __import__("sys").modules` may not be enough on some circumstances (it's possible to pre-build binaries which can be loaded in the format: `_pydevd_frame_eval.pydevd_frame_evaluator_win32_27_32`).

So, I'm a bit wary of having `ptvsd` rely internal on structures from `pydevd` (i.e.: I think the variables needed should be officially exported by `pydevd` for `ptvsd` to use it without having to worry about internal details of `pydevd`, regardless of https://github.com/microsoft/ptvsd/issues/1733, to avoid future breakage).

**Comment by karthiknadig** [comment]
Closing this. Since we can get this info via `ptvsd_sysinfo`.
