### ISSUE TITLE
Pydevd API to send custom events over DAP

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1860]

**Comment by fabioz** [comment]
What's the custom event to be sent? (i.e.: the dap protocol in pydevd is very specific to the ptvsd needs, so, I'm not sure it's worth it to send something from ptvsd instead of just sending it from pydevd)

**Comment by int19h** [comment]
It's #1859 for now, but there will be more - e.g. we wanted to send server logs to the adapter over DAP, and that will also need something.

In general, there's a class of issues where it's the code inside ptvsd rather than the code inside pydevd that needs to notify the adapter and/or IDE. So if pydevd is the one sending events, it'd need to expose a corresponding specialized API hook for every one of those for ptvsd to call when it needs to. It seems like it'd be better to just have a single hook for "here's event body as JSON".

Another reason why that would be preferable is that at some point we might start having other packages building on ptvsd also sending custom events that are specific to their scenarios. Some contexts where this was previously discussed are Jupyter and IoT.

**Comment by karthiknadig** [comment]
Also warnings (justMyCode==false) to be sent via some custom event ( see #1861).

There is another category, basically send a request to IDE and debugger waits for response (reverse-request). That could be used to dynamically change the setting like JMC. The only limitation right now is that VSCode does not support custom reverse-requests.

**Comment by fabioz** [comment]
I think that #1861 could actually be always sent by pydevd -- the telemetry info (#1859) regarding binaries could probably be sent by pydevd too (without any special api), but it does make sense to send the server logs created from ptvsd from ptvsd itself...

As a note, I'm currently working on this issue.

**Comment by karthiknadig** [comment]
Python extension plans on using DebugAdapterTracker API for logging ( https://github.com/microsoft/vscode-python/issues/8106 ). Having server logs sent as events is useful to capture all the logs in a single location. This is also helpful in remote scenarios to get detailed pydevd logs.
