### ISSUE TITLE
Don't step into loop when pressing F11 with hit count breakpoint

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/ptvsd#1898]
## Environment data

- VS Code version: 1.40.0-insider
- Extension version (available under the Extensions sidebar): 2019.11.47235-dev

## Expected behaviour

It should step into loop when pressing F11 with hit count breakpoint

## Actual behaviour

Cannot step into loop when pressing F11 with hit count breakpoint, It always stop on "for" statement
![image](https://user-images.githubusercontent.com/41426540/68365455-a0da2200-016b-11ea-9ae6-8513edb93836.png)

## Steps to reproduce:
1. Input below code:
```
    for i in range(1,500,20):
          print(i)
```
2. Set "Hit Count" condition breakpoint such as "10" on "print" statement
3. Press F5
4. Press F11

Repro gif:
![stepintoloop](https://user-images.githubusercontent.com/41426540/68365629-32499400-016c-11ea-97d7-dd7fc0fb37cb.gif)

**Comment by int19h** [comment]
I think it's because there is no way for the tracing code to distinguish whether this line was hit because it was the target of a step, or because of the breakpoint. So it assumes breakpoint, and then when the condition isn't true, auto-resumes.

I'm not sure what we can do here, though. In particular, we can't just fall back to treating it as end of step if condition isn't True - the problem is that there are cases where the two really are different. E.g. suppose it was some custom generator function instead of `range()`, there was a hitcount breakpoint inside of it, and it was F10 (Step Over). In that case, the breakpoint inside the generator would be hit, and the condition evaluate to False. If we then ignore that, and assume that it was the end of the step, then we'd break in the wrong place. 

The fundamental problem here is that we don't try to compute the destination for a step - which would be very complicated, likely requiring runtime bytecode inspection, and even then I'm not sure how that would work with third party native code modules. We instead rely on Python reporting a line number / stack frame change to us, and treat that as the end of the step. This makes it impossible to distinguish from a breakpoint on the same line. And normally that's not an issue, because with regular breakpoints, it doesn't really matter why we stopped on that line, so long as we stopped. But for conditional and hitcount breakpoint, the reason why we ended up on that line does matter.

@fabioz, do you have any ideas?

**Comment by fabioz** [comment]
I'll take a look at it.
