### ISSUE TITLE
[debugAdapter] Protocol violation handling 'attach' request (incorrect request_seq)

### ISSUE THREAD

**Issue by gins3000** [microsoft/ptvsd#1904]
## Environment data
- Extension version (available under the Extensions sidebar): 2019.10.44104

## Expected behaviour
A response is sent with the `request_seq` matching its request's `seq`.
See: https://microsoft.github.io/debug-adapter-protocol/specification#Base_Protocol_Response
```ts
/**
 * Sequence number of the corresponding request.
 */
request_seq: number;
```

## Actual behaviour
When `attach` fails once, and is re-sent, the `request_seq` will be that of the first (failed) request, making it impossible to match the successful response to the correct request.

## Steps to reproduce:
1. Send an attach request that will cause an error (e.g. a wrong port)
2. Send another attach request that is expected to succeed
3. Observe the next response's `request_seq` not matching the second request's `seq`

## Logs

This is an annotated log from the standalone debug adapter protocol client I'm writing:
```
// Sending an "attach" request...
[DebugAdapterClient] sending request 'attach' (2) {
  "port": 5678
}
// An error response comes back correctly, because the specified port is not yet ready
[DebugAdapterClient] received error response for 'attach' (2) {
  "seq": 2,
  "type": "response",
  "request_seq": 2,
  "command": "attach",
  "success": false,
  "message": "Failed to attach (connect ECONNREFUSED 127.0.0.1:5678)",
  "body": {
    "error": {
      "format": "Failed to attach (connect ECONNREFUSED 127.0.0.1:5678)",
      "id": 1
    }
  }
}
// Sending the request again
[DebugAdapterClient] sending request 'attach' (3) {
  "port": 5678
}
// A response is received, but it comes with the request_seq of the first request (2) instead of the request that this is actually responding to (3)
[DebugAdapterClient] Received response attach with bad sequence number 2 {
  "type": "response",
  "seq": 1,
  "request_seq": 2, <<< this should be 3
  "success": true,
  "command": "attach",
  "message": "",
  "body": {}
}
```
This might have something to do with the `attach`, `launch` and `initialize` requests being deferred (and thus storing the first request's ID?), so this bug may affect all three of these requests.

**Comment by int19h** [comment]
Can you clarify which version of ptvsd you're using (`ptvsd.__version__` will do the trick). Also, given that this is a custom DAP client scenario, how are you communicating with the adapter - is it a direct socket connection to ptvsd, or are you going via the .ts adapter that ships with the VSCode extension?

**Comment by gins3000** [comment]
@int19h I have originally posted this issue in https://github.com/microsoft/vscode-python, and communicated with the adapter featured there, launching it myself with `node ./out/client/debugger/debugAdapter/main.js --server=<some port>`, with a custom client implementing the VSCode Debug Protocol.

I don't think ptvsd is relevant for this particular issue (it's about the debug adapter from the VSCode extension), so I'm not sure why the issue was moved. Could you clarify, @karthiknadig ? I'll gladly provide more information, if something was missing.

On the bright side, I have now learned that ptvsd is already implementing the DAP on its own (I had started from https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/, and found ptvsd later) so I connected to it directly instead, and that seems to work for me.

Would it make sense to add ptvsd to the [list of DAP implementations](https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/)?

As this issue is still about microsoft/vscode-python, I think it should be moved back there though.

**Comment by int19h** [comment]
This is a bit complicated, and we never really communicated the relationship between the adapter in vscode-python, and ptvsd itself, clearly.

The old arrangement - that currrently ships in vscode-python - is ptvsd 4.x + TS adapter. In that one, ptvsd does implement DAP, but only over a socket. Thus, the separate adapter was needed to implement DAP-over-stdio (by redirecting to socket), and to handle the part of the DAP initialization sequence that had to happen until the point where that adapter got enough information to launch ptvsd properly - which is to say, until it got the "launch" or "attach" request from the client. The two projects were effectively joined at the hip, which is why the DAP implementation list has vscode-python in it, rather than ptvsd.

The new arrangement, implemented in ptvsd 5.x, has ptvsd implement all the functionality that was previously handled by the TS adapter in the extension. It can still talk DAP over a socket, same as old one did - and we use it for "attach" (by telling VSCode to connect directly to a socket) - but it can also talk over stdio. And it handles the entire initialization sequence, including launching the debuggee process. So now it's a fully self-contained DAP implementation (and yeah, we need to update that list accordingly once we ship a stable version of 5.x).

vscode-python is going to move to ptvsd 5.x as well, and as part of that process, it will remove the TS adapter eventually. There isn't much point in having a bug over in that repo, either - it'll just get closed eventually once that code is gone. 

So for your scenario, ptvsd 5.x is certainly the way to go. On top of fixing this issue, it also avoids any dependencies on Node, and should simplify deployment as well - you can basically just do `pip install ptvsd` now to get everything you need for your client, or even just include bdist into your project. 

However, I would also recommend implementing DAP-over-socket in your client. I'm not sure if we can commit to supporting DAP-over-stdio for "attach" requests long term - it works now, but it's not going to be well-tested on any of the popular clients, since they will all use direct socket connections instead of spawning the adapter. It's also used by some other adapters, as far as I know (e.g. Java). 
VSCode currently requires a little bit of code to do this - it's the [bit in vscode-python](https://github.com/microsoft/vscode-python/blob/6e260e7e4c9318380f5217767a5f1a0e291bd045/src/client/debugger/extension/adapter/factory.ts#L32-L46) that looks at the debug configuration in launch.json before the debug session even begins, parses "host" and "port", and directs VSCode to use a socket for that session. But a custom DAP client could implement the same functionality directly, handling it the same for all languages.

**Comment by gins3000** [comment]
Wow, thanks for this detailed and yet fast response :o 

When I saw that ptvsd implements the DAP I suspected that the DAP implementation from the extension might really be on the way out. In this case I will just close the issue. Thanks again!
