### ISSUE TITLE
Debuggee output is UTF-8 regardless of locale

### ISSUE THREAD

**Issue by zhucong1986** [microsoft/ptvsd#1938]
version: ms-python.python-2019.11.49689
Yesterday, vscode has autoupdate this extension.
after that. vscode terminal output chinese encoding error.

This file work well in cmd/powershell window.

![error.jpg](https://i.loli.net/2019/11/20/oCiPsS26xyAtTIM.jpg)

**Comment by int19h** [comment]
@zhucong1986 
If you run `chcp` in the Terminal, it should give you the active codepage number; most likely, 936. Try adding this to your launch.json:
```json5
"env": {
    "PYTHONIOENCODING": "cp936",
}
```
(adjusting accordingly if the actual codepage is different)
Does this correct the output?

**Comment by int19h** [comment]
@karthiknadig I believe this to be caused by the extension forcibly adding `PYTHONIOENCODING=utf-8` to the environment for the debuggee. This causes Python to produce UTF-8 output, but the VSCode terminal actually expects it to be encoded according to locale settings. The launcher captures the output bytes and forwards it to the terminal as is, but it gets rendered by the terminal according to locale.

The reason why this works if you run the Python script directly from the terminal, without debugger in the picture, is because `sys.stdout` utilizes Win32 console API directly in that mode, instead of writing to the file descriptor. Since that API allows for Unicode strings, there are no encoding issues. But when debugger is involved, the launcher redirects stdout of the script, which bypasses Win32 console APIs, and requires encoding consistency.

**Comment by int19h** [comment]
Side note: even if we remove the env var, this also means that enabling output redirection (which the extension does by default by adding `"RedirectOutput"` to debug options) has an observable adverse effect. The same Python script that would run just fine without output redirection, can fail with it, because its output is now forced to whatever encoding the system locale specifies.

So instead of removing the variable altogether, I think we should move the logic deciding whether to use it or not to the launcher. The launcher can then avoid setting it if output redirection is disabled, but set it to "utf-8" when it is enabled. Then, instead of just passing the raw bytes as is, the launcher would decode them from UTF-8, and write them out via `sys.stdout` (instead of `os.write()` directly to the file descriptor, as it does now), ensuring that Python 3.6+ the Unicode console code path works correctly. This will ensure feature parity in both cases.

**Comment by int19h** [comment]
See https://www.python.org/dev/peps/pep-0528/ for context.

**Comment by liyanan24** [comment]
Does it mean that every time I write code that contains Chinese, I need to add the code in launch.json?

**Comment by int19h** [comment]
@liyanan24 This is a bug, and we're going to fix it before releasing ptvsd 5.0 stable. For now, if you're running the ptvsd alpha, you'll need to use the workaround.

**Comment by zhucong1986** [comment]
```
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS C:\Users\ZC\Desktop> & 'C:\Users\ZC\AppData\Local\Programs\Python\Python37\python.exe' 'c:\Users\ZC\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '57059' 'c:\Users\ZC\Desktop\aa.py'
你好
PS C:\Users\ZC\Desktop> 
```
Call this luncher to run my .py file, the output is correct : 
```
%userprofile%\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\ptvsd_launcher.py
```

focus on my screenshot below, the luncher is:
```
%userprofile%\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\new_ptvsd\wheels\ptvsd
```

i have delete %appdata%\User\ folder and pip uninstall autopep8 pylint, 
then restart vscode and open a .py file, press f5. 
the luncher is ptvsd_launcher.py, but a few later.....
the luncher changes to ptvsd folder.

i tried to backup  %appdata%\User\globalStorage\state.vscdb when vscode runs well.
then wait for the luncher changes to ptvsd folder.
i replace state.vscdb .....
it woks... Luncher never changes to ptvsd folder.

**Comment by int19h** [comment]
The two launchers are for two different versions of ptvsd - 4.x the old stable one, and 5.x, the new one that is still in testing. The new one had the bug, and required the fix.

Next ptvsd 5.x release will have the fix.
