### ISSUE TITLE
"Exception has occurred" didn't pop up

### ISSUE THREAD

**Issue by kzhui125** [microsoft/ptvsd#1946]
```py
import pandas as pd

print('1')
df = pd.read_csv('file_not_exits')
print('2')
```

If I make a debug point at `print('2')`, and start debugging, I expect "Exception has occurred" pop up.

But this error show up:

<img width="448" alt="1" src="https://user-images.githubusercontent.com/11925432/69404245-c8b6b180-0d37-11ea-9b01-7e11a5f910eb.png">

**Comment by int19h** [comment]
Can you tell a little bit more about your environment? In particular, I wonder about the location of `pandas` on the file system - is it inside site-packages as usual, or is it some kind of custom layout?

**Comment by kzhui125** [comment]
Hello,

I install python using brew, and install pandas using pip.

<img width="882" alt="syspath" src="https://user-images.githubusercontent.com/11925432/69517826-cf8c3100-0f90-11ea-8eeb-4b86b4d9c4db.png">

Thanks,

**Comment by fabioz** [comment]
@kzhui125 some more questions:

- If you run it without debugging, do you have some error? 
- What if you run it directly from the shell (i.e.: `python <my_file.py>`)?
- Can you provide your launch configuration?
- Can you provide the log for the test run? (see: https://github.com/Microsoft/ptvsd/blob/master/README.md#debugger-logging for how to get it).

**Comment by kzhui125** [comment]
run it without debugging, python test.py
```
/usr/local/bin/python /Users/zm/Documents/repos/zrepos/python-tests/test.py
1
Traceback (most recent call last):
  File "/Users/zm/Documents/repos/zrepos/python-tests/test.py", line 4, in <module>
    df = pd.read_csv('file_not_exits')
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'file_not_exits' does not exist: b'file_not_exits'
```

no launch configuration, only debug python file

**Comment by fabioz** [comment]
For the log you can make a launch and then set the `PTVSD_LOG_DIR` environment variable.

i.e.: add to the launch configuration:

```
"env": {
    "PTVSD_LOG_DIR": "/usr/local/logs",
}
```

**Comment by kzhui125** [comment]
[ptvsd-23188.log](https://github.com/microsoft/ptvsd/files/3886627/ptvsd-23188.log)

@fabioz here is the log

**Comment by fabioz** [comment]
@kzhui125 can you check if `/usr/local/lib/python3.7/site-packages/pandas/_libs/parsers.pyx` exists in your machine?

The problem is that there are some cython-generated files for pandas and the related modules have relative paths as their `__file__` attributes (i.e.: `pandas/_libs/parsers.pyx`) and when we get the absolute path this becomes a path based on the current working directory.

I think we could detect that this is a relative path and then try to guess the proper file location based on the `sys.path` entries, but this only makes sense if that file is actually distributed along with pandas...

Note that there may be something to be done in the client too as there are cases where it's really impossible for the debugger to find the real file (for instance if the user generated code and used something as `invalid/file.py` to compile it) -- in this case it should still show the exception, even if the real source can't be found instead of just complaining that the source can't be found.

**Comment by kzhui125** [comment]
<img width="915" alt="11" src="https://user-images.githubusercontent.com/11925432/69543130-e4d08200-0fc7-11ea-8844-1139a6945891.png">

@fabioz there is no parsers.pyx

**Comment by fabioz** [comment]
In this case I don't think we can really do anything about it in `ptvsd` (except maybe just recognizing that it's a relative path and passing a relative path to the client, but I think it won't really make a difference in how it's handled in the client) -- it's up to VSCode itself to show the exception even if the file doesn't exist.

What do you think @int19h @karthiknadig?

**Comment by int19h** [comment]
That .pyx not being there is what I'd expect, since it's similar to .c files for other native modules - it's a source build artifact, there's no reason to redist it.

The real problem here is that the file is not considered library code. If it were, the exception would have been reported at the expected line. I don't think there's any general solution to this - the file has a relative `co_filename`, which logically places it into the workspace.

At the same time, if this is a pervasive issue for .pyx specifically (and I suspect it is - those paths have to be relative, nothing else makes sense at build time), we could try to solve it just for them. Basically, for relative .pyx paths, if the file doesn't exist, check if there's a matching `sys.modules` entry (as in, `foo/bar/baz.pyx` -> `foo.bar.baz`). If there is, assume that it's that file, and look at the module's `__file__` to determine whether it's stdlib or user code.

**Comment by int19h** [comment]
Also needs to do the same for .pxd files per #2002.

**Comment by fabioz** [comment]
I started to take a look at this. 

As a note, #2002 is actually a bit different (because in that case the `.pxd` file is actually available, whereas in this case it's not), so, to solve #2002 we should try to resolve the relative filename by looking into entries in `sys.path` (as it'd find the file we would just consider it a library file without any additional handling -- I'll do this as a part of this issue).

For this one, I checked just considering it a library, but it seems that in this case we won't even show the unhandled exception (right now an unhandled exception in a library will not be shown in the debugger when `justMyCode:true`, which means it'll just print the traceback -- we should try to find the first user code in the traceback in this case instead of ignoring it and then show the exception at that point... I'll take a look at this as a part of this issue too). 

Still, this doesn't fix the issue on the client side if `justMyCode:false` (it'll still show that dialog prompting the user to create the file, we're just making it a bit harder to happen -- if a relative path is given it'll actually create an empty editor with that path saying `Could not load source 'path/to/file': Source unavailable.` -- this happens for a filename as `<some_string>` too).

I think the solution for this use case is in the client: VSCode should not ask to create files for files which cannot be found in the debugger nor show that editor (i.e.: that's expected on some cases and I don't think the user ever wants to create a file if a non-existent file is given from the debugger) -- I'm not sure whether this should be done in VSCode or in the Python extension though... @karthiknadig @int19h do you know who shows that dialog/creates the editor when the file can't be found?

**Comment by fabioz** [comment]
The part related to ptvsd is now fixed.

The fix is that we now consider that file a part of the library, so, when `justMyCode:true` we won't show that file anymore in the stack. Still, if `justMyCode:true` it's possible that the file is shown, but then it's up to the client to show the proper UI in this case.
