### ISSUE TITLE
Debug process dies silently when running grpc server

### ISSUE THREAD

**Issue by saschahofmann** [microsoft/ptvsd#1957]
## Environment data

- PTVSD version: 2019.11.50794
- OS and version: macOs 10.15
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3
- Using VS Code or Visual Studio: VS Code

## Actual behavior

I am starting a gRPC server in the debugger which seems to work but after the first request the process dies without throwing an error. It then calls runs a `conda activate env` command.
When I start the debugger the command run in bash actually looks like this:
```
path-to/python
path-to-ptvsd/launcher
path-to/program.py
source path-to-conda/bin/activate
``` 
Which probably explains why it is running the conda activate after dying. 
If I simply run `python path-to/program.py` it works perfectly fine.
Running the debugger has worked before but I have troubles tracing it back to when it was introduced. Current hypothesis: it happened after the recent PTVSD update.

**Comment by karthiknadig** [comment]
@saschahofmann Can you tell us the `conda` version? you can run `conda --version` to get that. The issue seems to be that it is not activating conda environment before starting the debugger. see https://github.com/microsoft/vscode-python/issues/8422 . The extension will switch to using `conda run` which should address this issue. However, that only works with later versions of conda (>= 4.6.0).

**Comment by saschahofmann** [comment]
yes, so I am using **4.7.12** so that should be working.

**Comment by int19h** [comment]
It should be working once https://github.com/microsoft/vscode-python/issues/8422 is fixed, and we ship a new vscode-python release with that fix. 

I'll close this issue as a dup of the one above. If you're still having the same or a similar issue after it's fixed, please reopen.
