### ISSUE TITLE
incompatible with different pydevd

### ISSUE THREAD

**Issue by sailorfeng** [microsoft/ptvsd#1958]
I've install a newer pydevd for other usage, for example lastest version 1.8.0.
While the lastest ptvsd uses pydevd(1.3.3) which may not be compatible with 1.8.0.

How can I force ptvsd to use pydevd(1.3.3) in _vendored directory?

## Environment data

- PTVSD version: 4.3.2
- OS and version: Debian 9
- Python version (& distribution if applicable, e.g. Anaconda): 2.7
- Using VS Code:

## Actual behavior

```
/home/xxx/.local/lib/python2.7/site-packages/ptvsd/_vendored/force_pydevd.py:13: UserWarning: incompatible copy of pydevd already imported:

/home/xxx/.local/lib/python2.7/site-packages/_pydev_bundle/__init__.pyc
/home/xxx/.local/lib/python2.7/site-packages/_pydev_bundle/_pydev_calltip_util.pyc
/home/xxx/.local/lib/python2.7/site-packages/_pydev_bundle/_pydev_completer.pyc
/home/xxx/.local/lib/python2.7/site-packages/_pydev_bundle/_pydev_filesystem_encoding.pyc
/home/xxx/.local/lib/python2.7/site-packages/_pydev_bundle/_pydev_imports_tipper.pyc

.....
```

## Expected  behavior

No warning

## Steps to reproduce:
1. install latest pydevd & ptvsd.
2. try to debug with ptvsd.

**Comment by karthiknadig** [comment]
@sailorfeng `ptvsd` is not intended to be compatible with externally installed versions of `pydevd`. This is the reason we bundle `pydevd` with it. @fabioz (who owns `pydevd`) can provide additional info on the equivalent version between the bundled `pydevd` and released `pydevd`. That being said, what was the debugging scenario that you were trying to address?

**Comment by fabioz** [comment]
@sailorfeng as @karthiknadig said, `ptvsd` has a bundled version of `pydevd` within it. The version of `pydevd` inside of `ptvsd` is basically the same as `pydevd` (the version number of `pydevd` inside of `ptvsd` is not accurate... i.e.: the `master` version of `pydevd` has the same code as the `master` version of `ptvsd`, but the version there is still `1.3.3` -- the code is all the same, just the version number remains the same due to how the development is done... I keep care of making them the same on each new commit and they're always up to date). 

So, my suggestion in this case would be not installing `pydevd`, just install `ptvsd` and create a `.pth` file so that the vendored version of `pydevd` is used.

i.e.: For `ptvsd 4.x` you would create a `ptvsd.pth` inside of `python install dir/Lib/site-packages` with the following content:

`ptvsd/_vendored/pydevd`

@karthiknadig maybe we could create that file by default in `ptvsd 5` so that the bundled version of `pydevd` can be loaded without needing to change `sys.path`?

**Comment by int19h** [comment]
@fabioz The problem is that we don't version the interface between ptvsd and pydevd well (or at all, really). If we enable ptvsd to use arbitrary versions of pydevd, it will end up breaking people when they get out of sync eventually, because e.g. a new version of ptvsd is installed that requires some new pydevd feature, but the globally installed pydevd is much older and doesn't have it. That's mainly why we stuck to vendoring it.

**Comment by int19h** [comment]
@sailorfeng, to answer the original question - ptvsd always uses the vendored version of pydevd. The problem is that you can only have one pydevd loaded in the process at the same time, and thus it checks whether pydevd is already in `sys.modules` before trying to import its own vendored version. What you're seeing is the warning that results from that check. 

There's no way to directly import some version of pydevd in your app without having ptvsd use it, as well, unfortunately - it's the limitation that Python imposes on us. If the version of pydevd that you're using is okay in practice (e.g. if you can ensure that it's the same version that we're vendoring), then just go ahead and suppress the warning. 

That said, it is highly unusual to have the same app directly import both ptvsd and pydevd. Can you tell a bit more about your scenario, and why it requires both at the same time?

(Note that merely having pydevd _installed_ doesn't trigger this warning. It only happens if you have _imported_ it.)

**Comment by sailorfeng** [comment]
@fabioz I'll try creating `ptvsd.pth` file as you mentioned. Thanks for the solution.

@int19h It's not a big deal in my scenario which is my colleague used to debug with PyCharm. And that's why this confict happend when both debug libs are imported.
I've convinced him to give it up and fully embrace VsCode.
