### ISSUE TITLE
Debugger should not stop on GeneratorExit and StopIteration exceptions

### ISSUE THREAD

**Issue by fireattack** [microsoft/ptvsd#1959]
## Environment data

- VS Code version: 1.40.1
- Extension version (available under the Extensions sidebar): 2019.11.50794
- OS and version: Win7 x64
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.4 64bit
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language server

## Expected behaviour

No exception

## Actual behaviour

It shows 

![image](https://user-images.githubusercontent.com/4130991/69904087-f4edb600-1367-11ea-976b-14b78445e2dc.png)

## Steps to reproduce:

1. Debug the following code in a file:

```python
a = [1, 2, 3, 4]
b = [2, 7]
print(any(x in a for x in b))
```

It has been reported by other people at SO too: https://stackoverflow.com/questions/58261287/generatorexit-exception-when-debugging-any-line

**Comment by int19h** [comment]
I don't think the problem here is with `any()` as such - it just causes the generator to execute immediately. The exception itself is normal - it gets raised inside the generator whenever the outside code (in this case, `any()`, closes it). The bug here is that we're reporting it, even though the generator machinery will catch and handle it.

@fabioz, it looks like we should just be ignoring `GeneratorExit` in all circumstances? The docs straight up say that "it is technically not an error".

**Comment by fireattack** [comment]
Makes sense, thanks for investigating. Feel free to change the title to reflect that better.

**Comment by fabioz** [comment]
> @fabioz, it looks like we should just be ignoring `GeneratorExit` in all circumstances? The docs straight up say that "it is technically not an error".

Agreed... I'll take a look at it.
