### ISSUE TITLE
attach_by_pid fails on macOS + Python 3.x

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1961]
Consistent local repro when running `test_attach_by_pid`.

This was tricky to diagnose, because the code that captures output of lldb itself failed with `BrokenPipeError` when trying to read it - likely due to https://bugs.python.org/issue26372.

After removing the call to `communicate()`, and letting lldb dump its output directly, the following shows up in the log:

```
I+00000.430: Injector[PID=52388] output:
             b'Attaching with arch: i386:x86-64'

I+00000.432: Injector[PID=52388] output:
             b'Running: lldb --no-lldbinit --script-language Python -o \'process attach --pid 52388\' -o \'command script import "/Users/int19h/src/ptvsd/src/ptvsd/_vendored/pydevd/pydevd_attach_to_process/linux_and_mac/lldb_prepare.py"\' -o \'load_lib_and_attach "/Users/int19h/src/ptvsd/src/ptvsd/_vendored/pydevd/pydevd_attach_to_process/attach_x86_64.dylib" 0 "import sys;import codecs;decode = lambda s: codecs.utf_8_decode(bytearray(s))[0];script_path = decode([47, 85, 115, 101, 114, 115, 47, 105, 110, 116, 49, 57, 104, 47, 115, 114, 99, 47, 112, 116, 118, 115, 100, 47, 115, 114, 99, 47, 112, 116, 118, 115, 100, 47, 115, 101, 114, 118, 101, 114]);sys.path.insert(0, script_path);import attach_pid_injected;sys.path.remove(script_path);host = decode([49, 50, 55, 46, 48, 46, 48, 46, 49]);log_dir = decode([47, 85, 115, 101, 114, 115, 47, 105, 110, 116, 49, 57, 104, 47, 115, 114, 99, 47, 112, 116, 118, 115, 100, 47, 116, 101, 115, 116, 115, 47, 95, 108, 111, 103, 115, 47, 51, 46, 55, 45, 54, 52, 47, 116, 101, 115, 116, 115, 47, 112, 116, 118, 115, 100, 47, 115, 101, 114, 118, 101, 114, 47, 116, 101, 115, 116, 95, 97, 116, 116, 97, 99, 104, 46, 112, 121, 47, 116, 101, 115, 116, 95, 97, 116, 116, 97, 99, 104, 95, 98, 121, 95, 112, 105, 100, 91, 112, 114, 111, 103, 114, 97, 109, 93, 47, 83, 101, 115, 115, 105, 111, 110, 45, 49]) or None;attach_pid_injected.attach(port=61388, host=host, client=True, log_dir=log_dir)" 0\' -o \'process detach\' -o \'script import os; os._exit(1)\''

I+00000.433: Injector[PID=52388] output:
             b'Running lldb in target process.'

I+00000.464: Injector[PID=52388] output:
             b'(lldb) process attach --pid 52388'

I+00000.861: Injector[PID=52388] output:
             b'error: attach failed: Error 1'
```

That last error message is the lldb failure. @fabioz, can you please take a look?

**Comment by fabioz** [comment]
@int19h does it work in the ci? 

After searching a bit I found a reference saying that this is due to hardened runtime:
https://forums.developer.apple.com/thread/119059

If that's the case, it's more related to the `lldb` attach process (in which case we can't do much in our side) -- can you check if you can do at attach to a python 3.x process in your machine using lldb?

As a note, plain `pydevd` tests (without `ptvsd`) aren't currently run on mac os. I think that travis has support for it, so, I'll take a look if I can have that working on the ci as the first step.

**Comment by int19h** [comment]
There are sporadic failures on CI on MacOS. Problem is, they're hard to diagnose, because when it fails, it usually doesn't successfully capture the output of lldb, so the underlying cause is unknown. In this case, I edited it locally to disable redirection to be able to see the error, but ideally that should be captured in pydevd log. 

So I guess the immediate issue here is to improve logging, and then we can see whether CI is failing for the same reason or not. I suspect not, because local failure is very consistent, and the same test passes most of the time on CI.

**Comment by int19h** [comment]
With respect to hardened runtime - what's the workaround for it? From the linked thread, it sounds like this is something you can only work around by rebuilding the app. But the app is Python itself in our case, distributed from third party sources such as Brew. If it's built with hardened runtime, does that basically mean that attach-to-PID won't work? Or is there some workaround that I've missed?

**Comment by fabioz** [comment]
I think the culprit here was https://github.com/microsoft/ptvsd/issues/2049 (it could either halt on Mac with Python 3.5 or 3.6 or crash the interpreter), so, I think we can close this now -- if it still happens we can reopen it.

-- note that Python 3.7 or 3.8 were not affected by https://github.com/microsoft/ptvsd/issues/2049, so, if this issue also affected those versions my reasoning is not correct.
