### ISSUE TITLE
attach_by_socket tests fail sporadically on MacOS + Python 3.6

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#1967]
When it happens, it's usually several dozen tests failing in the same run for a given Python version. The only common theme is the attach method - the tests themselves are completely unrelated.

**Comment by int19h** [comment]
Suspected root cause is https://bugs.python.org/issue7995 - we do set timeout on a bunch of listener sockets.

**Comment by fabioz** [comment]
I think that this is the same thing as https://github.com/microsoft/ptvsd/issues/2049 (Mac + Python 3.6 seem to be the main place where it reproduces -- sometimes it would halt and sometimes it would give that crash -- it should be fixed in https://github.com/microsoft/debugpy/pull/8).

So, I'm going to close this issue -- please reopen if you see it again.
