### ISSUE TITLE
Local attach

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#200]
Need to investigate how to implement attaching directly to a local running process (i.e. not via remote debugging) with pydevd. We already ship the attach helper DLLs, but it's likely that they won't "just work", because of the way we deploy pydevd inside of our own package.

**Comment by huguesv** [comment]
FYI regarding local attach and Python 3.7: https://github.com/Microsoft/PTVS/issues/4145
Python 3.7 schedule is at https://www.python.org/dev/peps/pep-0537/

**Comment by DonJayamanne** [comment]
@karthiknadig @MikhailArkhipov @int19h @ericsnowcurrently 
Good news, I've managed to get this working. In fact it was fairly simple, now that we have `ptvsd.enable_attach`.

**Highlevel Solution:**
* Use existing code in pydevd to inject arbitrary python code.
* inject the code `ptvsd.enable_attach`
* That's it

Lets talk about this Next week.

@int19h I looked at this because I was working on a totally different debugging scenario and came across the injection code in Pydev.

**Comment by fabioz** [comment]
As a note, in the attach to process there's a provision to break into existing threads (specifically in https://github.com/Microsoft/ptvsd/blob/master/ptvsd/_vendored/pydevd/pydevd_attach_to_process/dll/attach.cpp#L1224 it sets the internal state to a thread and then calls the settrace in it).

This file is very close to the attach from ptvsd, so, it should be relatively straightforward to port the Python 3.7 fix from https://github.com/zooba/PTVS/commit/62d62687931e92c2cf15a4b7d318ccb45944044d.

**Comment by DonJayamanne** [comment]
Here's the prototype code - https://github.com/DonJayamanne/ptvsd/commits/attach
We might need to change:
* The way the debugger connects to VSC
* End the session (debugger host in the process) when debugger is disconnected 
Based on the prototype, this should be very easy.

**Comment by int19h** [comment]
API is probably a bit of a misnomer, since it's basically just a command line switch (or, alternatively, invoking `main`, passing the same arguments as `argv` parameter).
