### ISSUE TITLE
Uninformative error message when debugging

### ISSUE THREAD

**Issue by awildfivreld** [microsoft/ptvsd#2003]
Issue Type: <b>Bug</b>

When debugging this code:

```python
import numpy as np

print(np.dot(np.array([0,1]) - np.array([0,1])))
```
I get a new tab in vscode which states this:

```
Could not load source '<__array_function__ internals>': Source unavailable.
```
While I can see a "real" error message the "Call stack" section of the debugger (dot() is missing a parameter), this is not properly reflected in either the internal terminal or the new window that pops up.

This is the same code, but in the console:

```
>>> import numpy as np
>>> print(np.dot(np.array([0,1])))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 4, in dot
TypeError: dot() missing 1 required positional argument: 'b'
```

While not an earthshattering bug, I suppose it would be nice to get it fixed.

Extension version: 2019.11.50794
VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

**Comment by int19h** [comment]
It won't show up in the internal terminal, because that only happens when the exception escapes the app - Python prints the error traceback in that case. But at this point, it's paused at the line where the exception happened, before it escapes.

The other error message is happening because `numpy` uses generated code here with a dummy (non-existing) filename, and that generated code throws an exception. When we report it to VSCode, that dummy filename is in the stack, and the editor tries to open the corresponding file. This is a known issue - #1291.
