### ISSUE TITLE
Debug hover: shows empty when hovering over bogus words

### ISSUE THREAD

**Issue by isidorn** [microsoft/ptvsd#2011]
Hi, VS Code dev here :wave:

1. Have a python program and hover over some bogus words - like part of a string
2. Debug hover appears with no content
3. The issue here is that the python debug for `evaluate` of `"This"` returns a successful response. I suggest that for evaluating bogus expressions the python debugger returns a response with `success = false`

In this picture I am hovering over `This`.

Related issue: have a bogus expression in the WATCH view. The value is a structured object, instead it shuold just be an error like in the debug console

![Screenshot 2019-12-24 at 15 16 03](https://user-images.githubusercontent.com/1926584/71416358-50a61900-2660-11ea-9ecd-5b9ac4c5835c.png)

![Screenshot 2019-12-24 at 15 17 57](https://user-images.githubusercontent.com/1926584/71416427-a67ac100-2660-11ea-8bc2-f305d52cba12.png)

fyi @qubitron @DonJayamanne

**Comment by fabioz** [comment]
I think it's possible that this is this way because returning `success=false` on some cases force-stopped the debugger on Visual Studio (but I think that this should be fixed now), so, returning `success=false` should be ok at this point (but we should double-check with the Visual Studio team).

I created https://github.com/microsoft/ptvsd/issues/2014 to address the issue related to the error as a str.

**Comment by isidorn** [comment]
Ok thanks.
