### ISSUE TITLE
Debug completions stop working after calling help()

### ISSUE THREAD

**Issue by isidorn** [microsoft/ptvsd#2012]
Hi, VS Code dev here :wave:

1. Start debuggin python hit a breakpoint
2. Open debug console -> notice how you get nice suggestions
3. Enter `help()` 
4. You no more get suggestions from the python debug adapter

I guess the python interpreeter is stuck in help() mode and the adapter is no longer being able to get completions items. Is there some workaround for this scenario?

**Comment by fabioz** [comment]
The issue here is that:

```
Calling help() at the Python prompt starts an interactive help session.
Calling help(thing) prints help for the python object 'thing'.
```

So, by using `help()` (in the debug console) you'll see the `help()` interactive help session in the actual terminal (and it'll stay in that loop until you exit it and the debugger won't be able to answer in that thread until it exits -- if you go to the terminal and type `q` and `<Enter>`, you'll exit the help prompt and things will go back to normal -- and you can also use the terminal to ask for things as you'd expect from `help()`).

I'm not sure we should change anything here (things seem to be working as intended for me)...

**Comment by isidorn** [comment]
Thanks for the explanation. 
If nobody else from the users is hitting this than I am fine to close this as designed.
