### ISSUE TITLE
"Press any key" prompt appears when using Stop Debugging

### ISSUE THREAD

**Issue by RaymonGulati1** [microsoft/ptvsd#2026]
## Environment data

- PTVSD version: 5.*
- OS and version: Windows
- Python version (& distribution if applicable, e.g. Anaconda): CPython 3.7 (64 bit)
- Using VS Code or Visual Studio: Visual Studio

## Actual behavior
Stopping a debugging session results in "Debugging is being stopped..." dialogue (see below). 

## Expected  behavior
No dialogue should show up and the ptvsd adapter should terminate

## Steps to reproduce:
A bit difficult to reproduce for other people because my changes are integrating ptvsd 5 into PTVS and they haven't been merged into PTVS. 
1. Start a python script
2. Let it hit a breakpoint
3. Stop debugging by pressing the red icon in VS
4. Wait 5-10 seconds for that dialogue to show up

![image](https://user-images.githubusercontent.com/3315992/71932408-a5638c80-3154-11ea-9c3b-74bfe337d86a.png)

Logs
[ptvsd.launcher-39492.log](https://github.com/microsoft/ptvsd/files/4032627/ptvsd.launcher-39492.log)
[ptvsd.server-54884.log](https://github.com/microsoft/ptvsd/files/4032628/ptvsd.server-54884.log)
[ptvsd.adapter-26304.log](https://github.com/microsoft/ptvsd/files/4032629/ptvsd.adapter-26304.log)

**Comment by int19h** [comment]
The problem is that the adapter won't respond to "disconnect" until "terminated" event is sent, and the launcher (which is responsible for sending that) won't send it until the "Press any key..." prompt is reacted to. Basically, the debug session isn't considered fully completed until the user says it is.

The real bug here is that the prompt shows up when using Stop Debugging. The launcher should disable wait-on-exit when it gets "terminate" request.
