### ISSUE TITLE
Add symbols for the shipped binaries

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#2032]
@fabioz looks like we are missing pdb's for the dlls and exes that we ship (in `pydevd_attach_to_process`). can you add them?

**Comment by fabioz** [comment]
@karthiknadig I can add it, but I think we should start to think about generating those only for distribution instead of adding them to git (as well as dlls and exes themselves).

Right now I build them locally with `.sh` / `.bat` files (which are under `pydevd_attach_to_process`) -- we could just call them during the build (or I could do a makefile which may be more standard -- the compile step itself is pretty simple).

I was also thinking about not putting the cython-generated .c files in git also...

Thoughts?

**Comment by karthiknadig** [comment]
@fabioz We need it now because we are blocking one of our consumers. I agree we should just build this directly. As for the exact way we do that, I will leave that to @int19h to make the decision.

**Comment by fabioz** [comment]
Ok, I've just created a pull request adding the pdbs (note that the .exe pdbs have around 5mb each).
