### ISSUE TITLE
Live Share Debug not Functional

### ISSUE THREAD

**Issue by benjamin-weller** [microsoft/ptvsd#2050]
I'm unable to start a new debug session from the client or server when using live share.

I'm trying to do live share between a mac and a windows PC (although I don't think this should matter, live share isn't platform dependent from what I can tell).

Stack trace:
```
Traceback (most recent call last):
  File "/Users/user/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 317, in _on_run
    self.process_net_command_json(self.py_db, json_contents)
  File "/Users/user/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 133, in process_net_command_json
    request = self.from_json(json_contents, update_ids_from_dap=True)
  File "/Users/user/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 211, in _from_json
    return pydevd_base_schema.from_json(json_msg, update_ids_from_dap, on_dict_loaded=self._on_dict_loaded)
  File "/Users/user/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/_debug_adapter/pydevd_base_schema.py", line 123, in from_json
    return from_dict(as_dict, update_ids_from_dap=update_ids_from_dap)
  File "/Users/user/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/_debug_adapter/pydevd_base_schema.py", line 109, in from_dict
    return cls(update_ids_from_dap=update_ids_from_dap, **dct)
TypeError: __init__() missing 1 required positional argument: 'arguments'
````

**Comment by int19h** [comment]
We need some details about the debug session to diagnose this properly. If you set `"logToFile": true` in your launch.json, it'll produce a bunch of log files (`ptvsd*.log` and `pydevd*.log`) in the extension folder - could you please share those?

**Comment by benjamin-weller** [comment]
[ptvsd.adapter-1469.log](https://github.com/microsoft/ptvsd/files/4109114/ptvsd.adapter-1469.log)
[ptvsd.adapter-1514.log](https://github.com/microsoft/ptvsd/files/4109115/ptvsd.adapter-1514.log)
[ptvsd.launcher-1477.log](https://github.com/microsoft/ptvsd/files/4109116/ptvsd.launcher-1477.log)
[ptvsd.launcher-1520.log](https://github.com/microsoft/ptvsd/files/4109117/ptvsd.launcher-1520.log)
[ptvsd.server-1481.log](https://github.com/microsoft/ptvsd/files/4109118/ptvsd.server-1481.log)
[ptvsd.server-1524.log](https://github.com/microsoft/ptvsd/files/4109119/ptvsd.server-1524.log)

Unsure if this will help. On my client computer (PC) when I try and initiate a debug session it tells me that I haven't selected a version of Python (shouldn't this just execute the debug session using Python on the Mac/host?)

**Comment by int19h** [comment]
It looks like the client is sending a "modules" request with no "arguments" in it, because it doesn't want to pass any; but pydevd schema requires it. Not sure why this is affected by Live Share in any way - I'd expect it to manifest in any session. Either way, a simple fix. @fabioz, can you please update the schema?

**Comment by fabioz** [comment]
I'll take a look at it.

**Comment by fabioz** [comment]
@int19h I updated the `debugProtocol.json` to the latest version, but it seems that this is really a bug in the client (i.e.: `arguments` is a required argument for the `modules` request: https://github.com/Microsoft/debug-adapter-protocol/blob/gh-pages/debugAdapterProtocol.json#L1962 -- do you know if this is sent by `vscode` or `vscode-python`?).

Still, I think an invalid message shouldn't break the debugger, so, I'll harden the debugger so that if an invalid message is sent it will be able to proceed.

**Comment by int19h** [comment]
It's sent by VSCode itself.

I'm pretty sure it's actually a bug in the spec, because in all other requests, if all members of "arguments" are optional, then it can be omitted as a whole (e.g. "threads" works like that). And all properties are optional in the definition of `ModulesArguments`. They probably just copy-pasted the definition from something else, and forgot to remove "arguments" from the required list.

**Comment by fabioz** [comment]
I agree it seems like it should be optional, but if that's the case then the spec should be fixed (although the last time I reported something like that they said that `making a mandatory element optional would be a breaking DAP change`: https://github.com/microsoft/vscode/issues/48680, so, I think it'll be fixed in VSCode and not in the spec -- as a note, I'll make a fix in the debugger to accept that as optional anyways).

It's also strange that we just got this issue now (the spec seems to have that as mandatory for a long time), so, maybe something changed in VSCode itself.

@benjamin-weller can you provide the VSCode version where this is happening?

**Comment by benjamin-weller** [comment]
Client:
![image](https://user-images.githubusercontent.com/22554871/73368811-3cfd5c00-4277-11ea-9dd5-1b2139050cdd.png)

**Comment by benjamin-weller** [comment]
Server:
![image](https://user-images.githubusercontent.com/22554871/73369666-94e89280-4278-11ea-8545-d73a18ec82e5.png)
