### ISSUE TITLE
Uncaught exceptions in async loop (Discord.py)

### ISSUE THREAD

**Issue by DleanJeans** [microsoft/ptvsd#2095]
## Environment data

- VS Code version: 1.42.1
- Extension version: 2020.2.63990
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8 64-bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: Discord.py 1.3.1
- Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

Should break when there are uncaught exceptions.

## Actual behaviour

Fails silently.

## Steps to reproduce:

Install discord-py first:
```
pip install discord-py
```

```
# import random
from discord.ext import tasks, commands

bot = commands.Bot('-')

@tasks.loop(seconds=3)
async def print_random():
    print('Random number: ', end='')
    n = random.randint(1, 9)
    print(n)

if __name__ == '__main__':
    print_random.start()
    bot.run('NjgwMzg0NjI4NjkwOTExMjMy.Xk_Hpg.-PbjojzrdRU2ClF8K_MtF2mvtsk')
```

I've created a token just for this. Feel free to run the code with it.
Try running with `import random` commented and uncommented.

**Comment by int19h** [comment]
When you say "fails silently", do you mean that there is no Python stack trace printed out at all?

**Comment by DleanJeans** [comment]
Exactly. A `try except` with `traceback.print_exc()` would be needed, `raise` doesn't even work.

**Comment by int19h** [comment]
I think this is because the framework being used catches and swallows the exception, so it's not uncaught as far as Python itself is concerned - not much we can do here. You can set the checkbox on "Raised exceptions" to get a notification when the exception occurs in your code, but that will also trigger if you catch it yourself, unfortunately.

**Comment by DleanJeans** [comment]
Thanks for responding.

**Comment by fabioz** [comment]
As a workaround you can do yourself here, you can run with a breakpoint in the place where the unhandled exceptions are handled by the framework (which for this case seems to be `discord/ext/tasks/__init__.py` -- look for `log.exception('Internal background task failed.')`).

You should also be able to setup the logging machinery so that it prints that exception (i.e.: something as https://stackoverflow.com/questions/14058453/making-python-loggers-output-all-messages-to-stdout-in-addition-to-log-file).
