### ISSUE TITLE
Add support for ptvsd.enable_attach

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#251]
- [ ] Pausing does not work (I guess this is because when attaching, if there are no breakpoints, then pausing won't work).
- [ ] Breaking into debugger using (`break_into_debugger`) might not work for the same reason as above.

**Comment by DonJayamanne** [comment]
I've checked this out, unfortunately the way pydev is written the `settrace` is a combination of `ptvsd.enable_attach` and `ptvsd.wait_for_attach` (FYI - I'm referring to the behaviour in the older version of PTVSD).

We'll need to either:
* Try to work around this (somehow find a way to get this working)
* Or just bite the bullet and do the same in the new version of PTVSD

@int19h @karthiknadig cc

**Comment by int19h** [comment]
The main reason why we kept it separate is for scenarios like attaching to a running web server. But I'm not sure how common these are in practice. I mean, you wouldn't run in production with debugging enabled for sure, because of the perf penalty. Pretty much all user code that I've seen (in bug reports etc) always did `enable_attach` followed by `wait_for_attach`.

However, one thing that we can do on our side, is tell pydev that it is connected right away (since we control their "socket"), while still waiting for the incoming real socket connection from the IDE. This would mean that we'd need to do the pydevd handshake, and then just ignore all events, until a real connection is established. But it seems doable.

**Comment by DonJayamanne** [comment]
> However, one thing that we can do on our side, is tell pydev that it is connected right away 

Agreed. Hopefully the work that @ericsnowcurrently is working on for attach/detach will allow this scenario.
