### ISSUE TITLE
Add support for Python 3.7 breakpoint() function

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#253]

**Comment by DonJayamanne** [comment]
FYI - I've managed to get this working, without any changes to PYDEVD. We will have to add a minor change to PTVSD. that's about it.
Based on the spec, all we need to do is expose some env variables. I.e. technically speaking we don't need to make any changes to PTVSD or PYDEVD, just create the env vars.

**Comment by fabioz** [comment]
@DonJayamanne, as a note, `pydevd` will add that support anyways in the future, so, the implementation should consider the use-case of both `ptvsd` and `pydevd`.

I think that for `pydevd`, the call should be `pydevd.settrace`, but I think this is not compatible to how `ptvsd` wants to make the wrapping (I think it should be `ptvsd.break_into_debugger` for ptvsd), so, the main issue is how to deal with the different implementation expectations.

I think the simpler would be setting it at import time (so, pydevd would set it and ptvsd would override it afterwards)... the change just needs to be synchronized to make sure both work properly -- my idea was doing a pull request with both implemented at the same time with proper tests for both. 

Also, if the environment variable is already set, I think it should not override it -- i.e.: for PyDev my idea is having the IDE set the environment variable too, in a way that calling `breakpoint()` will actually connect to the remote debugger if possible and then pause the program (so, it'd also add `pydevd` to `sys.path`, import it and then call the `pydevd.settrace` -- I think VSCode/PTVS should do something similar...), so, the implementation provided by the debugger should only take place in the case where the user launches externally and then imports the debugger (where the debugger would be used as a remote debugger).

Also, I'd probably would go as far as creating a `breakpoint` builtin for earlier versions of Python with the implementation backported so that the API is similar for all versions of Python when using the debugger (although that's currently out of the scope of this issue).

**Comment by karthiknadig** [comment]
#756
