### ISSUE TITLE
Debugger throws error 'Unable to open <frozen importlib._bootstrap>'

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#312]
* Open VSC
* Select `Raised Exceptions`
* Start debugging a simple program `print("Hello world")`
* Debugger will display an error `Unable to open <frozen importlib._bootstrap>`

Problem:
* There is some error in PTVSD and the debugger is capturing this error and attempting to break into it (after all, we have enabled this feature `Raised Exceptions`.
* However this should not happen, until the user code has started.
I.e. we shouldn't be enabling exceptions filters/breakpoints until just before the user code is about to be executed.

https://github.com/Microsoft/ptvsd/issues/85

**Comment by DonJayamanne** [comment]
@brettcannon @int19h 
Is the milestone for this issue valid? Or should this be pushed to Release.
I'd consider this to be a fundamental issue.

**Comment by int19h** [comment]
This is one of the two items in https://github.com/Microsoft/ptvsd/issues/194. Basically, this is user code, specifically the implicit import of builtins at the very beginning of it. But we shouldn't be breaking there because the exception itself is in standard library code.

#194 is in Public Preview, so that's the right milestone (or we can close this one as a dupe).

**Comment by DonJayamanne** [comment]
> or we can close this one as a dupe

Done

**Comment by nkfeiyang** [comment]
where to enable or disable "Raised Exceptions"  in vsc?

**Comment by brettcannon** [comment]
@nkfeiyang there's a checkbox in the right-hand column while the debugger is running.
