### ISSUE TITLE
Hide _DummyThread threads

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#353]
Some times when debugging we see a thread named `Dummy-5` or `Dummy-6` in the call stack pane.
We might want to consider filtering out threads that inherit the `_DummyThread` class.

**Justification:**
While debugging a single threaded application I couldn't figure out why the `Pause` functionalityf was not working (`at all`), I could see the requests going from PTVSD into PyDev.
It took me a while to realize that the wrong thread was being paused.
VSC was sending the pause request for the `Dummy-` thread instead of the `MainThread`.
I.e. I failed to realize the fact that there were multiple threads in the call stack.

This also highlights the fact that `Pause` in VSC should `Pause` all threads, not just the thread sent in the `Pause` request (discussed with PTVS team).

**Comment by fabioz** [comment]
Dummy threads are actually expected on cases where the thread was not created using `threading` facilities (i.e.: using `thread.start_new_thread` or `QThread`), so, they can't be reliably filtered out.

There was an issue in that some threads from `ptvsd` were not marked as `pydevd` threads, which made `pydevd` report them, but I think this should be fixed in the current master now. 

The other issue I can think of is if the debugger tries to get the currentThread from a thread before it was actually put in the list of live threads -- I think that with the latest changes this should not happen (I cover that now in https://github.com/Microsoft/ptvsd/commit/d635e22d3396f1cf3ab2fe9bc6fc9f5395b38232#diff-9f9c206706e9769d499d95be0ec27196R59).

So, I think this can be closed now (although if you can still reproduce with the latest ptvsd master I can take a new look on the pydevd side).
