### ISSUE TITLE
Add 'remote launch' - launch a program for remote debugging but continue running the user code

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#355]
Today when using `python -m ptvsd --server --port 1234 --file xyz.py`, ptvsd does not run the user code until a debugger is connected.

We'd like to change this to continue running the code (similar to having `ptvsd.enable_attach()` at launch time)

Requirement:
Add a flag named `--wait`

**Comment by DonJayamanne** [comment]
@qubitron is this something you'd want to see for VSC Release.

**Comment by qubitron** [comment]
For backwards compatibility @zooba commented this morning that we'd actually want to add a "--wait" flag that tells ptvsd to wait to launch, because the default behavior in the previous version was to launch without waiting. Since ptvsd is already integrated into Azure services, we wouldn't want to change the default behavior.

**Comment by qubitron** [comment]
Also, this needs to be for the VS stable release and/or VSC public preview
