### ISSUE TITLE
Performance hit debugging Django code

### ISSUE THREAD

**Issue by zooba** [Microsoft/ptvsd#358]
While debugging Django templates, @qubitron noticed a big slowdown after adding a breakpoint. Every request after that was much slower than before.

We suspect this is because of tracing switching on due to the breakpoint, but not switching off. It also may be because tracing then goes through a lot of stdlib/Django code that it doesn't really need to trace.

**Comment by qubitron** [comment]
More info, my specific repro steps are to F5 this app:
https://github.com/qubitron/stackoverflow-django

Browse to the ```/frameworks?language=Python``` page, results (using stopwatch app):
- OLD Debugger, first time load: 21s
- OLD Debugger, refresh page: 13s
- OLD debugger, run from first breakpoint to second: 13s
- OLD debugger, run from first breakpoint to second with just my code disabled: 13s
- OLD debugger, unset breakpoints and refresh: 13s
- NEW debugger, first time load: 12s
- NEW debugger, refresh page: 9s
- NEW debugger, run from first breakpoint to second: 26s
- NEW debugger, unset breakpoints and refresh: 27s

I had previously seen a greater difference between the two debuggers in the past, a 2-3x speedup on the new debugger for this exact same scenario with the page loading in about 5s on the new debugger, which makes me think something has been introduced that is causing a performance slowdown.

**Comment by int19h** [comment]
Still investigating, but it appears to have something to do specifically with setting breakpoints while the app is running. If breakpoints are set before F5, then they don't affect perf substantially unless it's the same function/frame (and even then the slowdown is nowhere near as big). But if a breakpoint is set after, things slow down substantially.

This is regardless of where the breakpoint is (i.e. it can be in a different file that's not even loaded). It also applies to all code, not just Django; but Django templates are the worst affected, which is likely why you've noticed it there.

**Comment by int19h** [comment]
Okay, so at this point I'm pretty sure that this is not a regression on our side, or that we're using pydevd in the wrong way - I have a condensed simplied repro showing similar results in LiClipse on stock pydevd (with none of our changes). @qubitron, can you give that a try as well, just to make sure that we're looking at the same issue here?

**Comment by fabioz** [comment]
I actually started to take a look at this and my initial guess is not correct. This isn't really django-specific... to make it clear, there's still one issue with breakpoints on django templates in that it won't allow frames to be skipped, but this problem isn't really related to it.

By investigating a bit more, the problem happens only on python 3 due to interactions on the 2 approaches to debugging (one approach uses the regular sys.settrace and the other modifies the frame code object to add programmatic breakpoints using the api available to customize the frame evaluation).

Note we can't use the evaluation approach on a few of situations anyways (i.e.: handled exceptions, changing breakpoints, breakpoints in django templates or jinja templates...), so, my suggestion is initially disabling the evaluation approach -- to make a real fix it'll take a bit longer... probably the real fix will be making sure that when the tracing approach is turned on, the evaluation approach is completely turned off instead of having both running an the same time as happens now.

The approach which modifies the frame code object is actually optional already, so, the initial fix should be just letting it off by default (the only downside is on the use case where the user has a case where most of the time is dominated by the tottime of a function -- if it's dominated by function calls the tracing approach works as well as the evaluation approach, but the overhead even on the case of the time dominated by the tottime of a function is ok, especially if the cython modules are available, and if the user actually hits a case where this is slow, he can use programmatic breakpoints instead of adding a breakpoint so that no overhead is incurred until his programmatic breakpoint is hit).

**Comment by karthiknadig** [comment]
Tried this with @qbitron on my desktop. This looks like it is fixed. Reopen if there are more issues.
