### ISSUE TITLE
Poor startup time performance when using Anaconda

### ISSUE THREAD

**Issue by huguesv** [Microsoft/ptvsd#378]
With Anaconda 5.0 (Python v3), startup is really slow (several seconds). Compared to old ptvsd, which starts up immediately.
It's not an issue on my CPython 3.6

Tested on VS.

**Comment by DonJayamanne** [comment]
@huguesv @karthiknadig 
I'll check if we have the same perf issues on VSC (so far I can't see any such perf issues on Mac and Linux)

**Comment by DonJayamanne** [comment]
I've tested this on VSC on a Windows with (Anaconda 5.0 Python 3):
* Old version of PTVSD - 1 second
* New version of PTVSD - 2 seconds

So, yes there is a slight delay, however the delay is not as bad as in VS.

**Comment by DonJayamanne** [comment]
@huguesv @karthiknadig Please could you ensure you have installed the necessary cython extensions.

**Comment by huguesv** [comment]
Reported on Visual Studio Community at https://developercommunity.visualstudio.com/content/problem/259468/vs-1572-experimental-python-debugger-absolutely-no.html

**Comment by int19h** [comment]
I'm not observing any significant slowdown in general. One thing that can significantly increase startup time is if the same ptvsd install is used across several Python versions, because then it needs to recompile bytecode, which does push startup time upwards into several seconds. But once that bytecode is cached, subsequent uses show sub-second load times, on both Anaconda and regular Python.
