### ISSUE TITLE
Fix the names of the Windows wheels

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/ptvsd#387]
Looking at https://pypi.org/project/ptvsd/4.1.1a1/#files I noticed that the files are labeled as `py3` and not `cp36` or any specific version of Python. So are the wheels not containing any binary files, or do they and the filename is off? Or am I misunderstanding how wheels on Windows work and this is some magic juju of Steve's? 😉

**Comment by zooba** [comment]
It's magic :)

The wheels include all the required .pyd files for 3.5 and later. Users who are configured to build for 3.0-3.4 need to install without binaries to get the speedups, and users on 2.7 will default to installing from sdist and get the speedups if they have the compiler handy. We aren't releasing pre-built binaries for any of these versions (not least because we're not supposed to release anything built with unsupported compilers...)

The reason we have multiple copies of the same wheel is because there is no tag for "win_any". But the wheels are identical (other than a metadata change in order to break hash comparisons between the two files).
