### ISSUE TITLE
Breakpoints don't hit on attach

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#448]
Repro steps:
1. Copy the code below into test.py
2. Make sure you are synced to latest ptvsd master
3. set PYTHONPATH to ptvsd
4. In the command prompt run `py -3.6 test.py`
5. From VS/VSC open `test.py` file and set breakpoints on line 7 and 10.
6. Attach to `tcp://localhost:5678`

![image](https://user-images.githubusercontent.com/3840081/40738084-6a4d55d0-63f7-11e8-8aaf-1610c412ac26.png)

Expected: 
Breakpoint on line 7 is hit.

Actual:
Console displays `Hello! What is your name?` and waits for user Input. The break-point on line 10 is hit after entering some text.

Repro code:
```python
import random
import ptvsd

ptvsd.enable_attach()
print("test!!!!!!!!!!!!!!!!!!!! wait for attach")
ptvsd.wait_for_attach()
print('ptvsd version: %s' % ptvsd.__version__)
guesses_made = 0
name = input('Hello! What is your name?\n')
number = random.randint(1, 20)
print('Well, {0}, I am thinking of a number between 1 and 20.'.format(name))

while guesses_made < 6:
    guess = int(input('Take a guess: '))
    guesses_made += 1
    if guess < number:
        print('Your guess is too low.')
    if guess > number:
        print('Your guess is too high.')
    if guess == number:
        break
if guess == number:
    print('Good job, {0}! You guessed my number in {1} guesses!'.format(name, guesses_made))
else:
    print('Nope. The number I was thinking of was {0}'.format(number))
```

@DonJayamanne , @ericsnowcurrently for reference. This used to work in 4.1.1.a1

**Comment by ericsnowcurrently** [comment]
I got the same result (bp on line 7 not hit) on linux using VSC.

**Comment by ericsnowcurrently** [comment]
I switched PTVSD to the v4.1.1a1 tag and found that breakpoints were not hit at all.

Also, I noticed that under 4.1.1a1 I got the warning about Cython, but under master I didn't.

**Comment by ericsnowcurrently** [comment]
After clearing all breakpoints and then setting the two again, I got the original behavior (bp on line 7 not hit, line 10 hit).  So this does not appear to be something new.

**Comment by ericsnowcurrently** [comment]
As far as I can tell, there's a race involved here.  ``ptvsd.enable_attach()`` only starts the session (once a connection happens).  It doesn't wait for the "handshake" messages to finish.  This means that ``ptvsd.wait_for_attach()`` will likely finish well before breakpoints are set.  Thus a breakpoint right after the ``wait_for_attach()`` call has a decent chance of not being hit.

**Comment by karthiknadig** [comment]
Removing pri0 since this was seen in previous release

**Comment by DonJayamanne** [comment]
@ericsnowcurrently 
#501 and #462 might be related.

**Comment by ericsnowcurrently** [comment]
PR #502 addresses the issue as much as currently possible.  There's still a problem with how pydevd does not respond for `CMD_SET_BREAK` messages.  So we have no way of deterministically knowing when the new breakpoints are active.  Until that gets solved we will have the race described above.

Possible solutions:

* make pydevd respond to `CMD_SET_BREAK` (once the new breakpoints are active)
* add something like `CMD_GET_BREAK` to list active breakpoints (allowing us to poll)

**Comment by ericsnowcurrently** [comment]
...ideally we'd have both.  A response from `CMD_SET_BREAK` would make things simple and a new `CMD_GET_BREAK` makes sense regardless of solving this issue.

**Comment by ericsnowcurrently** [comment]
@fabioz, thoughts?

**Comment by fabioz** [comment]
@ericsnowcurrently I think that it should be possible to make it work without changes to pydevd.

I think that the problem is that the `ready_to_run` flag is directly set prior to setting the breakpoints in:

https://github.com/Microsoft/ptvsd/blob/fb27b4187fc5dcbafa26b2552a07174fef450247/ptvsd/_remote.py#L28

The proper way is making the connection, setting the breakpoints and then sending a `CMD_RUN`, which would be handled only after breakpoints are added... that way there'd be no racing condition.

The one problem I see is that `wait_for_attach` in https://github.com/Microsoft/ptvsd/blob/fb27b4187fc5dcbafa26b2552a07174fef450247/ptvsd/attach_server.py#L22 uses a local event to check if it's Ok with a callback sent from the `enable_attach` and this will get into a racing condition... better to just ask for some message and get its confirmation (i.e.: issue a `CMD_LIST_THREADS` and wait for it to be completed -- as commands are always handled sequentially, you can be sure that for that command to be answered `CMD_RUN` has already been issued properly -- the other option would be using the non-stable API and check if `debugger.ready_to_run` is true at that point, but ideally ptvsd should not access the pydevd non-stable API and should just exchange messages which are guaranteed to be backward compatible).
