### ISSUE TITLE
Tools tip for dictionary shows object hash

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#45]
![image](https://user-images.githubusercontent.com/3840081/35876515-5e08541a-0b27-11e8-941b-1bda759e56e1.png)

**Comment by fabioz** [comment]
As a note, I've started to take a look at this issue.

**Comment by fabioz** [comment]
After investigating it, this will actually be a big change in `pydevd`

The main issue is that the API to get variables only provides users with a way to get a dictionary of key->value which will already be the final representation of the object (and what's shown to the user is later used to get the variable again).

To fix this, both the protocol as well as the internal API will need to be changed to allow for object identifiers to be given to variables so that the what's shown to the user does not need to contain that information (which means that the protocol has to be changed to send and receive such an id to get the variable and that mapping of ids->variables must be kept while the thread is suspended).

Given that this will touch a good number of places, my suggestion would be already fixing the other related issue which is being able to have a different formatter per-request and try to use json instead of xml as a payload for the responses which return variables.

My estimate is around 12 days to have this complete. I'll already start on it, but as it'll take a while until it's actually integrated let me know if there's something I should take a look first given that this will take longer than I anticipated.

On the good side, the solution is closer to what the debug adapter protocol expects, so, the integration in   `ptvsd` will need to do less work and formatters will be more flexible than now.

**Comment by karthiknadig** [comment]
I will go over the issues and let you know.

**Comment by DonJayamanne** [comment]
Though this is a dup of #1114, please note the values are more prominent in VSC, hence the issue is worse in VSC than in VS.
In VS you get the values only as tooltips, where as in VSC they are `always` visible.
The fact that it manifests it self differently in VSC could impact the priority of this issue

**Comment by karthiknadig** [comment]
The thing is this is how `pydevd` formats dictionaries. When that part is fixed, it will fix this in all places. Do let us know if we need to bump the priority on this.

**Comment by karthiknadig** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/3840081/53442685-b84af380-39be-11e9-90c1-3d0fcec13d97.png)

![image](https://user-images.githubusercontent.com/3840081/53442698-bc771100-39be-11e9-8b55-dc2afecc1a84.png)
