### ISSUE TITLE
Output from print statements not delimited with a line separator

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#489]
* OS - Mac
* VS Code - Latest version

**Python code:**
```python

import time
import threading

def one():
    while True:
        print("Do in one")
        time.sleep(1)

def two():
    while True:
        print("Do in two")
        time.sleep(1)

def three():
    while True:
        print("Do in 3")
        time.sleep(1)

workers = []
worker = threading.Thread(target=one)
worker.start()
workers.append(worker)

worker = threading.Thread(target=two)
worker.start()
workers.append(worker)

worker = threading.Thread(target=three)
worker.start()
workers.append(worker)

worker.join()
```

**Current version of PTVSD output is as follows:**
Note how the first line contains output from print statements that are not line separated.
```
Do in oneDo in twoDo in 3

Do in one
Do in two
Do in 3
Do in one
Do in 3
Do in twoDo in 3
Do in one
Do in twoDo in 3
Do in one
Do in twoDo in 3Do in one
Do in 3Do in twoDo in one
```

** Older version of ptvsd - ptvsd 4.1.1a5 (working)**
```
Do in one
Do in two
Do in 3
Do in one
Do in two
Do in 3
Do in one
Do in two
Do in 3
Do in one
```

<img width="881" alt="screen shot 2018-06-14 at 2 18 08 pm" src="https://user-images.githubusercontent.com/1948812/41438948-d83954ee-6fdd-11e8-9ed4-6268ec3e4df5.png">

**Comment by DonJayamanne** [comment]
@fabioz cc

**Comment by fabioz** [comment]
Short answer: this is expected and it's up to users to synchronize on prints when using multiple threads).

Long answer:
If you run the same sample in a terminal without debugging you can observe the same result as print actually does 2 writes (one for the text and another for the '\n'). 

Previously it was a bit better because buffering provided less opportunity for the thread to switch between the 2 writes, but now that it creates a message and has to get a lock to put the message on a queue to be sent it becomes a bit more apparent (and in the terminal where it has to actually write to the I/O it's also pretty apparent).

**Comment by DonJayamanne** [comment]
> Long answer:
If you run the same sample in a terminal without debugging you can observe the same result as print actually does 2 writes (one for the text and another for the '\n').

I don't observe this behavior with Python 3 on a Mac. 
Whats interesting is, in the terminal, everything is fine.
In the debugger, things get messed.

@fabioz Please could you confirm you are using Python 3?
From what I can tell, line feeds get messed up only when running in Python 2.

I still believe this is a problem with the debugger.
If it doesn't `consistently` happen in the terminal in Python3, it shouldn't `consistently` happen in the debugger either, at least when using Python 3.

@karthiknadig @MikhailArkhipov 
Awaiting a decision.

**Comment by DonJayamanne** [comment]
@fabioz Lets leave this issue open for now. 
Not a critical issue (discussed with @MikhailArkhipov & @karthiknadig).

**Comment by gramster** [comment]
Low pri.
