### ISSUE TITLE
Enable gevent support by default

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#498]
> https://github.com/Microsoft/ptvsd/issues/497#issuecomment-398464766

@fabioz Is there any reason not to always enable GEVENT_SUPPORT in the debugger?
I.e. what's the implication of setting this flag to True, even when not using `gevents`?

**Comment by fabioz** [comment]
When gevent support is enabled pydevd may have to reload version of the libraries of threading, socket, etc so that the debugger can keep on working (as the debugger must use real threads and will deadlock with greenlets), but this isn't ideal when gevent is not being used (so, I'd say it's not ideal to have it on by default).

Another thing I just noted is that ptvsd itself will probably have to be protected against the gevent monkeypatching, so, my suggestion will probably not work (so, I think more work will need to be done in order for ptvsd to work with gevent -- I may be wrong though... it definitely needs more investigation).
