### ISSUE TITLE
Majority of the Tests do not run on Python 2.7 (on Travis)

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#551]
@ericsnowcurrently @karthiknadig @int19h @d3r3kk 
Is there any reason we're not running tests on Python 2.7.
I would have thought this was a simple matrix and we run tests on a number of versions.

* 149 tests run on Python 2.7
* 595 tests run on Python 3.4...

* Is this deliberate? If so why?
* How do we change this?
* What's the setup on VSTS (@d3r3kk)

**Comment by d3r3kk** [comment]
> - What's the setup on VSTS (@d3r3kk)

No idea what's going on with Travis, I never paid much attention to that.

However, in VSTS you have full coverage I believe (other than macOS only hitting 2.7 and 3.6, I can change that if you all would like me to).

595 tests for each OS + Python Version, not including Python 2.7. For Python 2.7 it appears there is a flag that is being respected, `--quick-py2`, this is probably the culprit.

![image](https://user-images.githubusercontent.com/11466735/42120749-4c7c7414-7bd5-11e8-8929-7a3558ae9b4a.png)

[I queued a build after putting that particular flag into a build variable. For the build I queued I removed the value --quick-py2, we can inspect it after its done.](https://ptvsd.visualstudio.com/ptvsd/ptvsd%20Team/_build/results?buildId=213&view=logs)

**Comment by ericsnowcurrently** [comment]
I enabled the whole test suite on 2.7 a while back but ran into some problems with travis.  I hadn't gotten back to trying again and apparently forgot to open an issue.  I'll look into it.

**Comment by d3r3kk** [comment]
@DonJayamanne no, VSTS runs Py2.7 and Py3.6 on macOS, and 2.6 through to 3.7 on Windows/Linux.

I know there are a bunch of tests that were failing previously, but isn't that because we test a lot more versions of Python + macOS + Windows in there?

[If you look at the VSTS build](https://ptvsd.visualstudio.com/ptvsd/ptvsd%20Team/_build/results?buildId=213&view=logs) the build is failing *even harder* when I removed that --quick-py2 flag...

**Comment by karthiknadig** [comment]
This is fixed with the pytest based tests.
