### ISSUE TITLE
Multiprocess debugging support

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#57]
pydev is currently started in single process mode. we need to pass `--multiprocess` flag as a command line arg. That may not be enough, we may need custom protocol messages to tell VS/VSC adapter that another process has started.

**Comment by huguesv** [comment]
Also reported on developer community at https://developercommunity.visualstudio.com/content/problem/231012/pydev-debugger-breakpoints-wont-work-in-the-new-pr.html

**Comment by fabioz** [comment]
A note here: due to the way that things are wrapped I think ptvsd won't know how to talk to the newly created multiprocess, so, this won't be simple to add in the current structure.

The main issue is that ptvsd expects an in-memory pydevd and requires patching it in some places instead of launching pydevd and then acting as a server to it to just translate what's needed to vscode (in which case it could just treat the spawned process as a new pydevd process and translate the threads from that process accordingly to vscode -- i.e.: vscode doesn't need to know about new processes, the adapter could do the needed work to send messages to the right process given the thread ids).

Another thing is that the whole patching expects pydevd to be the main entry, not ptvsd (so, many other things would need to be patched for this to work).

I think the main issue it was done this way is because pydevd doesn't communicate through the debug adapter protocol, so, ideally pydevd itself could communicate through the debug protocol (instead of needing ptvsd as a wrapper) and then have ptvsd work more as a customization layer of pydevd and launching customization.

**Comment by DonJayamanne** [comment]
> I think the main issue it was done this way is because pydevd doesn't communicate through the debug adapter protocol,

Well, I think this is still possible. PTVSD talks to pydevd using the pydev protocol (over a fake socket). So, when dealing with multi-process debugging, all we need to do is, get PTVSD to talk to pydevd over an actual socket!

Isn't that all that's required? Or am I missing something?

/cc @karthiknadig @fabioz

**Comment by DonJayamanne** [comment]
Here's a proof of concept, managed to get this working very easily using existing code.

![multiproc](https://user-images.githubusercontent.com/1948812/42790900-2ff6ca74-8922-11e8-9602-d770d053b2d6.gif)

**Comment by DonJayamanne** [comment]
@karthiknadig 
We should be able to turn existing PTVSD code into a DA, by simply using a real socket instead of a fake socket when communicating with pydevd.
I.e. very simple minor changes to turn existing PTVSD into a DA.

That's pretty much what I did to get the above working, PTVSD is a DA in this case, and PyDevD is running in the child process.

/cc @ericsnowcurrently

**Comment by fabioz** [comment]
@DonJayamanne I think this would be the ideal solution -- I thought it'd be more work given the way customizations are done, but if you got it running with few changes, even better ;)

This would probably fix a number of other issues as `pydevd` could work standalone (so, issues such as regular exiting wouldn't be issues anymore and the debug adapter could do some things better without being in the same process -- one thing that comes to mind is not needing to redirect output unless it's a remote debug as the debug adapter could just grab the output from the subprocess pipe).

**Comment by DonJayamanne** [comment]
> This would probably fix a number of other issues as pydevd could work standalone

Agreed.

> as the debug adapter could just grab the output from the subprocess pipe

Agreed. This would be lot more efficient as well.

**Comment by jwilges** [comment]
@DonJayamanne are these changes planned? Your approach sounds like it's a huge step forward. Do you have a patch to share? I'd be psyched to take a look at it and try it locally. My current workarounds for multi-process debugging are cumbersome.

**Comment by alphacentauri12** [comment]
Nice! 👍 
A patch would be great for the moment! ;-)

**Comment by GandalfSaxe** [comment]
Will this issue also cover Python multiprocessing's Pool().map?

https://docs.python.org/3.4/library/multiprocessing.html

**Comment by DonJayamanne** [comment]
@karthiknadig 	@int19h 

I couldn't get it to work, probably some setup issue.
I didn't pass the variable, instead is just modified [_local.py](https://github.com/Microsoft/ptvsd/blob/master/ptvsd/_local.py#L17) to include the `--multiprocess` flag.

Please try this extension.
Note: PTVSD is not included in the extension, hence you'll need to set the environment variable in `launch.json` to use `PTVSD` for launch scenarios.
```js
        {
            "type": "python",
            "env": {
                "PYTHONPATH": "/Users/donjayamanne/Desktop/Development/vscode/ptvsd"
            }
....
        },
```
[python-2018.10.0-alpha.vsix.zip](https://github.com/Microsoft/ptvsd/files/2488257/python-2018.10.0-alpha.vsix.zip)

**Comment by DonJayamanne** [comment]
@int19h Got this working guys, had to make some changes at my end.

**Comment by karthiknadig** [comment]
The debugger in `master` supports `spawn` processes, not `fork` processes. The work item is not complete. To use with multiprocessing on windows, you have to set `multiprocessing.set_start_method('spawn')`

The work is being tracked here: https://github.com/Microsoft/ptvsd/issues/425
Sample usage: https://github.com/Microsoft/ptvsd/blob/master/pytests/func/test_multiproc.py

**Comment by DonJayamanne** [comment]
@int19h 	@karthiknadig 

* Please install and use this extension for testing multi-process debugging.
* Please rename the extension to `.vsix` 
* Install in VSC

[python-2018.10.0-alpha.vsix.zip](https://github.com/Microsoft/ptvsd/files/2489615/python-2018.10.0-alpha.vsix.zip)

**Comment by sourabhXIII** [comment]
@DonJayamanne 
Thanks for the patch.
Can you please help me understand how to install it? What should I rename to `.vsix`?

**Comment by karthiknadig** [comment]
@sourabhXIII If you have the latest released version of the extension, then in the launch json put `"subProcess": true` to enable this. There are some limitations to this feature. It currently supports `spawn` subprocesses and `fork` subprocesses are a work in progress (see #943 for tracking). 

If you are using this on linux/mac with `multiprocessing` library you have to set `multiprocessing.set_start_method('spawn')` before using it. That setting is supported only on python 3.x, for 2.x you have to wait until #943 is done.

**Comment by zchrissirhcz** [comment]
@karthiknadig 
Hi, I'm using python3.7 and just using the example code below:

`A.py`
```python
#!/usr/bin/env python
#coding: utf-8

import multiprocessing
multiprocessing.set_start_method('spawn')

from multiprocessing import Process, Event

import B

if __name__ == '__main__':
    update_event = Event()
    client_proc = Process(
                args=(update_event,),
                name="client",
                target=B.TestFunc,
            )
    client_proc.start()

    import time
    time.sleep(100)
```

`B.py`
```python
#!/usr/bin/env python
#coding: utf-8
import time

def TestFunc(a):
    while True:
        time.sleep(5)
        print(a)
```

`launch.json`
```javascript
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: cur file",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "subProcess": true
        }
    ]
}
```

When setting a break point in A.py's 12-th line, and by clicking `step over` in python debug mode, my VSCode just crash, failed to debug this very-simple-python-multiprocessing-code. So sad.


My VSCode is just updated this afternoon, ubuntu16.04.  Its detail:

版本 1.34.0
提交 a622c65b2c713c890fcf4fbf07cf34049d5fe758
日期 2019-05-15T21:55:35.507Z
Shell 3.1.8
渲染器 66.0.3359.181
Node 10.2.0
架构 6.6.346.32

**Comment by int19h** [comment]
This is not a debugger issue - the same behavior can be observed running A.py directly.

The reason is that this line:
```py
multiprocessing.set_start_method('spawn')
```
[must be](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) inside the `if __name__ ...`  block. Otherwise, it gets run twice in the child process, causing this exception.

**Comment by zchrissirhcz** [comment]
@int19h Thanks for your reply. It works for my pasted A.py and B.py example. Actually I was trying debugging a large python program and I'll try if it also works when it is available.
