### ISSUE TITLE
Support for pdb.pm() like post-mortem debugging

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#690]

**Comment by andyneff** [comment]
@karthiknadig do you know of any work around to achieve post-mortem debugging?

I tried the following, but I don't think `_pydevd_settrace` is designed to work this way

```python
import ptvsd
from ptvsd._remote import _pydevd_settrace
def pm_hook(type, value, tb):
  if not ptvsd.is_attached():
    print("Crash detected. Waiting...")
    ptvsd.wait_for_attach()
    # ptvsd.break_into_debugger()
    _pydevd_settrace(
        suspend=True,
        trace_only_current_thread=True,
        patch_multiprocessing=False,
        stop_at_frame=tb.tb_frame,
    )
    print("Attached")

import sys
sys.excepthook = pm_hook
```

I use similar code with other python debuggers to start post mortem on error

**Comment by karthiknadig** [comment]
@andyneff Are you calling `ptvsd.enable_attach` some where else? `wait_for_attach` will block until you attach from with VS/VSC. Also `enable_attach` does not let you pass arguments to _pydevd_settrace (see `attach_server.py`) you may have to edit that to allow passing the args. I am curious, if it will work after making the recommended changes, let me know.

As for whether `_pydevd_settrace` works in this scenario @fabioz can give better answer.

**Comment by andyneff** [comment]
Yes, I was. I forgot to include that in the snippet. **Updated**

**Comment by fabioz** [comment]
@andyneff as @karthiknadig said, in ptvsd you need 2 calls to attach: `ptvsd.enable_attach()` and `ptvsd.wait_for_attach` afterwards (it's a bit different from plain `pydevd` where a single call would do both).

Now, after it's attached, what you're trying to do won't work well because the debugger won't actually enter that frame (so, it won't pause where you want it to pause) and right now there's no public API for that -- hence this bug ;)

It should be possible to do with a private API, although I can't really give you the code right now (not on front of my machine).

@karthiknadig please assign to me to add the public API.

**Comment by gramster** [comment]
Closing due to lack of upvotes.
