### ISSUE TITLE
Create tests for remote debugging using IP Address of local machine

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#701]
Test Regression https://github.com/Microsoft/ptvsd/issues/578

**Comment by karthiknadig** [comment]
Lowered the priority on this as we discussed. 

Reasoning:
The issue occurred because we were not passing the host `0.0.0.0` to `pydevd`. So, by default it was setting up as local host. To test this correctly we need to run the tests and debugger on different ip address. 

There is already a test `test_attach_byip` that attempts to connect to the debugger using ip address. This test will always pass even with the bug 578. because any port opened on localhost will accept connections form the same machine.

**Comment by karthiknadig** [comment]
Looks like these will be a set of multi-machine or container based tests. @d3r3kk @DonJayamanne any suggestion on  options available to do the `[win|mac|nix] <--> [win|mac|nix]` combination of connections. If not all which should be tackled first.

**Comment by d3r3kk** [comment]
Tests such as this have a **lot** of variables outside those of the tests themselves. This set of external variability is something that will unfortunately and necessarily make the test runs susceptible for plenty of false negatives.

I would definitely recommend that we consider to make this testing part of a new VSTS automation process. This new automation could run nightly. Make cross-machine testing a part of a release process as well, using VSTS release automation would make this relatively simple to do.

**Comment by int19h** [comment]
The original scenario is no longer particularly interesting. What we need is tests that actually test remoting (e.g. with containers).
