### ISSUE TITLE
Hide unwanted messages

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#719]
@fabioz 
Is there a way we can hide the following message:
`pydev debugger: New process is launching (breakpoints won't work in the new process).
pydev debugger: To debug that process please enable 'Attach to subprocess automatically while debugging?' option in the debugger settings.`

This is confusing our users. We repeatedly get issues reported in VS Code, and people misunderstand this to be an error.

**Comment by fabioz** [comment]
Not currently... I'll make that optional (or maybe send those messages through commands for the IDE to decide what to do).

**Comment by DonJayamanne** [comment]
Would be great if this can be done for the release of it's easy.
Would like to have a perfect release 😁 in August...lol..

**Comment by fabioz** [comment]
Ok, I'll do that tomorrow (should be easy).

**Comment by fabioz** [comment]
Ok, I think the proper fix would be having all logging go as commands to the IDE instead so that it can be filtered... I started going that path, but I won't be able to finish for today and I think there are some other issues which are more important, so, I provided a pull request to simply remove that output (https://github.com/Microsoft/ptvsd/pull/729) and I'll address the issue properly later on.

So, please integrate that pull request but leave this issue open until I address the issue of redirecting all logging through debugger messages.
