### ISSUE TITLE
On stackTrace should provide stack trace for any live thread

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#72]
https://github.com/Microsoft/PTVS/issues/3736

**Comment by karthiknadig** [comment]
This is not done yet. We have following pending items:
1. A way to tell pydevd to suspend all threads on (breakpoint/exception/etc). There is currently a mechanim but that path does not use breakpoint_id's which we rely on.
2. Get a notification from pydev that all threads are suspended. Currently there is only a way to tell if individual threads are suspended. we need a way to tell if all threads are suspended.

**Comment by fabioz** [comment]
The part related to pydevd is on my todo-list (my current item is path mapping issues across platforms and right after this deal with the thread suspension policy).

**Comment by DonJayamanne** [comment]
@karthiknadig @fabioz Would be great if we have separate issues for those and linked them in here. That way we know what the pre-requisites are for this issue to be looked at. I.e. easier to track the status of this.

**Comment by fabioz** [comment]
Starting to take a look at this.

**Comment by fabioz** [comment]
After working a bit on how to provide a message saying that all threads are suspended I got into corner cases where this cannot be reliably done because to actually pause a thread some tracing event is required, but by pausing a thread it's possible that we get into situations where this never happens and waiting for such a message would not work (i.e.: it would effectively deadlock).

I'm posting an example below where this happens:

```
import threading
import time

go_on = threading.Event()
lock = threading.Lock()
counter = 0


def method():
    global counter
    with lock:
        counter += 1
    go_on.wait()
        

threads = [threading.Thread(target=method) for _ in range(3)]

for t in threads:
    t.start()

while counter < 3:
    time.sleep(.1)    

print('breakpoint with suspend_all here')  # Will never be able to suspend all threads if they reached go_on.wait() as no tracing event will be generated for the thread after reaching that point.

go_on.set()
```

So, not sure how to proceed... the feature requested seems to be getting the stack of threads even if they're not paused, so, maybe the best approach would be actually implementing that feature (creating a `GET_THREAD_STACK` command which can be used to get the stack for any running thread by using `sys._current_frames`).

@karthiknadig do you think that's reasonable?

**Comment by karthiknadig** [comment]
@fabioz We will need the `suspend_policy` in `CMD_SET_BREAK` (currently it is only available if we don't use `breakpoint_id`). That along with `GET_THREAD_STACK` should be enough.

**Comment by fabioz** [comment]
@karthiknadig ok, will work on that. 

Although I'll only start those next Monday as I ended up chasing a deadlock today -- there's a pull request for it with the fix at: https://github.com/Microsoft/ptvsd/pull/591 -- I got reports from it when using `scapy` and attaching the remote debugger, so, it'd be interesting to merge it before another release as I think it's a pretty critical issue.

**Comment by karthiknadig** [comment]
Following items are pending on ptvsd side:
- [ ]  Set the flag to suspend all while setting breakpoints
- [x]  Pause should send suspend request to all threads
- [ ]  Continue should send run request to all threads
- [ ]  Use the new get stack trace pydevd command to retrieve stack for running threads

**Comment by DonJayamanne** [comment]
> Use the new get stack trace pydevd command to retrieve stack for running threads

Can't we use this approach to get stack trace of suspended threads as well. Instead of using the current approach of strong some stack trace into a variable. I.e. request on demand.
