### ISSUE TITLE
Pre-defined breakpoint does not work (remoting Mac -> Ubuntu).

### ISSUE THREAD

**Issue by ericsnowcurrently** [Microsoft/ptvsd#751]
## Environment data

- PTVSD version: master
- OS and version: OSX + Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio: VSC

## Actual behavior

Upon attaching I get the following message in the running process:

   pydev debugger: warning: trying to add breakpoint to file that does not exist: /Users/esnow/projects/ptvsd-bug-bash/script.py (will have no effect)

and the breakpoint I had set does not work.  Note that the path in the warning is from the Mac.  The path to the running script (on Ubuntu) is different.

## Expected  behavior

The pre-defined breakpoint works.

## Steps to reproduce:
1. run the script on the remote machine (Ubuntu)
1. open the folder containing the script (in VSC on Mac)
1. set the `host` setting in the launch config to the address of the remote machine
1. select the proper launch config
1. set a breakpoint (in the infinite loop)
1. start debugging

Here's the script I used:

```python
import sys
import time
import ptvsd


# you can use one of three things here
# 1 Wait for attach ptvsd.wait_for_attach()
# 2 Use is attached loop:
# while not ptvsd.is_attached():
#        time.sleep(0.1)
# 3 Nothing. Enable attach should allow you to connect and pause

def main():
    print('waiting for attach...')
    i = 1
    while not ptvsd.is_attached():
        print('.', end='')
        if not i % 5:
            if not i % 10:
                print()
            else:
                print(' ', end='')
        sys.stdout.flush()
        time.sleep(0.1)
        i += 1
    print('\n')

    while True:
        # You can either hit pause or use the ptvsd.break_into_debugger()
        # ptvsd.break_into_debugger()
        print('hello')  # Set breakpoint here.
        time.sleep(0.3)


if __name__ == '__main__':
    ptvsd.enable_attach(('0.0.0.0', 5678))
    main()
```

**Comment by karthiknadig** [comment]
You have to use pathmappings for this to work.

**Comment by omartin2010** [comment]
In launch.json, there used to be (for the non experimental debugger) properties “localRoot” and “remoteRoot” that were meant for that. Dis this change with the latest code? I’ll look when om my computer where this pathmapping is located, probably a property of the class or something’.

**Comment by karthiknadig** [comment]
@omartin2010 
> Dis this change with the latest code?

Yes,  `localRoot` and `remoteRoot` were moved into `pathMappings`. They can be used like this:
```json
        {
            "name": "Attach",
            "type": "pythonExperimental",
            "request": "attach",
            "port": 5678,
            "host": "localhost",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "<remote directory path>"
                },
            ]
        },
```

**Comment by omartin2010** [comment]
I have found this but had to play with VSC to open it from the right folder because I had error messages like : 
/Users/esnow/projects/ptvsd-bug-bash/non_existing_directory/c:/users/omartin/.../directory2

so it would append the complete local path to the remote path. Not sure I understand how this is supposed to work but I ended up having to, because the root paths aren't the same on both systems, and in the remote system, my script was in directory1, and on the local system, in directory2, I ended up having to relaunch VSC by opening up directory2 as a work directory. I could not stay one directory above and write, say, "localRoot": " ${workspaceFolder}/directory2". This would trigger the whole path above. I'm sure this isn't expected, or I don't understand how that works.

**Comment by karthiknadig** [comment]
I tested this with a similar layout:
**local machine:** `C:\GIT\testscripts\directory2\pytest.py`
**remote machine:** `C:\Users\kanadig\Source\Repos\pyscripts\directory1\pytest.py`

**pytest.py**:
```python
import ptvsd
import time

ptvsd.enable_attach()


def main():
    count = 0
    while True:
        count += 1
        print(count)
        time.sleep(0.3)


main()

```
Launched that on the remote machine, as:
`C:\Users\kanadig\Source\Repos\pyscripts\directory1>py -3.7 pytest.py`

I had opened `C:\GIT\testscripts` in VSC, and used this in **launch.json**:
```json
    {
            "name": "Attach",
            "type": "pythonExperimental",
            "request": "attach",
            "port": 5678,
            "host": "winpytest2",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}\\directory2",
                    "remoteRoot": "C:\\Users\\kanadig\\Source\\Repos\\pyscripts\\directory1"
                },
            ]
        },
```

That worked for me:
![image](https://user-images.githubusercontent.com/3840081/44295793-fc697880-a264-11e8-92ad-0609203a010e.png)

Let me know if this works for you.

**Comment by omartin2010** [comment]
Seems like it's working (my other end was a Linux machine) but for the local path. Here's what I've comep to realize was my problem. I was putting a forward slash on my local path "${workspaceFolder}/dir1" instead of "${workspaceFolder}\\dir1" and this generates a remote path like "/mnt/local_linux_path/c:/etc/" where "/mnt/local_linux_path" is "remoteroot" and c:/etc/ is the path generated by my "mistake". Wouldn't it be easier of we simply treated the / like \\?

**Comment by karthiknadig** [comment]
> Wouldn't it be easier of we simply treated the / like \?

Agreed. We will use this #762 to track the work.
