### ISSUE TITLE
Incorrect frame for breakpoint

### ISSUE THREAD

**Issue by huguesv** [Microsoft/ptvsd#752]
## Environment data

- PTVSD version: today's master
- OS and version: Win10
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio: Visual Studio

## Steps to reproduce:
1. Type this code and set breakpoint on line 9 as in the picture and start debugging.
```
import threading
from queue import Queue
import time

print_lock = threading.Lock()

def get_url(current_url):

    time.sleep(2)
    with print_lock:
        print("\nStarting thread {}".format(threading.current_thread().name))

def process_queue():
    while True:
        current_url = url_queue.get()
        get_url(current_url)
        url_queue.task_done()

url_queue = Queue()

url_list = ["https://www.google.com"]*5

for i in range(5):
    t = threading.Thread(target=process_queue)
    t.daemon = True
    t.start()

start = time.time()

for current_url in url_list:
    url_queue.put(current_url)

url_queue.join()

```

![image](https://user-images.githubusercontent.com/1696845/44122248-dba913c4-9fd7-11e8-9b16-2c36f9a3dfcc.png)

## Actual behavior

VS breaks on line 16.

## Expected  behavior

VS breaks on line 9.

**Comment by karthiknadig** [comment]
This looks like it is paused on the wrong thread. VS UI shows the last paused thread instead of the thread that hit break point. We could probably use `preserveFocusHint` to control that.

**Comment by karthiknadig** [comment]
@DonJayamanne Can you look at this change https://github.com/karthiknadig/ptvsd/commit/cf7a5f63bb0a064a583436bd0689ff25d84c13f7 ? Basically VS has special requirements about `stopped` Event. 
see: https://github.com/Microsoft/VSDebugAdapterHost/wiki/Differences-between-Visual-Studio-Code-and-the-Visual-Studio-Debug-Adapter-Host#stopped-event

There is a bit more to it. we have to send stopped event if the `reason in  ['breakpoint', 'exception', 'step']` events, even if we sent a stopped event with `reason== 'pause'` otherwise VS has no clue which stack to show.
