### ISSUE TITLE
Add way to ignore exception handler

### ISSUE THREAD

**Issue by zooba** [microsoft/ptvsd#757]
When writing a framework, there are cases where I want to handle all exceptions from a call into user code. However, this means that the "unhandled exception" filter no longer works properly.

It would be great if there was some marker (a comment? a function decorator?) that I could put in my framework code to ensure that exceptions handled by that function are first handled by the debugger.

**Comment by fabioz** [comment]
It should probably be a comment so that the user doesn't need to import the debugger to make it work.

As a note, there are already other cases where comments already determine how the debugger works in `pydevd`.

i.e.: 
- `# @IgnoreException` where an exception is raised won't be shown as a caught exceptions.
- The debugger doesn't step into methods with `# @DontTrace`.

Maybe for this case, a method could be marked with a comment such as `# @HandleUncaughtException`?

**Comment by gramster** [comment]
Old issue, no upvotes, there are workarounds. Closing.
