### ISSUE TITLE
Multithreaded debugging only breaking on main thread.

### ISSUE THREAD

**Issue by crwilcox** [Microsoft/ptvsd#776]
I filed https://github.com/Microsoft/vscode-python/issues/2103 on vscode, but was asked to file here as well. The other issue has an archive that has code that will try to run multiple threads. Breakpoints on child threads are not hit.

@brettcannon investigated this further and found that it won't stop on the breakpoints, but logpoints are executed.

My sample code unfortunately requires creds for an external service. It seems @brettcannon found spawning child threads was enough to show the inability to break.

**Comment by karthiknadig** [comment]
This should be fixed in the master. There is a cosmetic issue in master of which thread is displayed by the UI. This is because we currently do set the `preserveFocusHint` field in the thread stopped event.
![image](https://user-images.githubusercontent.com/3840081/44868989-4416d980-ac41-11e8-8fc4-023798ffe055.png)

**Comment by karthiknadig** [comment]
Fixed via #778
