### ISSUE TITLE
Debug console is now outputting tabs as spaces

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#824]
## Environment data

- PTVSD version: Latest
- OS and version: Mac & Windows
- Python version (& distribution if applicable, e.g. Anaconda): N/A
- Using VS Code or Visual Studio:VSC

## Actual behavior

Tabs are converted into spaces when output is displayed in VS Code debugger output window.

## Expected  behavior

Tabs should not be replaced with spaces

## Steps to reproduce:
1. Debug the following code:
* `print("Hello\tWorld")`
2. The output in the terminal is correct.
3. The output in the debug console window is incorrect it is `Hello<single space>World`

**Comment by DonJayamanne** [comment]
@karthiknadig 	@int19h 
I won't be labelling the issues I create, this way its easier for your team to find issues that you haven't triaged and added appropriate labels.

**Comment by karthiknadig** [comment]
@int19h Looks like the XML parser in `wrapper.py` is replacing the `\t` with ` `. I am not able to find any setting for that.

**Comment by int19h** [comment]
That's probably just standard XML whitespace normalization (if so, it should also collapse multiple spaces into single). I think it can be fixed by changing `Handler` in `untangle.py` and adding [`ignorableWhitespace`](https://docs.python.org/2/library/xml.sax.handler.html#xml.sax.handler.ContentHandler.ignorableWhitespace) method, that does the same thing as `characters` method.

**Comment by int19h** [comment]
Actually no, that's not it - it doesn't collapse multiple spaces (or tabs).

**Comment by int19h** [comment]
Oh, I see - it's because the text is passed as an attribute. And then [attribute value normalization](https://www.w3.org/TR/xml/#AVNormalize) applies. 

This is technically a bug on pydevd side of things - it should escape significant tabs, just like it quotes newlines. The parser is doing the right thing here. That said, there might be some way to modify this behavior via `setFeature` - let me take a look.
