### ISSUE TITLE
BreakOnSystemExitZero debug option is not respected

### ISSUE THREAD

**Issue by huguesv** [Microsoft/ptvsd#841]
## Environment data

- PTVSD version: 4.1.3
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Using VS Code or Visual Studio: VS

## Actual behavior

Debugger breaks on `sys.exit(0)` even when the option to break on zero is disabled:

![image](https://user-images.githubusercontent.com/1696845/46029474-60732e00-c0a8-11e8-8ce4-88ab0dc8008f.png)

## Expected  behavior

Debugger only breaks on `sys.exit(0)` if the option is enabled.

## Steps to reproduce:
1. In tools, options, python, debugging, uncheck "Break on SystemExit exception with exit code of zero"
2. Debug this code:
```
sys.exit(0)
```

Edit: FYI all Python exceptions were unchecked:
![image](https://user-images.githubusercontent.com/1696845/46029708-0a52ba80-c0a9-11e8-9121-fc4b58f45289.png)

**Comment by huguesv** [comment]
VSC may not have a way to set this option, but when using VSC with the old ptvsd, it was not breaking on sys.exit(0) and now it is breaking on it with new ptvsd.

**Comment by JenusL** [comment]
Please fix this soon. It's so annoying.

**Comment by huguesv** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/362033/sysexit0-gives-us-an-error-instead-of-exit.html

**Comment by karthiknadig** [comment]
This is the expected behavior after discussing with @huguesv . The debugger currently does not follow this table. When fixing this bug we must ensure the behavior matches this.

| WaitOnNormalExit | WaitOnAbnormalExit | BreakOnSystemExitZero | Expected Behavior |
|------------------|--------------------|-----------------------|-------------------|
| False | False | False | <ul><li>Don't exception break if exitcode = 0</li><li>Exception break if exitcode ≠ 0</li> <li>Don't wait for user input</li></ul> |
| False | False | True | <ul><li>Always exception break on SystemExit</li><li>Don't wait for user input</li></ul> |
| False | True | False | <ul><li>Don't exception break if exitcode = 0</li> <li>Exception break if exitcode ≠ 0</li> <li>Wait for user input if exitcode ≠ 0</li></ul> |
| False | True | True | <ul><li>Always exception break on SystemExit</li> <li>Wait for user input if exitcode ≠ 0</li></ul> |
| True | False | False | <ul><li>Don't exception break if exitcode = 0</li> <li>Exception break if exitcode ≠ 0</li> <li>Wait for user input if exitcode = 0</li></ul> |
| True | False | True | <ul><li>Always exception break on SystemExit</li> <li>Wait for user input if exitcode = 0</li></ul> |
| True | True | False | <ul><li>Don't exception break if exitcode = 0</li> <li>Exception break if exitcode ≠ 0</li> <li>Always wait for user input</li></ul> |
| True | True | True | <ul><li>Always exception break on SystemExit</li> <li>Always wait for user input</li></ul> |
