### ISSUE TITLE
Send variable details so variable window doesn't collapse them while stepping

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/ptvsd#870]
Microsoft/vscode-python#645

**Comment by karthiknadig** [comment]
ptvsd has no information about the state of the variable window. There is no debug adapter message support for such a thing. This does not feel a issue that can be fixed on the python side of things.

**Comment by fabioz** [comment]
@karthiknadig from https://github.com/Microsoft/vscode/issues/32199#issuecomment-321597173, it seems that this is really from ptvsd... I haven't checked, but I know ptvsd does some translations back and forth from the `pydevd` structure to what the debug adapter expects -- is it possible that new ids are being generated instead of keeping an existing id in place for the frame or variables?

**Comment by karthiknadig** [comment]
@fabioz That is a good suggestion. We do update the ids for frames and variables. That is something we can fix.

**Comment by karthiknadig** [comment]
I am converting this to a tacking bug. We need to make two separate set of changes, to get this working correctly.
