### ISSUE TITLE
Attach session fetches source files even when it's local

### ISSUE THREAD

**Issue by int19h** [microsoft/ptvsd#915]
When using attach to connect to a local-running process, VSC insists on fetching the source of any file in which a breakpoint is hit, and display it in a separate tab from the same file being already opened in the editor. E.g. suppose I have a Flask app in C:\Temp\fltest. I open C:\Temp\fltest\app.py in the editor, and set a breakpoint somewhere, then cause it to be hit. VSC opens a new tab titled app.py next to the existing one, and shows the location where the breakpoint was hit there (but doesn't show the breakpoint!).

I think this is just overzealous source fetching. It shouldn't do it for local connections at all, and just report full file paths in this case.

**Comment by karthiknadig** [comment]
We currently require users to provide path-mappings in attach scenario (local or remote). We have a bug open to provide a better way to auto map, and use source retrievals as a fallback.

**Comment by qubitron** [comment]
Verify that default '.' path-mappings fix this

**Comment by karthiknadig** [comment]
The default path mapping fixes cases where this is available. VSC is able to provide this, but in VS case the default path mappings are not available. Especially when running projects.

**Comment by qubitron** [comment]
Does ptvsd know the workspace root? Can it default to ${workspaceRoot} and '.' when no path mappings are provided?

**Comment by karthiknadig** [comment]
Talked with @huguesv about this. For VS if we do this https://github.com/Microsoft/PTVS/issues/3960#issuecomment-461597348, then it will have similar behavior to VSC. i.e., provide default path mappings.

> Does ptvsd know the workspace root? Can it default to ${workspaceRoot} and '.' when no path mappings are provided?

Assuming the above comment is PTVS works. Then this issue is relevant only for IDE versions where the defaults are not available. We will have another issue though, if ptvsd always assumes ${workspaceRoot} and '.' mapping, **without** getting it from the IDE, users who have "remote only" source will **not** be able get remote source. Source reference is turned off when path mapping is used. Right now, users can turn-off the default path mapping, and make use of the source reference feature. If `ptvsd` makes that assumption then they wont be able to turn it off.

There is a cleaner solution. A thing we want to try and see is, what happens if we provide both source path and source reference to the IDE. The DAP spec states either `source.Path` or `source.Reference` should be used. If the IDE can try the path first and then if that fails use the source reference that would make this cleaner on the ptvsd side. If this is not possible we should see if we can get them to allow both to be sent. This would solve the problem generally for other languages too.
