### ISSUE TITLE
Test does not kill all processes

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/ptvsd#940]
## Environment data

- PTVSD version: master
- OS and version: Any
- Python version (& distribution if applicable, e.g. Anaconda): Any
- Using VS Code or Visual Studio: console

## Actual behavior

After running full set of tests, often there are python test instances left behind.

## Expected  behavior

Test should kill all processes launched as a part of the test.

## Steps to reproduce:
Run all tests under [pytests](pytests) a bunch of times

**Comment by int19h** [comment]
All tests that use `debug_session` have a separate watchdog process that will clean up if necessary (and complain). So this is most likely coming from some of the tests that create `DebugSession` instances explicitly and use them to attach to an already-existing ptvsd process - i.e. for multiproc. 

In general, for those instances, the test should `wait_for_terminate`. If the child process does not exit naturally, the test might also need to issue a "terminate" request.

But since tests can time out before that, it should also spin up a watchdog for every such manually managed process, as a final line of defense:
```py
from pytests.helpers import watchdog
watchdog.create(pid)
```
(the tests can't *rely* on the watchdog though, since it will only kill any stray processes when the main test process exits - not when test finishes running.)

**Comment by karthiknadig** [comment]
I have not seen this occur since the auto kill. Closing this, will reopen if seen again.
