### ISSUE TITLE
Tests timing out on Mac

### ISSUE THREAD

**Issue by gramster** [Microsoft/ptvsd#953]
## Environment data

- PTVSD version: cloned from master on 10/23
- OS and version: MacOS 10.14
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda, Python 3.6.6
- Using VS Code or Visual Studio: N/A

The following tests time out and I had to change them to skip:

test_flask.py:
- test_flask_breakpoint_no_multiproc
- test_flask_exception_no_multiproc
- test_flask_breakpoint_multiproc

test_socket.py:
- test_reuse_same_port

**Comment by karthiknadig** [comment]
Can you run the failing test with `-vvs` ? That will give me a better idea of what is going on.

**Comment by gramster** [comment]
For the socket one, the test just looks like it should fail, so the behavior I see is expected but that makes the test wrong:

=================================== FAILURES ===================================
__________________ TestSocketServerReuse.test_reuse_same_port __________________

self = <pytests.test_socket.TestSocketServerReuse object at 0x11f092630>

    def test_reuse_same_port(self):
        try:
            sock1 = create_server(self.HOST1, self.PORT1)
>           sock2 = create_server(self.HOST2, self.PORT1)

pytests/test_socket.py:26:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

host = '127.0.0.2', port = 7890, timeout = None

    def create_server(host, port, timeout=None):
        """Return a local server socket listening on the given port."""
        if host is None:
            host = 'localhost'
        server = _new_sock()
        try:
>           server.bind((host, port))
E           OSError: [Errno 49] Can't assign requested address

ptvsd/socket.py:79: OSError

During handling of the above exception, another exception occurred:

self = <pytests.test_socket.TestSocketServerReuse object at 0x11f092630>

    def test_reuse_same_port(self):
        try:
            sock1 = create_server(self.HOST1, self.PORT1)
            sock2 = create_server(self.HOST2, self.PORT1)
            assert sock1.getsockname() == (self.HOST1, self.PORT1)
            assert sock2.getsockname() == (self.HOST2, self.PORT1)
        finally:
            close_socket(sock1)
>           close_socket(sock2)
E           UnboundLocalError: local variable 'sock2' referenced before assignment

pytests/test_socket.py:31: UnboundLocalError

**Comment by karthiknadig** [comment]
Test test should ensure that same port can be reused if the addresses are different. The issue here seems to be that it is not allowing me to set '127.0.0.2'.

**Comment by karthiknadig** [comment]
Also, the behavior of this flag `socket.SO_EXCLUSIVEADDRUSE` is OS and flavor specific. The test here is trying to ensure we are getting the behavior we assume with the flag. See here for some more details: https://stackoverflow.com/a/14388707/111335

**Comment by gramster** [comment]
Why would it let you use 127.0.0.2? It's not bound to any interfaces. You'd presumably need to do an ifconfig first. lo0 is bound to 127.0.0.1 only by default. I'm surprised this works on any system (assuming it does).

**Comment by karthiknadig** [comment]
> I'm surprised this works on any system (assuming it does).

Windows supports 127/8 loopback IP addresses, has been since WinXP Service Pack 2 ([KB884020](https://support.microsoft.com/en-us/help/884020/programs-that-connect-to-ip-addresses-that-are-in-the-loopback-address)). I tested this on my ubuntu machine and it supported 127/8 loopback as well. So I assumed this might be standard. 
![image](https://user-images.githubusercontent.com/3840081/47514533-799d0500-d835-11e8-8ad9-d96e46f320e0.png)

As for this issue. We have this test because the `SO_REUSEADDR` flag on windows means that two sockets instances can bind to the same address and port. Which of the two will receive the connection is non-deterministic. For users, this means that they could have the debugger running locally in two different processes listening to the same port. When you connect with VSC/VS there is no way to tell which one they connect to. To fix this windows has a different flag `SO_EXCLUSIVEADDRUSE`, which makes the behavior as you would expect: the second process binding to the socket with same address and port should fail. However, if the address is different it should NOT fail.

I want to avoid adding additional loopback addresses if they are not already supported. So, I will look into an alternate way to test this. One possibility is to try 'localhost' and '0.0.0.0' on linux/Mac. This may have to be special cased for linux/mac since '0.0.0.0' won't work on windows as it will trigger firewall; any process launched with 'no window' or background process by a 'windowed' process will trigger a firewall response.

**Comment by gramster** [comment]
Linux and Mac do too. But before you can listen to an address it must be bound to an interface, and the loopback interface binds 127.0.0.1 only out of the box. In any event, there is no re-use if you bind 127.0.0.1 and 127.0.0.2; those are distinct addresses. And SO_REUSEADDR does not allow listening on the same addr/port combo; you need SO_REUSEPORT for that (on Linux/Mac; I don't know about Wndows). And I think you have to use setsockopt.

**Comment by karthiknadig** [comment]
We don't want to listen to same addr/port combo so i don't think we should be enabling `SO_REUSEPORT`. There are historical reasons why we need SO_REUSEADDR. We can discuss those offline.

**Comment by karthiknadig** [comment]
This should be fixed by #961 . I used travis osx build to test this since:
py2.7 https://travis-ci.org/karthiknadig/ptvsd/jobs/446792874
py3.6 https://travis-ci.org/karthiknadig/ptvsd/jobs/446792876
