### ISSUE TITLE
Bad except clauses order

### ISSUE THREAD

**Issue by 42B** [Microsoft/ptvsd#962]
https://github.com/Microsoft/ptvsd/blob/9920fceb0584403a79195af5a22e1ab46228ee3c/ptvsd/ipcjson.py#L204-L210

These exceptions seem to be in the wrong order since `JSONDecodeError` inherits from `ValueError`. At first glance, that could be fixed by simply move catching `JSONDecodeError` above `ValueError`.

```python
        try:
            msg = json.loads(content)
            self._receive_message(msg)
        except json.decoder.JSONDecodeError:
            raise InvalidContentError('Error deserializing message content.')
        except ValueError:
            raise InvalidContentError('Error deserializing message content.')
```

The issue then is that they are also exactly the same exception being raised so merging the two exceptions into one tuple could be another option.

```python
        try:
            msg = json.loads(content)
            self._receive_message(msg)
        except (json.decoder.JSONDecodeError, ValueError):
            raise InvalidContentError('Error deserializing message content.')

```

The last question would be if both exceptions are really necessary. As long as a string is being passed to `json.loads`, shouldn't the only exception ever being raised be `JSONDecodeError`? If `self._receive_message` needs to catch a `ValueError` then this tuple might still work. Otherwise, maybe something like this would be preferable?

```python
        try:
            msg = json.loads(content)
        except json.decoder.JSONDecodeError:
            raise InvalidContentError('Error deserializing message content.')
        else:
            self._receive_message(msg)

```

I didn't send a PR yet because I have no idea which of these potential solutions would be preferred.

**Comment by int19h** [comment]
This is legacy code that will be removed in near future ([messaging.py](/Microsoft/ptvsd/blob/master/ptvsd/messaging.py) replaces it), so there's no point fixing this now.

FWIW, I think the reason why it was written this way is because it has to also run on Python <3.5, which doesn't have `JSONDecodeError` at all. Hence why the first `except`-block catches `ValueError` - that is the one that'll be tripped on 2.7, and it won't even try to access the non-existent attribute in the second block (hence why it couldn't be a tuple - a tuple would evaluate both elements before matching against the exception).

You're right that even so, it could have been handled simply by catching `ValueError`. I think the fact that `JSONDecodeError` is derived from `ValueError` was something that the original author didn't notice.
