### ISSUE TITLE
Remote debugging not working with multiproc

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#984]
## Environment data

- PTVSD version: Master and Release
- OS and version: All
- Python version (& distribution if applicable, e.g. Anaconda): N/A
- Using VS Code or Visual Studio:VSC

## Actual behavior

Breakpoints don't hit when remote debugging a django app inside of a docker container

## Expected  behavior

Breakpoints hit when debugging a django app inside of a docker container

## Steps to reproduce:
1. Clone this repo: https://github.com/qubitron/django-docker
2. Set breakpoints inside of the views in views.py
3. Run the Docker: compose up command
4. Use the attach debug config

**Comment by int19h** [comment]
Is this with `--multiprocess`? If so, that does not support remote (all child processes wait for connections on `localhost`).

**Comment by karthiknadig** [comment]
Looking at the docker file, this is doing multiproc:
```
CMD ["python3", "-m", "ptvsd", "--host", "0.0.0.0", "--port", "5678", "--wait", "manage.py", "runserver", "0.0.0.0:8000"]
```
that definitely won't work with `ptvsd==4.1.4`. Multiproc in `ptvsd==master` currently works only with `localhost`.
@int19h is making the change to enable subprocess to work with the same host as parent.

**Comment by karthiknadig** [comment]
Removing `regression` and `priority:P0`, since this is not a regression (never supported multiproc in 4.1.4). This is an enhancement, since we had only talked about local multi proc. However, we have a PR that will allow remote multi proc.

**Comment by myusrn** [comment]
I can make ptvsd work using manage.py calls and command line python -m ptvsd --host 0.0.0.0 --port 5678 manage.py runserver --noreload but when i try and use either within context of docker container using ubuntu:18.04 the 5678 port listener isn't created.

If i docker -it exec django_webservice bin/bash into the container and do a pip list i see ptvsd and if i do a netstat -tunlp it shows nginx web server tcp/80 listener but not the ptvsd tcp/5678 port so it doesn't matter that i exposed port in "docker run -p 8000:80 -p 5678:5678 . . . " command it seems something about initializing ptvsd from within that environment isn't working. i tried adding Dockerfile EXPOSE 5678 in addition to EXPOSE 80 that was already there and that makes no difference and docs suggest EXPOSE is optional documentation syntax only.

Any thoughts on how to debug "docker run . . . " to determine what's causing failure?

**Comment by int19h** [comment]
If you're using a relatively recent version of VSCode and the Python extension, you should be using https://github.com/microsoft/debugpy on the server - see if that helps.

Also, recent versions of the Docker extension for VSCode support regular debugging workflow (F5) in containers - it might be the easiest way for you to do this, since you wouldn't have to mess with command line and ports at all.

**Comment by myusrn** [comment]
@int19h thanks for the response and suggestions.  

I am using the latest vscode 1.48.2 install and msft python [ ms-python.python ] extension v2020.8.103604.  The issue isn't it seems with vscode + python extension remote attach debugging behavior, since i can make it all work using localhost non-container deployment of django app using builtin django web server [ runserver ].  

The issue seems to be with enabling the debugpy 1.0.0rc2 listener in the container deployment case where django is run on top of nginx web server.  If i exec into that running container `docker exec -it django_webservices /bin/bash` and then look for listening ports `netstat -tunlp` i only see the nginx web server port 80 listener so it doesn't matter if i'm using `docker run -p 8000:80 -p 5678:5678 . . . ` to expose the debugpy agent listening port debugger from outside the container the issue seems to be the port never gets started up inside the container. 

From the running container interactive bash shell session i tried executing `python3 -m debugpy --listen localhost:5678 /home/docker/code/app/myapp/manage.py collectstatic --noinput` and following that another `netstat -tunlp` but still no sign of 5678 listener. So it seems in addition to manage.py `import debugpy; debugpy.listen(('0.0.0.0', 5678))` starting it using python manage.py command line arguments doesn't work in my environment.  Not sure how else to debug why.

As for the alternative vscode msft docker [ ms-azuretools.vscode-docker ] extension v1.5.0 support for f5 build, run and attach to container process debugging support that seems like good story for localhost docker container deployment.  It's not going to work when i need to remote debug attach to deployment of container in cloud container, e.g. aws eks, azr aks, gcp gke,  deployments correct?

**Comment by int19h** [comment]
Yes, I think their story is primarily about localhost. 

Can you file a separate bug for this in the debugpy repo? I think this is more about figuring out how to set up Docker in this case, but it'll be easier to track separately even so.

Another thing you might want to try is to have the container connect back to the IDE, instead of the other way around. This is not fully documented in all the appropriate places yet, but [this](https://github.com/microsoft/vscode-python/issues/10379#issuecomment-593557124) should have enough information to try.

**Comment by myusrn** [comment]
@int19h thanks again for followup response and suggestions.

I will file a separate issue with repro details in https://github.com/microsoft/debugpy issues.  I like the option of trying to have the debugpy reach back out to the IDE in listener mode.  

Do you know if there a special dns address for resolving the address of the desktop vscode ide from within a docker hosted container, as compared to the remote k8s hosted container, given within that container localhost and 127.0.0.1 would refer to just the container?  I thought i saw somewhere that "docker.for.mac.localhost" and "docker.for.win.localhost" are special case dns addresses for mac and windows docker setups respectively but not sure if they apply in this agent -> ide connection case.
